### PR TITLE
Rename and fix overfit_pct, val_percent_check and test_percent_check

### LINKED ISSUE #830: `overfit_pct` vs `train_percent_check` etc
As far as I can make out, the (only?) purpose of  `overfit_pct` is to overwrite the values of `train_percent_check`, `val_percent_check`, and `test_percent_check`. If that is the case, then I think we should 
- make  the names more similar (e.g. `data_percent_check`)
- move the positions of the arguments closer together (so that it suggests a relation)
- update the docs to reflect that (I found the docs confusing)

Also, the default value should not be `0.0` but `None`.

Another option would be to drop it completely for the sake of simplification. Not sure.

### LINKED ISSUE #1668: Ditch Trainer percent arguments, make overfit great again
## 🚀 Feature

Replace `*_percent_check` with `limit_*_batches` and redesign `overfit_pct` Trainer arguments. 

### Motivation

Over the past few days I was struggling to use these parameters in my tasks. For a example, I want to run a test on model overfitting for an image classification problem. I would take a few (say, 2) batches from my train dataset and train several epochs on them. Then I would assert 100% accuracy on these train batches.

The problems I stumbled on are the following:

1. `overfit_pct` documentation is misleading. Recently a clarification was made that it sets `*_percent_check` parameters to a given value, but it still doesn't actually help to overfit a model since you can't simply run `trainer.test()` or `trainer.run_evaluation()` without manipulating model's dataloaders after running `trainer.fit(model)`. 
2. If the value of the `val_percent_check` is too small, which actually can happen if you use `overfit_pct` with small training dataset in mind, you just silently skip validation loop and run into an exception in `model.validation_epoch_end` trying to accumulate loss for batches. Yeah, handling the latter is reasonably on me since I override this method but it will be much nicer if such unexpected loop-skip is checked by Pytorch-Lightning. You guys are great and I want to love your project even more!
3. `train_percent_check` doesn't guarantee training on the same small part of the training dataset for every epoch because *it is a best practice to shuffle your training data every epoch*. As a result, new batches are formed every epoch and thus no overfitting :( 

### Pitch

1. I find redesigning these dataset limiting parameters as **absolute number of batches** more straightforward and desired than now. After all, I dare to say that most of the researches and developers are thinking in terms of number of bathes rather than percent of dataset.
2. `overfit_pct` is either removed or actually redesigned to help test overfitting, i.e. replacing validation or test loader with train loader. Ensure that training dataset isn't shuffled and the same batches are trained on every epoch.

### Additional notes

I realize that you cannot prohibit shuffling in case of using simply `*_percent_check` parameters. There can be experiments where you would like to see how your model performs training only on a portion of data. Therefore such prohibition is valid only for overfit mode.

### PR DESCRIPTION
**Pull request by williamFalcon**
Fixes #1668
Fixes #1920 
Fixes #830 

## Overfit
- Removes `overfit_pct`
- Adds `overfit_batches` which can be a float (%) or int (steps)
- overfit now makes sure train, test and val splits are all the train step
- sets shuffle=False in the train set

## limit_xxx_batches
- removes `train_percent_check` and `val_percent_check`
- replaces with `limit_train_batches` and `limit_val_batches` which can also be int (steps) or percent (float)

## docs + tests
- adds tests to verify
- updates docs

@tullie these flag names make sense?

### TODO: also replace train_percent_check with limit_train_batches

### CODE REVIEW

**Comment by awaelchli** [comment]
@williamFalcon are you trying to fix this: #1920  ?

**Comment by williamFalcon** [comment]
@awaelchli partly. also enabling this to take a number of batches instead of just a percent.

**Comment by williamFalcon** [comment]
@awaelchli @Borda take a look?

**Comment by awaelchli** [comment]
besides the new Trainer flags, it's not easy to see what's the difference to #1920. It seems you have re-implemented it.

**Comment by Borda** [comment]
> @williamFalcon are you trying to fix this: #1920 ?

> @awaelchli partly. also enabling this to take a number of batches instead of just a percent.

so shall #1920 be merged first? otherwise, it may raise plenty of conflicts...

**Comment by Borda** [comment]
btw, this was not reviewed as @awaelchli @Borda asked to rebase it on #1920

**Comment by tullie** [comment]
I wonder if overfit_batches can be removed entirely. It's good to strive for an API where there's only one way to do things, and I feel like the problem with these trainer args is that it's not clear what the difference between setting overfit_batches=1 or limit_val_batches=1 and limit_train_val=1 is?

Regardless, this PR is still an improvement to how it was before. Is there any reason you didn't put deprecation warnings in?

**Comment by williamFalcon** [comment]
This was a two-part PR.
The warnings are here https://github.com/PyTorchLightning/pytorch-lightning/pull/2220

This was the time to remove overfit but i realized it actually serves a different approach.

overfit_batches will actually use the train set for train, val and test so you can truly overfit. It also removes the shuffle from the training set so you iterate over the same exact stuff.

However, the other 3 flags don't serve that purpose. Those are more for only using some of the data for training, val or test (likely for debugging purposes)

**Comment by pwl** [comment]
Hi, I'm getting an error
```
~/.local/lib/python3.7/site-packages/pytorch_lightning/callbacks/progress.py in total_val_batches(self)
     99             is_val_epoch = trainer.current_epoch % trainer.check_val_every_n_epoch == 0
    100             total_val_batches = trainer.num_val_batches if is_val_epoch else 0
--> 101             total_val_batches = sum(total_val_batches)
    102         return total_val_batches
    103 

TypeError: 'int' object is not iterable
```
from a line added in this PR: https://github.com/PyTorchLightning/pytorch-lightning/commit/04c794ca72f45dd492e49baff773c2b8e274b9ed#diff-c611176c04f224f1ec16a768aec9c527R101

Turns out `sum(0)` doesn't work in python, so maybe it should be
```
total_val_batches = sum(trainer.num_val_batches) if is_val_epoch else 0
```
I'm writing this here instead in a new issue, as this is a very fresh PR, I hope that's ok.  Also, I wonder how this got past the tests.

**Comment by Borda** [comment]
@pwl good catch, mind sending a fix PR?

**Pull request merged**
