### PR TITLE
Add argument `datamodule` using .fit() in docs

### PR DESCRIPTION
**Pull request by ydcjeff**
## What does this PR do?

Add argument `datamodule` in [the docs](https://pytorch-lightning.readthedocs.io/en/latest/datamodules.html#using-a-datamodule) since the default second argument is `train_dataloader`.

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
> Passing it the way that is described in the docs currently actually works for fit! Test doesn't do this, though. Perhaps you can close this?

it is not true, the actual API as expects dataloader as the second argument but you pass datamodule
https://github.com/PyTorchLightning/pytorch-lightning/blob/458d3e210e2da10482d97a996708731b8b0fabae/pytorch_lightning/trainer/trainer.py#L966-L972
and 
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1289-L1296

**Comment by williamFalcon** [comment]
nope. i enabled datamodules to be the secone argument. i guess i forgot to update the typing

**Comment by williamFalcon** [comment]
the real fix is to add datamodule to the types available for the second arg. but fit(model, dm) works and is the expected usage.

**Comment by Borda** [comment]
> nope. i enabled datamodules to be the secone argument. i guess i forgot to update the typing

but is it not in master yet and it is quite breaking change, no back compatibility...

**Comment by williamFalcon** [comment]
it is in master. it is not a breaking change. it’s additional support. try it out yourself

**Comment by Borda** [comment]
> it is in master. it is not a breaking change. it’s additional support. try it out yourself

ok, I see the if there... so the API a is a bit confusing as you can pass datamodule as `train_dataloader` argument and later we have also `datamodule` argument...
cc: @nateraw

**Pull request closed without merging**
