### PR TITLE
try to update failing dockers

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

prune some outdated code...
anyway, the failing seems to be a bit stochastic/random

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
well it seems to be some Horovd build issue:
```
#9 74.67   -- Found Pytorch: 1.6.0 (found suitable version "1.6.0", minimum required is "1.2.0")
#9 74.67   CMake Error at horovod/torch/CMakeLists.txt:21 (message):
#9 74.67     Horovod build with GPU support was requested but this PyTorch installation
#9 74.67     does not support CUDA.
```
@tgaddair have you seen it recently?

**Comment by ydcjeff** [comment]
@Borda this failing docker build has been fixed on master. #5203

**Comment by Borda** [comment]
> @Borda this failing docker build has been fixed on master. #5203

I thought so, but obviously failing still happens...

**Comment by ydcjeff** [comment]
> > @Borda this failing docker build has been fixed on master. #5203
> 
> I thought so, but obviously failing still happens...

I think you checkout from `release/1.2-dev`, not from master. maybe that's why

**Comment by tgaddair** [comment]
> well it seems to be some Horovd build issue:
> 
> ```
> #9 74.67   -- Found Pytorch: 1.6.0 (found suitable version "1.6.0", minimum required is "1.2.0")
> #9 74.67   CMake Error at horovod/torch/CMakeLists.txt:21 (message):
> #9 74.67     Horovod build with GPU support was requested but this PyTorch installation
> #9 74.67     does not support CUDA.
> ```
> 
> @tgaddair have you seen it recently?

Which test is failing, and which configuration is it?  Sounds like the problem is exactly what the message says: Horovod is being installed with GPU support but CUDA is not available in the PyTorch version.

**Comment by Borda** [comment]
> Which test is failing, and which configuration is it? Sounds like the problem is exactly what the message says: Horovod is being installed with GPU support but CUDA is not available in the PyTorch version.

yeah, that is strange the exactly same docker image works fine locally but fails in CI...
any idea how/why Conda installs Pytorch without Cuda support?

**Comment by Borda** [comment]
> > > @Borda this failing docker build has been fixed on master. #5203
> > 
> > I thought so, but obviously failing still happens...
> 
> I think you checkout from `release/1.2-dev`, not from master. maybe that's why

you are right but it still seems to be failing, see for example:
https://github.com/PyTorchLightning/pytorch-lightning/runs/1718565009?check_suite_focus=true
https://github.com/PyTorchLightning/pytorch-lightning/runs/1715289586?check_suite_focus=true
https://github.com/PyTorchLightning/pytorch-lightning/runs/1731706897?check_suite_focus=true

**Comment by ydcjeff** [comment]
I think that is random
all passed on today nightly event : https://github.com/PyTorchLightning/pytorch-lightning/actions/runs/504968398

**Comment by Borda** [comment]
ok, so let's use this pr just as cleaning the some not needed code...

**Review by carmocca — APPROVED** [review]

**Review by tchaton — APPROVED** [review]

**Review by rohitgr7 — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
