### PR TITLE
WandbLogger to log model topology by default

### LINKED ISSUE #8638: WandbLogger does not log model topology
## 🐛 Bug

Following the documentation [here](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.wandb.html), calling `.watch(model)` from the WandbLogger object should log model topology, but currently it does not.

Inspecting the code:

https://github.com/PyTorchLightning/pytorch-lightning/blob/c99e2fe0d2bf713f35054eaa0d521ee7f6030786/pytorch_lightning/loggers/wandb.py#L202-L203

WandbLogger does not pass a value for `log_model` parameter to the wandb object, which is `False` by default.

https://github.com/wandb/client/blob/5ce4a13f44e0d47693affd9a494dae5d91d42438/wandb/sdk_py27/wandb_watch.py#L17-L19

If I directly call `.watch()` from the wandb object, model topology is logged correctly.

```python
logger = WandbLogger()
logger.experiment.watch(model, log_graph=True)
````

### To Reproduce

Colab link to the BoringModel: https://colab.research.google.com/drive/1keZ8hlWt2vgJDgK4e2IiXiN68npfsPiJ?usp=sharing

### Expected behavior

WandbLogger should either automatically log model topology (by passing `log_graph=True` to wandb) or let the user specify that by adding `log_graph` as an extra optional keyword argument.

### Environment

From `collect_env_details.py`

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.4.0
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.11
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

### PR DESCRIPTION
**Pull request by gau-nernst**
## What does this PR do?

Fixes #8638 

- Add `log_graph=True` parameter to `WandbLogger.watch()` and pass it to `wandb.watch()`
- Update wandb logger test to include `log_graph`

Recently wandb introduces the parameter `log_graph` in `wandb.watch()`. By default, it is `False`, so model topology won't be logged (see [here](https://github.com/wandb/client/pull/2395))

### Does your PR introduce any breaking changes? If yes, please list them.

* log_graph=True by default.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by tchaton — APPROVED** [review]
LGTM ! Any idea of implication on training performance ?

**Comment by gau-nernst** [comment]
I don't think it will have any negative impacts on training performance, because it's just extra logging. This was the default behavior for wandb some time ago (before wandb client commit [#2395](https://github.com/wandb/client/pull/2395) on July 16)

I just found out that wandb added `log_graph=False` in their `wandb.watch()` in [this](https://github.com/wandb/client/pull/2358) and [this](https://github.com/wandb/client/pull/2395) commits. This means that earlier version of wandb client will throw an error  because we have passed an extra argument (I haven't tested this).

Should we raise the minimum version requirement for wandb logger? Or we discard my PR and leave the user handle this behavior by themselves? (which is what I'm doing for my project)

**Review by Borda — APPROVED** [review]

**Comment by awaelchli** [comment]
@gau-nernst if you merge master into this branch the failing gpu test will pass and we can merge.

**Comment by gau-nernst** [comment]
@awaelchli I have rebased from master and added an entry to CHANGELOG.md
The GPU test has passed now. Thank you for the support!

**Pull request merged**
