### PR TITLE
Fix shuffle for distributed sampler

### LINKED ISSUE #2703: `replace_sampler_ddp` doesn't create a shuffled sampler
## 🐛 Bug

The `DistributedSampler` created using `replace_sampler_ddp` is not shuffled. Check the `kwargs` [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/data_loading.py#L195)

### Expected behavior

If training dataloader, create a shuffled `DistributedSampler`, else create a non-shuffled sampler. Even though the `train` flag is passed to the function [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/data_loading.py#L146), it is ignored. 

### Environment

pytorch-lightning master

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

Fixes #2703

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
can we have a test for it? maybe mark it as wip in the meantime

**Comment by rohitgr7** [comment]
@awaelchli need a little help here with the test. Not sure why is it giving this error.
> train_sampler = trainer.train_dataloader.sampler
   AttributeError: 'NoneType' object has no attribute 'sampler'

Can't test it locally.

**Comment by awaelchli** [comment]
Yes, the train_dataloader is None because the test that runs in the main process never sees the trainer state getting updated. When using ddp, the fit and test is running in subprocesses. You can create a callback and put your assertions in e.g. on_train_start and on_test_start methods.

**Comment by rohitgr7** [comment]
Oh! okay. Thanks :)

**Comment by awaelchli** [comment]
@rohitgr7 I drafted it here in the latest commit. Need to wait for CI since I also can't test distributed things locally.

**Comment by rohitgr7** [comment]
Nice! It worked.

**Comment by williamFalcon** [comment]
What happens in the case where the user does not want to shuffle train data?

**Comment by rohitgr7** [comment]
Add this sampler manually and pass `replace_ddp_sampler=False`. Maybe we should mention this thing in docs.

**Comment by williamFalcon** [comment]
yes. Mind updating that?

**Pull request merged**
