### PR TITLE
Fixing a small issue in trainer logging 

### PR DESCRIPTION
**Pull request by guydav**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs? **No changes required**
- [x] Did you write any new necessary tests? **I don't think this requires any new tests, does it?** 
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)? **Should this be on the changelog?**

## What does this PR do?
Fixes half of #1520. This is the simpler half, where the epoch is logged into a dict that isn't passed to the loggers. 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
As much as can be in a one-line fix.

### CODE REVIEW

**Comment by guydav** [comment]
Unsurprisingly, this broke the logging tests, probably since the `epoch` field now appears in the dictionary that arrives in the logger. Can I get approval to change the tests to account for this new field?

**Comment by guydav** [comment]
I added the change to the tests. Let's see that everything passes now.

Two questions: 

1. Do you merge directly to master? Or is there a develop or some other branch that this should be merged into?
2. Is this (the `epoch` field arriving properly to the loggers) a change that should be documented anywhere?

**Comment by williamFalcon** [comment]
1. yes
2. i don't think so right now? maybe if people bring it up but it seems like intuitive default behavior.

**Comment by guydav** [comment]
Okay cool. The only test that's failing is the PyTorch-v1_5 one that timed out. Does that make sense? As far as I'm concerned it's ready to merge, but if there's a way to return this test, that might be even better.

**Comment by Borda** [comment]
@guydav rebased

**Pull request merged**
