### PR TITLE
update readme with conda installation instruction

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?
follow up on #794

### CODE REVIEW

**Comment by Borda** [comment]
well, it not very clear to me how we can push new versions, for pip we have a workflow that builds particular release and pushes to PyPI, but how about condo... @hadim mind bring some light?

**Comment by hadim** [comment]
You can either submit a PR to the feedstock manually. You could also submit this PR using PL CI system at each release.

And the last option (probably the best): at each new pypi release, conda-forge bot will detect it, submit a PR to the PL feedstock and ping you to review it. Then you can just merge if everything is green. Or you can also commit to the PR to add/delete/edit any deps or other things.

**Comment by awaelchli** [comment]
@hadim how do we register it with the conda-forge bot?

**Comment by hadim** [comment]
@awaelchli to get pinged you mean?

The bot already scans all the conda-forge packages for new pypi releases, you have nothing to do. If you want to get notified you need the be added as a maintainer or you can just subscribe to the feedstock repository as for all GH repo: https://github.com/conda-forge/pytorch-lightning-feedstock

**Comment by hadim** [comment]
Here is an example of automatically created PR for another package: https://github.com/conda-forge/blessed-feedstock/pull/4

**Comment by awaelchli** [comment]
great, was not sure if it's already automatic or not. 
then all is fine with me, thanks hadim :)

**Comment by Borda** [comment]
@hadim Thank you!
btw how could we add Description section?
https://anaconda.org/conda-forge/pytorch-lightning

**Comment by hadim** [comment]
You can't. All of this is automatic but I don't a lot of people install packages from this page anyway. If it's really important for you then you would have to contact conda-forge devs.

**Pull request merged**
