### PR TITLE
Replace lightning logo asset

### LINKED ISSUE #4286: Update logo images
## 🚀 Feature
There are currently old logo images here as well as in bolts. Would be fantastic to see new ones.
- pytorch-lightning: https://github.com/PyTorchLightning/pytorch-lightning/tree/8a20d6af51d13adec37593c1356ce08ef380e828/docs/source/_images/logos/
- pytorch-lightning-bolts: https://github.com/PyTorchLightning/pytorch-lightning-bolts/tree/2f3f58045a44ffb32103a3644c2ee2be920a508b/docs/source/_images/logos/

### PR DESCRIPTION
**Pull request by edenlightning**
Fixes #4286

And remove unused assets.

### CODE REVIEW

**Review by teddykoker — APPROVED** [review]

**Comment by edenlightning** [comment]
@teddykoker you are quick!!

**Review by s-rog — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by ydcjeff — APPROVED** [review]

**Review by Borda — COMMENTED** [review]
why are we removing also the other logos?

**Review by Borda — APPROVED** [review]

**Comment by edenlightning** [comment]
Because they arent used anywhere

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
