### PR TITLE
Bugfix for #11618 (leaky save_hyperparams)

### LINKED ISSUE #11618: LightningModule.save_hyperparameters leaks parameters of surrounding classes into model hparams
## 🐛 Bug

If a LightningModule is created within the constructor of another class and that class has a base class, then a call to `save_hyperparameters` will leak the parameters of that constructor into the model's `hparam` dictionary.

### To Reproduce

The following minimal script demonstrates the problem:

```python
from pytorch_lightning import LightningModule

class BaseModule(LightningModule):
    def __init__(self, modelparam_a):
        super().__init__()
        self.save_hyperparameters()

class Module(BaseModule):
    def __init__(self, modelparam_b):
        super().__init__(1)

class BaseUser:
    def __init__(self):
        pass

class User(BaseUser):
    def __init__(self, userparam):
        super().__init__()
        self.mod = Module(2)

u = User(3)
print(u.mod.hparams)
```

### Expected behavior

Expected output would be

```
"modelparam_a": 1
"modelparam_b": 2
```

Actual output is

```
"modelparam_a": 1
"modelparam_b": 2
"userparam":    3
```

### Environment

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 2080 SUPER
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.21.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu111
	- pytorch-lightning: 1.5.9
	- tqdm:              4.62.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         
	- python:            3.9.9
	- version:           SMP Debian 5.15.5-2 (2021-12-18)

### Additional context

The problem is in `pytorch_lightning/utilities/parsing.py` in function `collect_init_args`, which collects local arguments from all frames on the call stack until there is no implicit argument `__class__` in there anymore. In this scenario, `User.__init__` has such an argument because class `User` inherits `BaseUser`, so `collect_init_args` recurses further than it should.

Instead the recursion needs to check whether it's still the same object that's being constructed, but I am unsure if this can be cleanly done. It's not technically enough to check that the `__class__` argument describes a class that inherits `__class__` from the previous stack frame, although this would limit the problem to somewhat unlikely scenarios in which Model B inherits Model A and also has another Model A as a member.

### PR DESCRIPTION
**Pull request by fknauf**
## What does this PR do?

Fixes #11618 and adds a regression test.

### Does your PR introduce any breaking changes? If yes, please list them.

It removes the `inside` parameter from `pytorch_lightning.utilities.parsing.collect_init_args`, which was used to track the state of its recursion and is not necessary in an iterative setup.

The `inside` parameter is not used anywhere else in the code base and is not covered by existing unit tests, and it does not look to me as though `collect_init_args` is meant to be part of the public API, so I figured it was unnecessary to keep it. If desired, the old behavior should be easy enough to emulate, but then I believe new unit tests need to be added for it.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Fun is fun.

### CODE REVIEW

**Comment by fknauf** [comment]
I'm a bit stumped about the test failures. It's failing in `tests/trainer/connectors/test_signal_connector.py::test_signal_handlers_restored_in_teardown`, which doesn't look like it has anything to do with this PR. Moreover, on my local machine the test passes.

**Comment by akihironitta** [comment]
@fknauf Yes, it's an unrelated to the change here and should be fixed in #11635. Would you mind trying merging/rebasing master?

**Comment by fknauf** [comment]
@akihironitta I rebased.

This time there seems to be something wrong with the deployment of the TPU testing container. As far as I can tell from https://app.circleci.com/pipelines/github/PyTorchLightning/pytorch-lightning/51831/workflows/36bd97e4-9de3-4f80-9a44-896c8d783afb/jobs/147245, it's unable to get the pod name from kubectl after the job finished runnning and therefore can't get the test logs. I have no experience with kubernetes, so I don't really know what of make of that.

**Comment by fknauf** [comment]
So how do I proceed here? I think the code is working, and we were just having trouble with the CI.

**Pull request closed without merging**
