### PR TITLE
Support returning None in training_step

### LINKED ISSUE #3491: training_step should allow returning None
## 🐛 Bug

In my dataset, some of the samples are too small and cannot produce valid losses. If all of the samples of a batch are invalid, I need to return None because I do not have a valid loss. Lightning does not seem to allow it.

### To Reproduce

```python
def training_step(self, *args, **kwargs):
    return None
```
In 0.9.0:
```
  File "python3.8/site-packages/pytorch_lightning/trainer/logging.py", line 140, in process_output
    for k, v in output.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

### Expected behavior

Training should not stop and should move on to the next iteration.

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

- Supports returning `None` in `training_step`
- Adds a test

Fixes #3491

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

### CODE REVIEW

**Comment by carmocca** [comment]
Failed tests seem to be unrelated (Horovod)

**Comment by rohitgr7** [comment]
can you add a test that returns outputs for some batches and test that? maybe something like total_batches = 100, returned batches = 50 conditioned on `batch_idx%2 == 0`, or maybe something else??

**Comment by ananthsub** [comment]
I asked this on the #3491 but there was no followup discussion:

> This almost seems like wrapping the train step in a try/catch, and if there's an exception, return None and continue to the next batch. An argument against this is that it could obscure real issues in your training pipeline. For instance, what if there's a bug in your dataloader that causes it to always return empty batches, or if your train_step always throws? Lightning would blindly iterate through the whole dataset instead of failing fast. So this issue seems less like returning None, and how exceptions should be handled in the train_step. Pushing the batching responsibility to the dataloader makes the contract for train_step much clearer. I'd much rather have the trainer fail sooner

Essentially if a user is returning `None`, then they are implicitly signing up for not being able to fail fast. Is that clearly communicated? And is that a tradeoff folks are comfortable with?

**Comment by williamFalcon** [comment]
sorry, this is not something we want to support. 

the real issue is that you need to make sure your dataloader is working as expected and that you skip a batch when it is none.

**Comment by carmocca** [comment]
> Essentially if a user is returning `None`, then they are implicitly signing up for not being able to fail fast. Is that clearly communicated? And is that a tradeoff folks are comfortable with?

Im not sure I understand your point entirely. We are talking about returning None in the `training_step`. This is entirely user-defined. The usual case is returning a `Result` so when a user returns None instead, he is doing it knowingly.

**Comment by williamFalcon** [comment]
in addition... for your particular case, if your batches are too small you should be accumulating gradients to get a non zero val, or increase your batch size

**Comment by williamFalcon** [comment]
ok, per our discussion on slack, let’s enable returning something to signal skip (maybe a string ‘skip’). 

but we cannot enable returning None

**Comment by carmocca** [comment]
To give a concrete example for why I need this:

I am training a model using variable length data (text) with the [CTC loss](https://pytorch.org/docs/master/generated/torch.nn.CTCLoss.html).
The CTC loss produces infinite losses when the model output is too short to be aligned to the targets.
If that happens for a full batch, then I have no loss.
And you cant check at the dataloader level if a batch produced long enough model outputs.

Will update this PR to return a signal. Marking it WIP in the meantime

**Comment by carmocca** [comment]
@williamFalcon Can you reopen, please?

**Pull request closed without merging**
