### PR TITLE
replace pyright by mypy

### LINKED ISSUE #4698: Type annotations and mypy
## 🚀 Feature

Introduce [mypy](https://github.com/python/mypy) in pre-commit pipeline

### Motivation
Static type checking is an interesting and powerful technique to assure high code quality and standard. I believe it should be unvaluable to start introducing type annotation and add `mypy` among pre-commit hooks

### Pitch
I want to check the correctness of types annotation with a static type checking. When I commit, the checker should verify and eventually notify the contributer to check his code

### Additional context

I ran `mypy` onto tests and it heighights some deprecated calls (such as `checkpoint_callback`, now in `callbacks` list). These checks could be useful to static check tests and find avoid obsolescent tests

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

replacing pyright by mypy

Resolves #4698

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:  

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by justusschock — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by ydcjeff — APPROVED** [review]
Shall we combine all code style checking (flake, isort, mypy) in one workflow?
Since they are all running in one step, it's better to combine them in a workflow.
It would be in another PR ofc.

**Review by SeanNaren — APPROVED** [review]

**Comment by edenlightning** [comment]
@ydcjeff great idea! Mind sending a PR?

**Comment by Borda** [comment]
> Shall we combine all code style checking (flake, isort, mypy) in one workflow?
> Since they are all running in one step, it's better to combine them in a workflow.
> It would be in another PR ofc.

I do not agree here, it is easier to see what fail if they are separate and they do not take almost any time...

**Review by akihironitta — APPROVED** [review]

**Pull request merged**
