### PR TITLE
tests for pytorch 1.5

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
https://github.com/pytorch/pytorch/releases/tag/v1.5.0

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
cPickle shall be fixed in #1478 but not tested...

**Comment by Borda** [comment]
just tested and the PR above fixes it... see https://app.circleci.com/jobs/github/PyTorchLightning/pytorch-lightning/20351

**Comment by williamFalcon** [comment]
@Borda ok, unblocked

**Comment by Borda** [comment]
the actual error is described here https://github.com/pytorch/pytorch/issues/32186

**Pull request merged**
