### PR TITLE
fixing some compatibility with PT 1.8

### LINKED ISSUE #5850: failing Profiler with PT 1.8
## 🐛 Bug

https://github.com/PyTorchLightning/pytorch-lightning/pull/5840#issuecomment-774421318

## Please reproduce using the BoringModel

there is some incompatibility, to be fixed in other PR

FAILED tests/metrics/test_composition.py::test_metrics_mod[2.0-expected_result2]
FAILED tests/models/test_horovod.py::test_result_reduce_horovod - RuntimeErro...
FAILED tests/trainer/test_trainer.py::test_pytorch_profiler_describe - Assert...
FAILED tests/trainer/test_trainer.py::test_pytorch_profiler_value_errors - As...
FAILED tests/trainer/test_trainer.py::test_pytorch_profiler_nested - Assertio...

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

addressing problems, fixes #5850

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@tgaddair mind bring light on why the process is failing on PT 1.8
```
[0]<stderr>:TypeError: must be real number, not NoneType
[1]<stderr>:    trainer.fit(model)
[1]<stderr>:  File "/__w/pytorch-lightning/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 504, in fit
[1]<stderr>:    self.accelerator_backend.setup(model)
[1]<stderr>:  File "/__w/pytorch-lightning/pytorch-lightning/pytorch_lightning/accelerators/legacy/horovod_accelerator.py", line 78, in setup
[1]<stderr>:    hvd.broadcast_optimizer_state(optimizer, root_rank=0)
[1]<stderr>:  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/horovod/torch/functions.py", line 172, in broadcast_optimizer_state
[1]<stderr>:    p = torch.Tensor([p])
```

**Comment by tgaddair** [comment]
Hey @Borda, this was a change in PyTorch's API which we updated Horovod for in https://github.com/horovod/horovod/pull/2624.  We can release a patch tomorrow to unblock this.

**Comment by Borda** [comment]
> Hey @Borda, this was a change in PyTorch's API which we updated Horovod for in [horovod/horovod#2624](https://github.com/horovod/horovod/pull/2624). We can release a patch tomorrow to unblock this.

That would be great! Thx for your swift action/reaction

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by Borda** [comment]
ok, just waiting on the new Horovod release, then we are ready to go...

**Review by justusschock — APPROVED** [review]

**Comment by Borda** [comment]
for the record, Horovod 0.21.2 has the fix for PT 1.8 compatibility

**Review by awaelchli — APPROVED** [review]

**Pull request merged**
