### PR TITLE
CI: unique docs artefact name

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

A tiny improvement in the filename of an artifact generated from CI `make-docs`.

Before the change:
```
docs-results-Linux-...-.zip
```
After the change:
```
 docs-results-d83369d51b256afb98ef5f6a4559127225db67ac.zip
```
so you do not have collisions with already downloaded docs...
as suggested by @akihironitta in https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/478

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes [if needed]?
- [ ] Did you write any new necessary tests [no need for typos, docs]? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:  

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone are aligned!**
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by carmocca — APPROVED** [review]
Is this job run only on one machine? If so, LGTM

**Comment by Borda** [comment]
> Is this job run only on one machine? If so, LGTM

yes, it running only once

**Review by ydcjeff — APPROVED** [review]

**Review by akihironitta — APPROVED** [review]
Thanks for applying it to PL.

**Review by rohitgr7 — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by s-rog — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
Great catch !

**Pull request merged**
