### PR TITLE
Update test_pruning.py to use `devices` instead of `gpus` or `ipus`

### PR DESCRIPTION
**Pull request by mathemusician**
## What does this PR do?

Update test to deprecate `num_processes`, `gpus`, `tpu_cores`, and `ipus` from the Trainer constructor

Part of [Pull 11040](https://github.com/PyTorchLightning/pytorch-lightning/pull/11040).

🌳 [Trello Board Link](https://trello.com/b/He49BfCc/pl-tests)

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by daniellepintz — APPROVED** [review]

**Comment by four4fish** [comment]
LGTM! But could we keep some of the tests for gpus, ipus, num_processes (and update the tests with with `pytest.deprecated_call(match=X..)`) in the future changes? These flags are still heavily used, we want to have enough coverage until we remove them cc @daniellepintz.

**Review by carmocca — APPROVED** [review]

**Comment by daniellepintz** [comment]
@four4fish I suggest we keep some of the tests (add `pytest.deprecated_call(match=X..)`) that are testing the actual parameter combinations, namely the tests in `test_accelerator_connector.py`. I don't think it's sustainable or necessary to keep tests across different files unless they are testing the functionality of the parameters themselves. Furthermore, I think we would have to put all of the `pytest.deprecated_call(match=X..)` changes in #11040 otherwise the tests would fail, so #11040 would become a giant PR.

**Comment by mathemusician** [comment]
@four4fish How do you suggest we keep some of the tests for gpus, ipus, and num_processes while preparing for v2.0?

**Comment by four4fish** [comment]
> @four4fish I suggest we keep some of the tests (add `pytest.deprecated_call(match=X..)`) that are testing the actual parameter combinations, namely the tests in `test_accelerator_connector.py`. I don't think it's sustainable or necessary to keep tests across different files unless they are testing the functionality of the parameters themselves. Furthermore, I think we would have to put all of the `pytest.deprecated_call(match=X..)` changes in #11040 otherwise the tests would fail, so #11040 would become a giant PR.

yeah, I was thinking kept few tests as-is, when #11040 PR out include the few left over ones with pytest.deprecated_call(..). But make sense, having accelerator_connector tests and some test_tpu.py, test_gpu.py will be enough. (accelerator_connector_test doesn't have enough coverage, some tests in test_Xpus are needed too)

**Comment by four4fish** [comment]
> @four4fish How do you suggest we keep some of the tests for gpus, ipus, and num_processes while preparing for v2.0?

yeah, details in the discussion with @daniellepintz above. For the current 3 PRs I think we are good :) thanks!

**Comment by mathemusician** [comment]
> > @four4fish How do you suggest we keep some of the tests for gpus, ipus, and num_processes while preparing for v2.0?
> 
> yeah, details in the discussion with @daniellepintz above. For the current 3 PRs I think we are good :) thanks!

@four4fish @daniellepintz Sounds great! I'll get right to it

**Comment by daniellepintz** [comment]
Sounds good. @mathemusician it would be helpful if as you are going through the tests, for the tests @four4fish  mentioned above, no need to update them and instead if you could leave a TODO for those for me to add `pytest.deprecated_call` in #11040. those tests would be any that deal with configuration of parameters, including some in test_accelerator_connector, test_gpu, and test_tpu

**Review by akihironitta — APPROVED** [review]

**Pull request merged**
