### PR TITLE
codecov can't parse GPU/TPU coverage - temporary skip until that is fixed on their end

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

skip some files that we cannot search for coverage

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@tgaddair we have some problems with installing Horovod with PT 1.6, mind have look?

**Comment by tgaddair** [comment]
@Borda is this just the Reinstall Horovod thing again?  Can you try changing the line with `HOROVOD_BUILT` as we discussed in a different PR:

```
HOROVOD_BUILT=$(python -c "import horovod.torch; horovod.torch.nccl_built(); print('SUCCESS')" || true)
```

**Comment by Borda** [comment]
> @Borda is this just the Reinstall Horovod thing again? Can you try changing the line with `HOROVOD_BUILT` as we discussed in a different PR:
> 
> ```
> HOROVOD_BUILT=$(python -c "import horovod.torch; horovod.torch.nccl_built(); print('SUCCESS')" || true)
> ```

ok, we have changed it fo conda, didn't know it is also needed for pip...

**Comment by tgaddair** [comment]
Ah, yeah didn't see that.  Yes, looks like we need it for both, based on these logs.

**Comment by Borda** [comment]
this is quite strange that TPU has almost no coverage even with the index it called directly without subprocesses

**Comment by williamFalcon** [comment]
is this a PR for spawn or ddp?

**Comment by Borda** [comment]
> is this a PR for spawn or ddp?

spawn for this moment, DDP in next step...

**Comment by williamFalcon** [comment]
?
spawn is tested...  with coverage. ddp is the only one that isn’t

**Comment by Borda** [comment]
> spawn is tested... with coverage. ddp is the only one that isn’t?

this is executed in spawn, right?
https://github.com/PyTorchLightning/pytorch-lightning/blob/8ab5bcda3d040fbe6fd616ff45793e3dfd1061ce/pytorch_lightning/accelerator_backends/tpu_backend.py#L99

**Comment by Borda** [comment]
lets do just skip for files we cannot simply search and find propper way later...

**Pull request merged**
