### PR TITLE
Added PYSYFT_AVAILABLE flag to optimizer step closure

### PR DESCRIPTION
**Pull request by madhavajay**
## What does this PR do?
Allows the Duet Lightning notebook to run.

Fixes # (issue) <- this [links related issue to this PR](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@madhavajay @tchaton just curious what os the branch for `openmined_v0` and shall it be rather based/updated with 1.2 instead of master...

**Comment by tchaton** [comment]
> @madhavajay @tchaton just curious what os the branch for `openmined_v0` and shall it be rather based/updated with 1.2 instead of master...

Hey @Borda, branch for `openmined_v0` was my first attempt at integrating PySyft. I will close it and use this one to push any integration progress.

Best,
T.C

**Comment by Borda** [comment]
@madhavajay I have tried to resolve conflict just to try that mergify is working, mind check if I did it also correctly?

**Comment by madhavajay** [comment]
@tchaton @Borda ill get @tcebere to create a PR so then he can push to it.

**Comment by Borda** [comment]
> @tchaton @Borda ill get @tcebere to create a PR so then he can push to it.

not sure what you mean, but I leave it to @tchaton :]

**Comment by Borda** [comment]
any update here? :]

**Comment by madhavajay** [comment]
@tudorcebere Is this still required or can we close it?

**Comment by madhavajay** [comment]
This has been resolved elsewhere.

**Pull request closed without merging**
