### PR TITLE
Fix outdated docs

### PR DESCRIPTION
**Pull request by skmatz**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?

Fix outdated docs: `save_best_only` was changed to `save_top_k` (#128).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
If I do a full text search in the whole project, I also find it in the following files:
```
docs/source/weights_loading.rst
pytorch_lightning/trainer/__init__.py
pytorch_lightning/trainer/training_io.py (you updated)
```

**Comment by Borda** [comment]
We shall a bit more unify docs and use rather cross-refs if possible

**Comment by awaelchli** [comment]
I still think it should be updated everywhere where it is outdated.

**Comment by Borda** [comment]
@awaelchli mind draft follow-up PR?

**Pull request merged**
