### PR TITLE
CI: Docs build preview in each PR

### PR DESCRIPTION
**Pull request by awaelchli**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?
It works!
This allows us to preview the docs in every PR and make documentation updates easier to review as it does not require to pull the branch and build locally. The html pages are automatically stored in CircleCI. 

**1. Click on the details button for the **Build Docs** task:**
image

**2. In CircleCi, click on the Artifacts tab:**
docs-preview

**3. Click on index.html to get to the home page!**

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
@Borda It works! 
Should I add a note to the contributing.md how to access it?

**Comment by Borda** [comment]
> Should I add a note to the contributing.md how to access it?

yes :] well thinking about making a page about for tests and docs in Wiki...

**Comment by awaelchli** [comment]
That would also be cool!

**Comment by Borda** [comment]
> That would also be cool!

may you draft it here or another way in MD format and I will copy-paste it to wiki... :]

**Pull request merged**
