### PR TITLE
Add E231 ignore to flake8 checs, conflicts with black

### PR DESCRIPTION
**Pull request by kumuji**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Fixes [problem with pep8speaks](https://github.com/PyTorchLightning/pytorch-lightning/pull/1967#issuecomment-640133151)

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
I don't understand this change. If one does not use black, this ignores the whitespace rules. Pretty sure this is undesired? With my comment in the other PR I did not mean to say we should ignore the rule simply because I saw a warning. It is likely a bug with black itself.

**Comment by Borda** [comment]
just thinking what about dictionary `{'any-key': 123}`

**Comment by Borda** [comment]
@kumuji mind check is something similar was reported in Black already - that PEP speaks complain about black patterns?

**Comment by kumuji** [comment]
> just thinking what about dictionary `{'any-key': 123}`
> 
> @kumuji mind check is something similar was reported in Black already - that PEP speaks complain about black patterns?

I haven't seen anything like it in black repo, not sure if it is a bug though. It just appears not frequently.

**Comment by Borda** [comment]
hey, any update here? :raccoon:

**Comment by kumuji** [comment]
> hey, any update here? raccoon

Seems like this error rarely appears, probably it is not necessary.

**Comment by Borda** [comment]
just looking around and found https://github.com/psf/black/issues/1289 https://github.com/psf/black/issues/429
and according to PEP8 black is wrong with this particular formating... https://www.python.org/dev/peps/pep-0008/#pet-peeves
Let's stick with PEP8 and if/when black deals with it, we'll upgrade it... :rabbit:

**Pull request closed without merging**
