### PR TITLE
[docs] Fix ModelCheckpoint examples

### PR DESCRIPTION
**Pull request by ydcjeff**
## What does this PR do?

Fix ModelCheckpoint Examples

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.    
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by rohitgr7** [comment]
@Borda removed them for some reason [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/4213#discussion_r510380694). What's the difference btw?

**Comment by ydcjeff** [comment]
> @Borda removed them for some reason [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/4213#discussion_r510380694). What's the difference btw?

Examples are showing correctly
https://67411-178626720-gh.circle-artifacts.com/0/html/generated/pytorch_lightning.callbacks.ModelCheckpoint.html#pytorch_lightning.callbacks.ModelCheckpoint

**Comment by rohitgr7** [comment]
oh okay. Thanks @ydcjeff. I should always have a look at docs before merging any changes.

**Review by rohitgr7 — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Comment by justusschock** [comment]
@ydcjeff any idea about failing tests?

**Comment by ydcjeff** [comment]
> @ydcjeff any idea about failing tests?

@justusschock because those are tested with 1.7, a PR is on the way #3821

**Pull request merged**
