### PR TITLE
Reuse `_TORCHVISION_AVAILABLE` in examples

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

We are defining `_TORCHVISION_AVAILABLE` twice

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [n/a] Did you make sure to update the documentation with your changes? (if necessary)
- [n/a] Did you write any new necessary tests? (not for typos and docs)
- [n/a] Did you verify new and existing tests pass locally with your changes?
- [n/a] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Review by Borda — COMMENTED** [review]
I would probably in the init just import from Pl and later in all examples hold import to this imported var

**Review by ananthsub — COMMENTED** [review]
are the only usages of torchvision under `pl_examples` ?  if so, should we move torchvision to be an extra requirement to simplify the core lightning dependencies?

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
>  if so, should we move torchvision to be an extra requirement to simplify the core lightning dependencies?

torchvision is not in the core dependencies
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/requirements.txt

**Comment by carmocca** [comment]
> I would probably in the init just import from Pl and later in all examples hold import to this imported var

In that case we would just be avoiding one single function call. If you prefer it that way to having it defined in a single place, we can close this PR

**Review by tchaton — APPROVED** [review]
Nice cleaning !

**Review by ethanwharris — APPROVED** [review]

**Pull request merged**
