### PR TITLE
Revert accidental change merged with PR #3433

### LINKED ISSUE #3406: Models defined by data
Is this correct (https://pytorch-lightning.readthedocs.io/_/downloads/en/latest/pdf/ pg17)

The first code example shows `prepare_data()` and `setup()` being called on the dataloader, but then it is not passed to `fit()`?

The second box has no explanation - I assume it's an alternative to the first code example?

image

### PR DESCRIPTION
**Pull request by david-waterworth**
## What does this PR do?

As requested by @Borda PR https://github.com/PyTorchLightning/pytorch-lightning/pull/3433 included an accidental change of docs/source/introduction_guide.rst line 300 `.. testcode::` was changed to `.. code-block:: python`. This PR reverts this change.

.. testcode::
.. code-block:: python

Fixes: #3406

### CODE REVIEW

**Comment by awaelchli** [comment]
> Rolls back accidentally change from testcode:: to code-block:: python in #3433 

could you update the description? This PR seems to be about something else, I don't know what. A better title might also help :)

**Comment by david-waterworth** [comment]
Apologies not sure how that happened - looks like GitHub auto-filled the title from an old PR I submitted and I forgot to amend it. I've updated the description.

**Comment by awaelchli** [comment]
@david-waterworth I don't see any reverted changes. As per your description, you need to change the code block directive to `.. testcode`, correct?

**Comment by david-waterworth** [comment]
Yes I guess something got messed up when I created the pull request. I'll fix it tomorrow

**Comment by david-waterworth** [comment]
@awaelchli it looks ok to me - if you click on `commits` then the final (3rd one) line 300 is back to `.. testcode::`, but for some reason `files changed` isn't showing the correct diff.

I think this is because the original PR for this branch has been merged. I modified my branch with commit #3 and created this PR. So the files change diff is from before the 3 commits even though 2 have been merged

**Comment by rohitgr7** [comment]
@david-alexander-white rebased with master. It's good now.

**Review by rohitgr7 — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
