### PR TITLE
fix Travis build

### PR DESCRIPTION
**Pull request by smallzzy**
This pr is trying to fix the ci on master.

### CODE REVIEW

**Comment by Borda** [comment]
What is the purpose of this PR?

**Comment by smallzzy** [comment]
testing ci. Do not mind me.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Borda** [comment]
For testing, pls use your Travis, there you can run tests on your fork... Thx

**Comment by smallzzy** [comment]
You do realize that this commit do improve ci status on master right? LOL

**Comment by Borda** [comment]
that what I was asking what is this about since PR description is empty...

**Comment by Borda** [comment]
https://travis-ci.community/t/failing-build-with-python-errorimporterror/7188

**Comment by smallzzy** [comment]
the sudo pip is using python 2. I am not sure if this is fully intentional.

**Comment by Borda** [comment]
it helps for Linux but still failing on osx...

**Comment by smallzzy** [comment]
https://travis-ci.org/smallzzy/pytorch-lightning/jobs/649313266
it turns out that we are getting completely different python

**Comment by Borda** [comment]
Working with Travis recintly is not very pleasant since they are changing their images on the fly...

**Comment by Borda** [comment]
I would drop Travis and move to GH action #823

**Comment by smallzzy** [comment]
My current theory is the following: 
* the unix build use system virtualenv. So fixing pip ends up fixing the ci
* the mac build will install virtualenv.
https://github.com/tox-dev/tox/issues/1516 points out that virtualenv==20 breaks tox.
So, I think going for a old virtualenv will fix mac build.

**Comment by Borda** [comment]
@williamFalcon ^^

**Comment by williamFalcon** [comment]
@smallzzy thanks!

**Pull request merged**
