### PR TITLE
Weekly Patch Release v1.5.3

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do? 

Contains all bugfixes to be released next week. As bugfixes get merged to master, they will get cherry-picked into this branch by the individual author (core) or on-caller.

For staff/core: The new [release guide is here](https://www.notion.so/gridai/Release-Guide-ab132bf94f304056afc8ff992304c18f).

```
gh pr list -s merged -S 'merged:2021-11-16T18:30:00.000Z..2021-11-23T18:30:00.000Z' --json mergedAt,milestone,url,mergeCommit,title --jq 'sort_by(.mergedAt) | reverse | .[] | select((.milestone.title == 
"1.5.x") or (.milestone.title == null)) | [.mergedAt, .url, .mergeCommit.oid, .title] | join(" ")' --limit 100

``` 

```
2021-11-22T15:58:22Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10631 a6dedcf492456c1ef4e29b084b2b970f79667f17 Fix `move_metrics_to_cpu` with evaluation
2021-11-22T14:52:22Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10671 48cb38ac5dd0159c8f7c5189c888dfd04a2ed34b Fix docs filterwarnings snippet
2021-11-22T11:19:46Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10665 eb13e1df89b70af0e90e3f1e9c4f94bff6728aee update bug_report model links and notebook
2021-11-19T17:34:24Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10621 a18b6409d13ded0e12752a9649bdb8dc763d4cbb Check torch.distributed availability before sharded tensor state dict hook registration
2021-11-19T16:48:27Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10408 ec27313be242b4131354490e9dbed365ed7b9be9 Fix an issue that caused Lightning to extract the batch size even though it was set by the user in `LightningModule.log`
2021-11-19T15:16:33Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10076 e83e8ae3058fced32f0903f4d6822a8d5e21b928 Respect the passed dtype with `self.log`
2021-11-19T14:04:33Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10613 94390aba56c0e9632ab9421640695955f0707490 Lite: Don't pop value if they don't exist
2021-11-19T05:59:57Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10497 137b62d80df9896ccce63bf607a29cfdbf1f06f0 Add `refresh_rate` to RichProgressBar
2021-11-19T03:13:36Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10610 7d3ad5b76eebe1333a89a51a72b77ec198d86489 Don't register signal in thread
2021-11-18T17:29:14Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10522 6b728713bb3b35ad58cd0085acaa443b33ab03ac log metrics for correct dataloader only
2021-11-17T22:29:49Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10591 c15b84dae7c1051d76c39dc3037e0eb5f016edc3 Simplify hanging queue test
2021-11-16T19:16:01Z https://github.com/PyTorchLightning/pytorch-lightning/pull/10468 0865ad1d66e903d0c89aafa4f6f2a6651f840a18 Weekly Patch Release v1.5.2


```

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
I made sure I had fun coding 🙃

Part of #1 (it's a lie, this is just here to avoid noisy GitHub bot)

### CODE REVIEW

**Comment by rohitgr7** [comment]
@awaelchli should https://github.com/PyTorchLightning/pytorch-lightning/pull/10626 be added here? since on that PR, milestone is set to 1.6.

**Comment by awaelchli** [comment]
@rohitgr7 yes, because it helped with CI hanging and wanted to make sure it gets included here too.

**Comment by awaelchli** [comment]
@rohitgr7 #10406 was added by mistake?

**Comment by rohitgr7** [comment]
> @rohitgr7 #10406 was added by mistake?

@awaelchli yeah! sorry. I added it to my list of commits at first and forgot to remove it. 😅

**Comment by tchaton** [comment]
@awaelchli Any updates here ?

**Comment by awaelchli** [comment]
Waiting for @carmocca to confirm which CI related commits to cherry pick from master

**Review by rohitgr7 — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
