### PR TITLE
Remove unused `beta` argument in precision/recall in docstring

### PR DESCRIPTION
**Pull request by ydcjeff**
## What does this PR do?

Remove unused `beta` argument in precision/recall in docstring

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by rohitgr7** [comment]
some changes are made to Precision/recall here. https://github.com/PyTorchLightning/pytorch-lightning/pull/4842
can you check if it's still required? @ydcjeff

**Comment by Borda** [comment]
> some changes are made to Precision/recall here. #4842
> can you check if it's still required? @ydcjeff

the main diff is that this goes to master as bug-fix, the other is for 1.2

**Review by rohitgr7 — APPROVED** [review]

**Comment by ydcjeff** [comment]
> some changes are made to Precision/recall here. https://github.com/PyTorchLightning/pytorch-lightning/pull/4842
> can you check if it's still required? @ydcjeff 

Yes, it has been removed from docstring in that. It can be said this can be closed.

**Review by SkafteNicki — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Review by caleb603 — COMMENTED** [review]
Good stuff

**Pull request merged**
