### PR TITLE
Weekly Patch Release v1.4.9 [full merge, no squash]

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

```fish
gh pr list -s merged -S 'merged:2021-09-21T18:30:00.000Z..2021-09-29T18:30:00.000Z' --json mergedAt,milestone,url,mergeCommit,title --jq 'sort_by(.mergedAt) | reverse | .[] | select((.milestone.title == "v1.4.x") or (.milestone.title == null)) | [.mergedAt, .url, .mergeCommit.oid, .title] | join(" ")' --limit 100
```

```fish
2021-09-27T19:36:57Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9715 131176b9f5e544a1133240a46dca1960308b7849 [bugfix] Prevent on_before_batch_transfer to be called twice
2021-09-27T16:16:46Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9717 64bbebc8694b90df2343185e702ca4d873aa8669 [bugfix] Resolve metrics not being properly resetted on validation epoch end
2021-09-27T13:33:27Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9606 a69b940ce3894c08cc4b033f4fee63a838a6e8ca [Bugfix] Fix location of `unscale` in mixed precision plugin
2021-09-26T19:20:43Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9704 83d83abc9dcb96a09e5eeda57daa2e83afed8731 Fix `lr_find` to generate same results on multiple calls
2021-09-25T16:02:26Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9595 a4bc0acb02b729218c9aba83a211c5f8405b5e16 Update warnings in `TrainingTricksConnector`
2021-09-23T08:20:25Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9410 86dd318dccb593fe1a65f196cceef377d2808eed Reset metrics before each task starts

```

Skipped:
```
2021-09-24T18:51:55Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9652 8fcdcb598bbf0fbe6cda92415d1d69eb1e2d0aa0 Fix `accumulate_grad_batches` on init

2021-09-27T15:55:20Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9696 faee9dfd532c96684445047c3dad6424feee1c02 Make `HorovodPlugin.all_gather` return a tensor

2021-09-25T05:53:32Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9664 b3a5c7f44217c945c296479d6918ab68dd0f588e Add `enable_progress_bar` to Trainer constructor

2021-09-24T08:27:16Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9679 c2e3ec164aea692f5a944b4f2d1782a2f363605c Add torch v1.11.0 to the list of versions in adjust_versions.py

2021-09-23T08:58:04Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9616 491e4a2a6cebc39f271346bb797795ff99dad0da Deprecate `progress_bar_refresh_rate` from Trainer constructor

2021-09-22T19:14:24Z https://github.com/PyTorchLightning/pytorch-lightning/pull/9649 37469cd3e85bd203cf32d8f888edbc713a7bce09 fix modify _DDPSinkBackward view inplace error for pytorch nightly 1.10

```

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
I made sure I had fun coding 🙃

### CODE REVIEW

**Review by kaushikb11 — APPROVED** [review]

**Review by rohitgr7 — APPROVED** [review]

**Comment by awaelchli** [comment]
I'm seeing a special test fail:
[tests/plugins/test_deepspeed_plugin.py::test_deepspeed_multigpu_stage_2_accumulated_grad_batches](https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=35155&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=d9f671c5-a304-5675-5394-961fd7f98b9b)

It's failing from this cherry picked PR #9652 but no changes directly related to deepspeed. Is it possible we would need  #8856 too as a base for this?

**Review by SeanNaren — APPROVED** [review]

**Comment by carmocca** [comment]
> Is it possible we would need #8856 too as a base for this?

Yes but I'm not sure if including #8556 will be easier than adapting #9652 to the old code.

I'd say dropping #9652 is also an option as it is described as "a small fix" with no linked issue.

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by awaelchli** [comment]
@carmocca thanks, yes, it appears so. I dropped the commit, don't see another way.

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
