### PR TITLE
Remove unnecessary intermediate layers in base-conda Dockerfile

### PR DESCRIPTION
**Pull request by sumanthratna**
## What does this PR do?

before this PR, the base-conda Dockerfile created 12 unnecessary intermediate layers (mostly from ENVs). If you all decide to merge this PR, I can create PRs for the other Dockerfiles (or I can fix the other Dockerfiles in this PR).

Please let me know if this is worth updating the changelog! 

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — DISMISSED** [review]
cool, mind do it also for other Docker files within this PR?

**Comment by Borda** [comment]
seems that all docker builds are failing now... :/

**Comment by sumanthratna** [comment]
> seems that all docker builds are failing now... :/

@Borda it should be better now!

**Review by Borda — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Review by rohitgr7 — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Comment by rohitgr7** [comment]
I wonder why isn't it merged automatically.

**Comment by Borda** [comment]
> I wonder why isn't it merged automatically.

o tel you now when it is merged :P

**Pull request merged**
