### PR TITLE
Let Accelerator inherit from ABC to make sure abstractmethod takes effect

### PR DESCRIPTION
**Pull request by chunyang-wen**
## What does this PR do?

+ We have to inherit from `ABC` in order to make `abstractmethod` to take effect. Make `Accelerator` inherit from `ABC`
+ Update docstring to better describe the function

### CODE REVIEW

**Comment by chunyang-wen** [comment]
The failed test case means that `ABC` takes effect.

**Review by carmocca — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Review by ananthsub — COMMENTED** [review]
thanks for working on this @chunyang-wen . Could you add an entry to the CHANGELOG since this may be a breaking change for people who write customized accelerator classes and who hadn't implemented the abstract methods?

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by akihironitta — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
Thank you for the quick fix @chunyang-wen <3

**Pull request merged**
