### PR TITLE
fix incomplete progress bar when refresh_rate > num batches

### LINKED ISSUE #4565: progress bar refresh_rate prevents old bars being cleared
If you set refresh_rate=100 then the sanity check and validation bars continue being displayed forever even though leave=False. Also the validation bars only show part complete.

I note also that the mininterval parameter for tqdm bars is ignored.

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Fixes #4565

Fixes edge cases with num batches not being divisibale by refresh rate, leading to an incomplete the progress bar. 
Tests here fail on master.

**Example:**

train_batches: 5, refresh_rate: 3

(master)
Epoch 0:  60%|██████    | 3/5 [00:00<00:00, 111.11it/s, loss=0.131]

(this branch)
Epoch 0: 100%|██████████| 5/5 [00:00<00:00, 125.00it/s, loss=0.124]

### CODE REVIEW

**Comment by awaelchli** [comment]
this bugfix is a visual fix, I need to figure out how to write the unit test. somehow counting the number of times update is called.

**Comment by SkafteNicki** [comment]
@awaelchli would it be idea for testing to subclass `ProgressBar` and then decorate the `update` method? Something like:
``` python
class MyProgressBar(ProgressBar):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._update_counter = 0

    def init_train_tqdm(self):
        bar = super().init_train_tqdm()
        bar.update = self.counter_wrap(bar.update)
        return bar

    def counter_wrap(self, update):
        def wrap(*args, **kwargs):
            self._update_counter += 1
            return update(*args, **kwargs)
        return wrap

```

**Review by justusschock — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]
LGTM

**Review by rohitgr7 — APPROVED** [review]

**Comment by ananyahjha93** [comment]
@awaelchli can you resolve the conflict?

**Review by zech564 — APPROVED** [review]

**Comment by awaelchli** [comment]
@ananyahjha93 resolved, thanks!

**Pull request merged**
