### PR TITLE
Fix pre-commit isort failure on tests/utilities/*.py

### PR DESCRIPTION
**Pull request by arnaudgelas**
## What does this PR do?

Relates to #4805

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by akihironitta — COMMENTED** [review]
Can you unlist this submodule from `pyproject.toml` to enable isort check on this submodule? Can you also update all your PRs regarding this?

**Comment by tchaton** [comment]
Hey @arnaudgelas,

Would be better to make 1 PR with isort resolving. It is saturating the ci :)

Best regards,
T.C

**Comment by arnaudgelas** [comment]
Hi @tchaton,
I tried earlier to submit all pre-commit isort fixes into a single PR here (note that the content,of this PR is incorrect), and I was told to split it into smaller one, see https://github.com/PyTorchLightning/pytorch-lightning/pull/5396#issuecomment-755984043

So  @Borda @tchaton should I make a single PR with all pre-commit isort fixes? or continue like this?

**Comment by arnaudgelas** [comment]
@akihironitta I could add a commit before that one which would modify pyproject.toml to make sure it fails first and that this commit actually fixes the test. I shall wait for the decision in between a single big PR or multiple ones...

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
> Would be better to make 1 PR with isort resolving. It is saturating the ci :)

@tchaton the suggestions came from us as @williamFalcon was against to have larger refactoring in single even it is automated one (since it does not come from the core, we have to read it if there is no accidental miss-chnage)

**Comment by akihironitta** [comment]
> Can you unlist this submodule from pyproject.toml to enable isort check on this submodule? Can you also update all your PRs regarding this?

@arnaudgelas Could you follow @Borda's comment? Also, would you mind updating all your PRs to enable isort check on each submodule by unlisting each one from `pyproject.toml`?

**Review by justusschock — APPROVED** [review]

**Comment by arnaudgelas** [comment]
@akihironitta Done!

**Review by SkafteNicki — APPROVED** [review]

**Review by tchaton — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Pull request merged**
