### PR TITLE
Parse help in DataModule.add_argparse_args

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
## What does this PR do?

It implements a missing behavior from `add_argparse_args` that is present in `Trainer` not in `LightningDataModule`, namely the ability of parsing the docstring of the class to infer how to populate the help string for an argument.

NB: The project's PR submission requirements are bit over the time I'm willing to invest, so forgive me for not complying with it. I understand this might result in the PR getting immediately closed but at least you're aware that the changes I present here, address the issue described.

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by carmocca** [comment]
Hi! Thanks for your PR!

This is duplicated code (which we forgot about!). So the correct fix should to do the same as in the `Trainer`

https://github.com/PyTorchLightning/pytorch-lightning/blob/2008d77f283e4ed1d916340dd47cfa85fe73f822/pytorch_lightning/trainer/properties.py#L30-L32

https://github.com/PyTorchLightning/pytorch-lightning/blob/2008d77f283e4ed1d916340dd47cfa85fe73f822/pytorch_lightning/trainer/properties.py#L152-L154

https://github.com/PyTorchLightning/pytorch-lightning/blob/2008d77f283e4ed1d916340dd47cfa85fe73f822/pytorch_lightning/trainer/properties.py#L164-L166

So, doing the same for the `DataModule`

**Comment by SergioRAgostinho** [comment]
A better solution indeed. I'll patch it.

**Comment by Borda** [comment]
pls set the target 1.2 as there won't be any releases in 1.1 cc: @tchaton; see [our suggestions](https://pytorch-lightning.readthedocs.io/en/latest/CONTRIBUTING.html#how-to-fix-pr-with-mixed-base-and-target-branches)

**Comment by Borda** [comment]
@SergioRAgostinho thank you for sending your PR, just a minor issue coming from our side... we have swapped branches regarding upcoming feat 1.2, mind rebase on actual `master`? if needed see [How to fix PR with mixed base and target branches?](https://pytorch-lightning.readthedocs.io/en/latest/generated/CONTRIBUTING.html#how-to-fix-pr-with-mixed-base-and-target-branches)

**Comment by carmocca** [comment]
Closing as it will be fixed by #6088

**Pull request closed without merging**
