### PR TITLE
[placeholder] clean imports in PL

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

TODO: pull actual master and use pyCharm to clean imports - automatic tool
clean unused imports in PL

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
is this isort?

**Comment by Borda** [comment]
> is this isort?

no, pycharm... :]

**Comment by rohitgr7** [comment]
maybe merge this just before release with a rebase?? just to keep it clean and consistent with other PRs.

**Comment by Borda** [comment]
> maybe merge this just before release with a rebase?? just to keep it clean and consistent with other PRs.

good point, jut not to forget.. as well as #3776 and #3131

**Comment by ananthsub** [comment]
Can this run as a pre-commit hook? Does it already?

**Comment by rohitgr7** [comment]
@Borda I suggest to close this one and open a new one, do an `isort` or `pycharm` and create a new one before release. Would be easier than rebase I think. Same with the other one.

**Comment by Borda** [comment]
> @Borda I suggest to close this one and open a new one, do an `isort` or `pycharm` and create a new one before release. Would be easier than rebase I think. Same with the other one.

not really as I said it was a placeholder so I would do it always from the actual master...

**Pull request closed without merging**
