### PR TITLE
[WIP] Dice coefficient class metric and unification

### PR DESCRIPTION
**Pull request by teddykoker**
* Add `DiceCoefficient` class
* unify dice coefficient functional metric to use the same code

### CODE REVIEW

**Comment by tadejsv** [comment]
Hey @teddykoker, unless I am mistaken, the Dice coefficient metric is acutally equivalent to F1 metric (see [here](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient#Name)) - so wouldn't it make more sense to simply wrap F1?

**Comment by teddykoker** [comment]
@tadejsv  Thats a great point! I'll do that

**Comment by justusschock** [comment]
@teddykoker @tadejsv But if we simply wrap L1 here, we should probably change the default for averaging to macro since with micro you can get a value above 1, which does not make sense at all (for macro it should be fine if I'm not mistaken).

**Comment by Borda** [comment]
Hi @teddykoker, we are very happy that you decided to improve PL and opened this PR.
Never the less we have moved the metric package outside PT, to a separate repository - [torchmetrics](https://github.com/PyTorchLightning/metrics), and unfortunately, there is not GH option to transfer your opened PR there to finish the job there. So I would like to kindly ask you if you are able to finish this PR by end of this week and then we can transfer your merged commit to the new repo or please open the very same PR in the new repository... 🐰 

Anyway thank you very much for being with us ⚡

**Pull request closed without merging**
