### PR TITLE
Remove rank_zero_only on DataModule prepare_data

### LINKED ISSUE #7927: DataModule PrepareData Only Called on Node 0
## 🐛 Bug

The LightningDataModule `prepare_data` function should be able to be called on the local rank 0 process on any node if the user chooses, and there are APIs around controlling this, but they don't work. I've reproduced this bug and traced it to one (rather obvious) line:

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/datamodule.py#L384

This line wraps the `prepare_data` function in `rank_zero_only`, a function which means global zero not local zero. There is already logic in the data connector around making sure that the function is only run when it is supposed to. Apparently the multi-node setup was never tested? 

This fix is simple: just delete the `rank_zero_only` part.

### Additional context

This is a quick one-line fix that I'm happy to PR, but someone needs to engage with me on it so that it actually gets merged.

### PR DESCRIPTION
**Pull request by Queuecumber**
## What does this PR do?

Fixes #7927 

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Queuecumber** [comment]
cc @awaelchli

**Comment by Queuecumber** [comment]
I was looking into adding new tests but it looks like there are already decent tests for `can_prepare_data`, the problem is that they never actually called `prepare_data` to see if it worked. We could add new tests to actually call the underlying `prepare_data` to cover these cases if you want.

**Review by ananthsub — APPROVED** [review]

**Comment by carmocca** [comment]
Thanks for the fix!

> the problem is that they never actually called prepare_data to see if it worked. We could add new tests to actually call the underlying prepare_data to cover these cases if you want.

Yes, this would be valuable.
Also, remember to update the CHANGELOG.md 👍

**Comment by Queuecumber** [comment]
OK changelog and tests updated

**Review by awaelchli — APPROVED** [review]
thanks for extending the tests, great fix. Running tests now.

**Comment by Queuecumber** [comment]
I see the failing mypy check and I'll look into it ASAP

**Review by Borda — APPROVED** [review]

**Comment by awaelchli** [comment]
@Queuecumber thanks for the fix
The mypy failure is unrelated to your changes

**Pull request merged**
