### PR TITLE
remove unused rpc import in modelcheckpoint causing import error

### LINKED ISSUE #5197: ImportError: cannot import name 'invoke_rpc_builtin' from 'torch.distributed'
```python
Python 3.7.9 (default, Aug 31 2020, 07:22:35)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning as pl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ericwiener/anaconda3/envs/donkey/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 61, in <module>
    from pytorch_lightning.callbacks import Callback
  File "/Users/ericwiener/anaconda3/envs/donkey/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py", line 19, in <module>
    from pytorch_lightning.callbacks.model_checkpoint import ModelCheckpoint
  File "/Users/ericwiener/anaconda3/envs/donkey/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 36, in <module>
    from pytorch_lightning.plugins.rpc_plugin import RPCPlugin
  File "/Users/ericwiener/anaconda3/envs/donkey/lib/python3.7/site-packages/pytorch_lightning/plugins/rpc_plugin.py", line 24, in <module>
    from torch.distributed import rpc
  File "/Users/ericwiener/anaconda3/envs/donkey/lib/python3.7/site-packages/torch/distributed/rpc.py", line 3, in <module>
    from . import invoke_rpc_builtin, invoke_rpc_python_udf, invoke_remote_builtin
ImportError: cannot import name 'invoke_rpc_builtin' from 'torch.distributed' (/Users/ericwiener/anaconda3/envs/donkey/lib/python3.7/site-packages/torch/distributed/__init__.py)
```

reported on slack
https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1608427484257200
by Eric Wiener

it probably happens when torch<1.7 (due to missing rpc)

### PR DESCRIPTION
**Pull request by awaelchli**
Fixes #5197

it looks like this import error is caused in pytorch < 1.7

### CODE REVIEW

**Comment by Borda** [comment]
Can we clean all imports in this subpackage with isort?

**Comment by awaelchli** [comment]
ok but it didn't really change anything :)

**Comment by Borda** [comment]
> ok but it didn't really change anything :)

well no we can remove this file from `isort` ignore so no one in the future will mess with imports here :]

**Comment by Borda** [comment]
@awaelchli in fact we shall not ignore these :D
https://github.com/PyTorchLightning/pytorch-lightning/blob/618580b4200e90b0acbb5f847865e0e9c02adec3/setup.cfg#L70

**Comment by Borda** [comment]
will be reflected #5201 (this goes for 1.2)

**Comment by awaelchli** [comment]
ok is it good now?

**Comment by Borda** [comment]
for the isort you can use `isort pytorch_lightning/callbacks/model_checkpoint.py --automatic`

**Review by SeanNaren — APPROVED** [review]

**Review by rohitgr7 — APPROVED** [review]

**Review by Borda — APPROVED** [review]
lgtm

**Pull request merged**
