### PR TITLE
add congratulations at the end of our notebooks

### PR DESCRIPTION
**Pull request by tchaton**
## What does this PR do?

This PR add a message at the end of each notebook

Fixes # (issue)

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In in short, see following bullet-list:  

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by tchaton** [comment]
Screenshot 2020-11-06 at 18 07 56

**Review by Borda — APPROVED** [review]

**Review by teddykoker — APPROVED** [review]

**Comment by edenlightning** [comment]
Until we get https://www.reviewnb.com/ ill just put suggestions here:
1. Some of the exclamation marks can be replaced with colons, "You can do so in the following ways:"
2. Capitalization
3. Add link to slack
4. "Interested in SOTA models? Check out Bolts. Bolts has a collection of models, all implemented in lightning, ...."
5. "Contribute"
+ "You can also contribute your own notebooks with useful examples"

**Comment by Borda** [comment]
@williamFalcon could you pls add it, @teddykoker @edenafek  what are the bullet points do so?

**Review by ydcjeff — APPROVED** [review]

**Comment by tchaton** [comment]
Screenshot 2020-11-07 at 11 48 55

**Pull request merged**
