### PR TITLE
Rename some doc files

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

Fixes #\<issue_number>

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @rohitgr7

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Review by kaushikb11 — APPROVED** [review]

**Review by akihironitta — APPROVED** [review]
Is it worth changing `profiler.rst` to `profiling.rst`? I don't see it very necessary, and some users might still access https://pytorch-lightning.readthedocs.io/en/stable/advanced/profiler.html (pasted somewhere in issues/discussions/external websites) and will get 404 because of this change.

**Comment by kaushikb11** [comment]
I agree with @akihironitta here. We shouldn't rename doc files unless it is necessary.

**Comment by rohitgr7** [comment]
just the profiler needs to be reverted? rest is fine??

**Review by ananthsub — APPROVED** [review]

**Review by akihironitta — COMMENTED** [review]
Personally, I'm ok with these ones:
```
docs/source/advanced/advanced_gpu.rst → docs/source/advanced/model_parallel.rst
docs/source/advanced/mixed_precision.rst → docs/source/advanced/precision.rst
docs/source/common/test_set.rst → docs/source/common/evaluation.rst
```

but not sure if it's really worth changing the following ones:
```
docs/source/advanced/profiler.rst → docs/source/advanced/profiling.rst
docs/source/common/optimizers.rst → docs/source/common/optimization.rst
docs/source/starter/introduction_guide.rst → docs/source/starter/core_guide.rst
docs/source/clouds/cluster.rst → docs/source/clouds/cluster_environment.rst
```

What do you think?

**Comment by rohitgr7** [comment]
I think just revert these?
```
docs/source/advanced/profiler.rst → docs/source/advanced/profiling.rst
docs/source/clouds/cluster.rst → docs/source/clouds/cluster_environment.rst
```
the reason: optimization consists mostly of topics related to optimization rather than just optimizers.
we already have `introduction.rst` now, so thought to rename the other one to `core_guide` since it's talking about the core components guide.

I agree a lot of links will fail, but we have moved certain sections/renamed them, so already existing links will eventually fail at other places too.

wdyt?

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
