### PR TITLE
Pickle the hparams directly

### PR DESCRIPTION
**Pull request by falceeffect**
Attempt at fixing #525. Works for me. Was not sure what to do with the hpc parts, so I decided to leave them as they are for now.

### CODE REVIEW

**Comment by neggert** [comment]
Looks like a good start. Could you please write a test for this functionality?

**Comment by williamFalcon** [comment]
just curious, why not detect all passed in params? i think there’s a way to introspect into the arguments passed into init (something about local)? that way we can pickle anything passed in?

**Comment by williamFalcon** [comment]
@falceeffect mind rebasing master into this? this also looks like WIP until the test is  written?

**Comment by williamFalcon** [comment]
@neggert @Borda @falceeffect is this PR still alive? can we get it merged in the next few days. If not, we can close it until it's ready to be worked on

**Comment by Borda** [comment]
it looks inactive for some time... :/

**Pull request closed without merging**
