### PR TITLE
add autograd profiler

### LINKED ISSUE #3917: Support PyTorch Profiler
Integrate [Pytorch Profiling](https://pytorch.org/tutorials/recipes/recipes/profiler.html) into Lightning.

### PR DESCRIPTION
**Pull request by quinor**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Adds a profiler based on `torch.autograd.profile.profiler`. It's different from the existing profilers as it allows to profile impact of specific pytorch ops (including C/C++ and CUDA code) compared to just the python code.

Closes #3917.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.
@jeremyjordan 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@quinor what do need help with? @jeremyjordan may you have look?

**Comment by quinor** [comment]
Tests, docs and thread safety + (of course) a review. Please see the list at the end of the top message.

**Comment by jeremyjordan** [comment]
@Borda would you mind looking into the thread safety?

**Comment by Borda** [comment]
> Borda would you mind looking into the thread-safety?

what do you mean by thread-safety, in python unless it is spec by no-GIL locker it is always safe...

**Comment by quinor** [comment]
> > Borda would you mind looking into the thread-safety?
> 
> what do you mean by thread-safety, in python unless it is spec by no-GIL locker it is always safe...

Quoted from my initial PR message:

"thread-safety (the profiler may fail if it's ran in multiple threads, ie. when there's more than one dataloader worker the profiler can be entered with the same action_name multiple times at once and that doesn't end well)"

Basically if someone does:
```
[thread1] profiler.start("name")
[thread2] profiler.start("name")
[thread1] profiler.stop("name")
[thread2] profiler.stop("name")
```

my profiler does break. There are 3 options I see right now:
1) fix this profiler so that it's OK
2) fix the way profilers are called in PL so that it doesn't happen
3) (I think might be the best) add some kind of UID to the `profiler.{start, stop}` calls so that each start-stop pair is unique. Alternatively make start return an object "stop" is called upon, that would require a bit of code rework though.

**Comment by edenlightning** [comment]
@Borda keep this PR?

**Comment by sachit-menon** [comment]
Just came across this linked in the Slack - this would be very cool functionality if it could end up merged.

**Comment by quinor** [comment]
> Just came across this linked in the Slack - this would be very cool functionality if it could end up merged.

feel free to work on it, I'm not deep enough in lightning to fix the issues I pinpointed :/

**Comment by sachit-menon** [comment]
I'm not either unfortunately, but the issue with the profiler and num_workers > 0 seems like it may have deeper roots: https://github.com/pytorch/pytorch/issues/6313

**Comment by Borda** [comment]
I 'll have a look just when we fix master so we can easily debug the optional issue here...

**Comment by SeanNaren** [comment]
Picking this up now, I think it might be worth being selective of the keys we'd like to profile. In most cases this would be the model forward/back/optim step. So something like:

```python
    def __init__(self):
        self.keys = ['model_forward', 'model_backward']
        ...

    def start(self, action_name: str) -> None:
        if action_name in self.keys:
            self.profilers[action_name] = profiler.profile(
                profile_memory=self.profile_memory,
                use_cuda=self.use_cuda,
                record_shapes=self.group_by_input_shape
            )
            self.profilers[action_name].__enter__()
```

Thoughts?

I'll make some changes to expose a few more variables as well.

**Comment by edenlightning** [comment]
Hey @quinor, need help in getting this done?

**Comment by quinor** [comment]
Hey,

I had not touched lightning since June. I'll try to pick it up, bring it to master and finalize this PR in the next few weeks as I'm back to work now. As for the multithreading issue, I think it might not be easily fixable and the easiest way is to just write in the documentation that dataloaders must not use threads when profiled.

@edenlightning if you're able to efficiently finalize this PR feel free to do so. Docs, (potential) tests and synchronizing it with current master are things left to do. I'll try to do that on my own otherwise.

**Comment by SeanNaren** [comment]
awesome news, thanks so much @quinor :)

**Comment by Borda** [comment]
@quinor how is it going, do you this we gen this done by end of this week to pass to 1.1? 🐰

**Comment by quinor** [comment]
@Borda I'll try to get the code ready on wednesday + hopefully some docs. I hope we can then close it by the end of the week.

**Comment by quinor** [comment]
I see some tests failing for pytorch 1.3 (since old pytorch's `autograd.profile` does not support `profile_memory`) - what should we do with that?

**Comment by quinor** [comment]
@Borda it's ready from my side, some issues (tests failing due to old pytorch) still pending that I couldn't resolve by myself. Do you still want to push it into 1.1?

**Comment by tchaton** [comment]
Hey @quinor,

I have a similar PR there: https://github.com/PyTorchLightning/pytorch-lightning/pull/5560/. Let's merge them together.

Best,
T.C

**Comment by quinor** [comment]
closing, #5560 implements this profiler.

**Pull request closed without merging**
