### PR TITLE
Add docs rendered link

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

Added: https://github.com/larsoner/circleci-artifacts-redirector-action
saves you 3 clicks and an extra tab.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @carmocca @akihironitta @borda

### CODE REVIEW

**Review by akihironitta — APPROVED** [review]

**Comment by akihironitta** [comment]
I remember this has to be merged into master to see if it's working.

**Comment by rohitgr7** [comment]
> I remember this has to be merged into master to see if it's working.
> 
> Update: For reference: [PyTorchLightning/lightning-flash#267 (comment)](https://github.com/PyTorchLightning/lightning-flash/pull/267#issuecomment-835847186)

thanks @akihironitta, let's see if it works :)

**Comment by Borda** [comment]
@rohitgr7 does it how the job already in this PR?

**Review by carmocca — APPROVED** [review]

**Comment by rohitgr7** [comment]
> @rohitgr7 does it how the job already in this PR?

not yet @Borda. As @akihironitta mentioned, it needs to be merged to see it on other PRs. we have it in flash as well: https://github.com/PyTorchLightning/lightning-flash/pull/267#issuecomment-835847186

**Comment by akihironitta** [comment]
For workflows triggered with:
```
on: [status]
```
we need to have workflow files in master branch.

> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#status

**Review by akihironitta — APPROVED** [review]

**Review by s-rog — APPROVED** [review]
Nice QoL improvement!

**Pull request merged**
