### PR TITLE
Bugfix/fix gan example

### PR DESCRIPTION
**Pull request by armavox**
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)

## What does this PR do?
Fixes  https://github.com/PyTorchLightning/pytorch-lightning/issues/1223

GAN example in repo was not working. Fixed typos and working in dp, and ddp mode.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by ternaus** [comment]
Is there a way to implement caching of the generated images?

Without it, the code works twice slower as we need to generate both in generator and discriminator phases.

**Comment by williamFalcon** [comment]
@armavox we moved away from hparams.
Made the changes, verify?

**Comment by ternaus** [comment]
@williamFalcon is there a way to avoid doing `self(z)` in the discriminator phase and reuse images generated at the generator phase?

**Comment by armavox** [comment]
@williamFalcon ok. Good.

**Comment by armavox** [comment]
@ternaus you’re right. However, the problem is that in forward() model is replicating every time, then the training_step() called for each copycat. So for me it seems that there is the only way to store buffered variables - save it in the initial class before replicating, e.g. to initialize generated images in __init__, and then pull there value from the one of copies. But each copy tends to generate own images, hence use of common buffer seems to be incorrect.

**Comment by williamFalcon** [comment]
@ternaus yes, easiest is to use ddp and NOT dp (dp is not recommended anyhow).

However, we're working on a fix to maintain state in dp @ananyahjha93

**Comment by ananyahjha93** [comment]
@williamFalcon thanks for pointing me to this updated GAN example.

**Comment by armavox** [comment]
@williamFalcon @ananyahjha93 may I see the branch, where are you working on that problem?

**Comment by ananyahjha93** [comment]
@armavox This is a [wip] commit but the current look of the solution is quite different from this. So, this is not a representation of the solution we are working on right now. 

https://github.com/PyTorchLightning/pytorch-lightning/pull/1895

**Pull request merged**
