### PR TITLE
conda speedup

### LINKED ISSUE #2491: CI: proper Conda caching
## 🚀 Feature

Fix the Github action test fro Conda, it seems that the environment is always made from search which takes about 8min even according action readme we shall cache the environment...

### Motivation

Significantly speed-up CI tests using Conda

https://github.com/goanpeca/setup-miniconda#caching

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Fixes Conda CI speed
check https://github.com/goanpeca/setup-miniconda/issues/54
Fixes #2491

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@tgaddair just updating Conda env and having some problem re-install Horovod...
I guess it is a problem of caching, right?

**Comment by Borda** [comment]
> @tgaddair just updating Conda env and having some problem re-install Horovod...
> I guess it is a problem of caching, right?

@tgaddair any suggestion? ^^

**Comment by tgaddair** [comment]
Hey @Borda, yes, looks like the same issue we've seen before with the pip cache.

Basically, the problem goes like this:

1. Some version of PyTorch and Horovod exist in the cache and are pulled into the env
2. A new version of PyTorch is installed, but Horovod is not changed
3. Horovod throws an error because it was compiled against a different PyTorch version

If possible, best solution is to uninstall and reinstall Horovod after the PyTorch version is changed, making sure to pass in `--no-cache-dir` to pip to ensure it is recompiled from source.

**Comment by Borda** [comment]
> If possible, best solution is to uninstall and reinstall Horovod after the PyTorch version is changed, making sure to pass in `--no-cache-dir` to pip to ensure it is recompiled from source.

sure, but the reinstall step is already there...

**Comment by tgaddair** [comment]
@Borda, I think I see what's happening here.  My guess is that this script is running with `set -e` so that when `HOROVOD_BUILT=...` is called and exits 1, it causes the whole run to stop.

Can you try changing this line to:

```
HOROVOD_BUILT=$(python -c "import horovod.tensorflow; horovod.tensorflow.nccl_built(); print('SUCCESS')" || true)
```

That way, the exit code will always be 0, but the check should still work.

**Pull request merged**
