### PR TITLE
Fixing horovod with GPU training code 

### PR DESCRIPTION
**Pull request by muhyun**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [X] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Fixes # (issue).

https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html guides to set 'gpus' to use GPU with Horovod, but it returns error saying;

> Horovod does not support setting num_nodes / num_gpus explicitly. Use 
>horovodrun / mpirun to configure the number of processes.

This PR is to set self.on_gpu if gpus >= 1, and to remove the error message.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
Cc: @tgaddair ^^

**Comment by tgaddair** [comment]
Note that setting `gpus > 1` will not do anything in the case of Horovod, as that is controlled by the `horovodrun` script.  I feel removing this may be misleading, as users might expect it to control the number of GPUs used by Horovod.

One thing we may wish to do in the future is have `gpus` control the number of GPUs *per worker* (for model parallelism), but that is currently not supported.

@muhyun, Is there a reason you feel that we should remove this check?

**Comment by muhyun** [comment]
@tgaddair, that's a good point. If I remove `gpus` in Trainer, it uses CPUs not GPUs. With `gpus` specified hoping to use GPU as per the document(https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html), it returns error not to use `gpus`.

```
# train Horovod on GPU (number of GPUs / machines provided on command-line)
trainer = Trainer(distributed_backend='horovod', gpus=1)

# train Horovod on CPU (number of processes / machines provided on command-line)
trainer = Trainer(distributed_backend='horovod')
```

As you said, it is a bit weird to have two places to set the number of GPUs, but this fix works in the current implementation because `horovod_train` checks if `self.on_gpu` is True.

```
    def horovod_train(self, model):
        if torch.cuda.is_available() and self.on_gpu:
            # Horovod: pin GPU to local rank
            assert self.root_gpu == hvd.local_rank()
            torch.cuda.set_device(self.root_gpu)
            model.cuda(self.root_gpu)
```

**Comment by tgaddair** [comment]
Hey @muhyun, to clarify, do you still get the error if you set `gpus=1`?  That should work without this change (if not, then there's a bug somewhere).

**Comment by muhyun** [comment]
Yes, that is why I commented out as well as adding a line to set ‘on_gpu’ flag.

**Comment by tgaddair** [comment]
I see.  Sounds like `self.on_gpu = True if self.num_gpus >= 1 else False` may be a good change, then.  Let me see if I can repro first.  My guess is there was a recent change that broke Horovod GPU binding.

**Comment by tgaddair** [comment]
Hey @muhyun, I just tested this on master using the following trainer:

```
trainer = pl.Trainer(gpus=1, distributed_backend='horovod')
```

It correctly pinned the model to GPU, as expected.

Can you share some logs or a min example that reproduces the error?  I am unable to reproduce it so far.

**Comment by muhyun** [comment]
I could re-produce this using a sample in pl_examples/basic_examples with `gpus` as 2 or larger;

```
$ horovodrun -np 2 python gpu_template.py --gpus 2 --distributed_backend horovod
```

This returns,

```
[1,0]<stderr>:pytorch_lightning.utilities.exceptions.MisconfigurationException: Horovod does not support setting num_nodes / num_gpus explicitly. Use horovodrun / mpirun to configure the number of processes.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
```

However, if `gpus` is set to 1 as you did, it runs using two GPUs;

```
$ horovodrun -np 2 python gpu_template.py --gpus 1 --distributed_backend horovod
```

With this observation, the fix might be update the document like

> set `gpus=1` to train Horovod on GPU

But it could be a bit inconvenient for who wants to try different multi gpu training option by changing the value of `distributed_backend`.

**Comment by tgaddair** [comment]
Thanks for clarifying @muhyun.  Sounds like the behavior is "correct" in that it's what I originally intended, but may not be intuitive.

It's tricky because I agree that it would be convenient to be able to swap between different backends with minimal code changes, but I don't want users to be confused about what `gpus` means for the Horovod backend.

I can think of a few options:

1. We keep the current behavior, so the user is forced to set `gpus=1` to enable GPU training, and thereby acknowledge that number of GPUs is controlled externally (by `horovodrun`).  We could do a doc update to make this more clear.
2. Going with this PR, we could allow the user to specify any `gpus>0` to enable GPU pinning for Horovod.  This makes it easier to test backends, but may confuse users who think changing this parameter will have an effect when using Horovod.
3. We implement the behavior from (2), but add a warning to the user if `gpus>1` indicating that the parameter is unused, and to use `horovodrun` to configure the number of GPUs.

Based on the confusion this has caused, I'm inclined towards option (3).  It would be good to get some other thoughts from @Borda and @williamFalcon as well.

**Comment by williamFalcon** [comment]
@tgaddair there's no way to forward that gpus flag to horovod? or to have that be what controls the gpus?

what is we set that flag as an env var?
```
PL_GPUS
```

**Comment by williamFalcon** [comment]
@tgaddair sounds like we can close this? let's reopen if needed

**Comment by tgaddair** [comment]
Hey @williamFalcon, yes I think it's fine to close this for now.  To answer your question, the problem with forwarding the `gpus` flag is that Horovod determines the number of GPUs before we execute that line of code.  There is a `horovodrun` command line tool that specifies the number of processes and launches the training script, so the most we can do is determine whether we want to use GPU vs CPU (or, in the future, if we want to have multiple GPUs per process).  Does that make sense?

**Pull request closed without merging**
