### PR TITLE
Use PyTorch API logging for Lightning Trainer

### PR DESCRIPTION
**Pull request by ananthsub**
## What does this PR do?
This adds the torch API usage logging to the Trainer class for each of the Trainer's public APIs. By default, this is a no-op. For large deployments of PyTorch, this can be configured to better track usage across the fleet: https://pytorch.org/docs/stable/notes/large_scale_deployments.html#api-usage-logging

This follows the same pattern already established in the [LightningModule here](https://github.com/PyTorchLightning/pytorch-lightning/blob/a72a7992a283f2eb5183d129a8cf6466903f1dc8/pytorch_lightning/core/lightning.py#L79-L81)

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by camruta** [comment]
Could you add details or link to some existing documentation about how to configure this to track usage? It's not very clear from https://pytorch.org/docs/stable/notes/large_scale_deployments.html#api-usage-logging

**Comment by ananthsub** [comment]
@camruta https://github.com/pytorch/pytorch/blob/6145ac07b5431a95e7d29f84ab979b332883b4ea/c10/util/Logging.cpp#L114-L117

**Review by Borda — APPROVED** [review]
lgtm

**Review by carmocca — COMMENTED** [review]
Maybe wrapping the call to these inside a function would be nice to not duplicate the comment

Also, is this very high level tracking enough? Don't we want to also annotate for example run epoch and other calls as we do with the profiler?

**Comment by ananthsub** [comment]
> Also, is this very high level tracking enough? Don't we want to also annotate for example run epoch and other calls as we do with the profiler?

Definitely not enough. We'll need much more fine-grained event logging + much more trainer metadata. This is a really high-level logging for large deployments of pytorch/Lightning to even distinguish which jobs are which on a cluster

**Comment by tchaton** [comment]
> > Also, is this very high level tracking enough? Don't we want to also annotate for example run epoch and other calls as we do with the profiler?
> 
> Definitely not enough. We'll need much more fine-grained event logging + much more trainer metadata. This is a really high-level logging for large deployments of pytorch/Lightning to even distinguish which jobs are which on a cluster

Hey @ananthsub, noob question. How does the cluster detects the torch API logging ?

**Comment by tchaton** [comment]
> Maybe wrapping the call to these inside a function would be nice to not duplicate the comment
> 
> Also, is this very high level tracking enough? Don't we want to also annotate for example run epoch and other calls as we do with the profiler?

I would prefer to put this within a function with a cleaner name. Looks too verbose to me.

**Review by tchaton — APPROVED** [review]
Please, wrap into an helper function.

**Review by awaelchli — APPROVED** [review]

**Pull request merged**
