### PR TITLE
Mark CheckpointConnector as protected

### LINKED ISSUE #11482: Mark `CheckpointConnector` as protected
## Proposed refactor

Mark `CheckpointConnector` as protected:
https://github.com/PyTorchLightning/pytorch-lightning/blob/18bbb39eef77c8c3d19789b1067164e962640c93/pytorch_lightning/trainer/trainer.py#L464

### Motivation

Part of #9778

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @kaushikb11 @ninginthecloud

### PR DESCRIPTION
**Pull request by krishnakalyan3**
## What does this PR do?

Fixes #11482

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by rohitgr7** [comment]
hey @krishnakalyan3 !
Signal connector is already done here: https://github.com/PyTorchLightning/pytorch-lightning/pull/11513
would you mind rebasing your branch with master?

also, you mean do to CheckpointConnector?

**Comment by krishnakalyan3** [comment]
Wow looks like I am super slow. You are right I made a mistake while naming the branch.

**Comment by rohitgr7** [comment]
> Wow looks like I am super slow. You are right I made a mistake while naming the branch.

you can still continue here. branch name looks correct :)

**Comment by krishnakalyan3** [comment]
Fixes #11482

**Comment by krishnakalyan3** [comment]
@rohitgr7 should the files below be changed?

```
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_checkpoint_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_from_checkpoint_fit_path == ckpt_path
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_checkpoint_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_from_checkpoint_fit_path == ckpt_path
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_checkpoint_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_from_checkpoint_fit_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_checkpoint_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_from_checkpoint_fit_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_checkpoint_path is None
./tests/deprecated_api/test_remove_2-0.py:    assert trainer.checkpoint_connector.resume_from_checkpoint_fit_path is None
```

**Comment by krishnakalyan3** [comment]
@rohitgr7 Looks like I have made the changes to all files, could you please review it?.

**Review by rohitgr7 — APPROVED** [review]
Thank you for your contribution 😃

**Review by ananthsub — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Review by ananthsub — APPROVED** [review]

**Comment by krishnakalyan3** [comment]
Thank you for the reviews.

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by awaelchli — APPROVED** [review]

**Comment by daniellepintz** [comment]
The GPUs test has been queued since yesterday, can someone rerun it?

**Comment by rohitgr7** [comment]
> The GPUs test has been queued since yesterday, can someone rerun it?

@daniellepintz there is some issue on the Azure side. All the PRs are in the queue.

**Comment by krishnakalyan3** [comment]
Looks like the GPU tests are still pending?

**Comment by akihironitta** [comment]
@krishnakalyan3 Yes. The tracking issue is #11634.

**Review by akihironitta — APPROVED** [review]
Although deprecation is not needed, shouldn't we add an entry to CHANGELOG.md similarly to #9779?

**Review by Borda — APPROVED** [review]

**Review by Borda — COMMENTED** [review]
changelog entry as it could be also seen as breaking change...?

**Pull request merged**
