### PR TITLE
Adding appends to some of the pseudocode blocks

### PR DESCRIPTION
**Pull request by calebrob6**
Small change to pseudocode blocks to make some of the example code more clear.

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by Borda — APPROVED** [review]

**Comment by carmocca** [comment]
@calebrob6 Can you rebase master?

**Comment by calebrob6** [comment]
@carmocca I rebased onto master but force pushed the changes (which seems to _not_ have been the correct way as it disabled auto-merge). How should I do this in the future?

**Comment by carmocca** [comment]
> @carmocca I rebased onto master but force pushed the changes (which seems to _not_ have been the correct way as it disabled auto-merge). How should I do this in the future?

Since you were a first time contributor, the CI needs to be approved, so you did fine by pinging one of us 🤟

**Pull request merged**
