### PR TITLE
self.forward() -> self()

### LINKED ISSUE #1209: update docs to recommend __call__ for forward passes
## 📚 Documentation

We should update the docs to recommend usage of `self(x)` for calculating the forward pass rather than `self.forward(x)`. Calling `forward()` directly can cause issues when you're using PyTorch model hooks (eg. see the additional logic in [`nn.Module.__call__`](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L540)).

Although most people don't play around with hooks and using `self.forward()` will work fine for them, we should probably follow the best practice (as I understand) of using `__call__` for calculating forward passes.

Related issues: #632

### PR DESCRIPTION
**Pull request by jeremyjordan**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?
Fixes #1209 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
@jeremyjordan what about the TPU issue?

**Comment by jeremyjordan** [comment]
can’t edit the title on mobile but this is WIP until TPU issue is resolved

**Comment by jeremyjordan** [comment]
@williamFalcon can you share more details about the TPU issue you ran into? i tried running the lightning_mnist_tpu notebook with this branch (and changing `self.forward()` to `self()` in the notebook) and it's running fine for me

**Comment by jeremyjordan** [comment]
@Borda  any idea what's up with the mergify bot?

**Comment by Borda** [comment]
@jeremyjordan we have there the following rule:
```
(on head branch) $ git rebase base
(on head branch) # Wait for CI to go green
(on head branch) # Squash all commits
(on base branch) $ git merge --ff head
```
looking to the master, it seems that there is some conflict with rebasing
```
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

**Pull request merged**
