### PR TITLE
Draft PR: Circle CI build-doc debug

### PR DESCRIPTION
**Pull request by tarepan**
## What does this PR do?
Draft PR for Circle CI debug related to PR #4402.  

We need Circle CI run for debug related to build-doc Circle CI error in #4402.  
In forked repository we cannot run Circle CI, so this draft PR is opened only for debug in upstream (this) repository.  

## Before submitting
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

### CODE REVIEW

**Comment by Borda** [comment]
hi @tarepan how is it going? :]

**Comment by tarepan** [comment]
Hi @Borda It seems that I successfully find the cause.  
At least, dependency description for docs (`requrements/docs.txt`) cause the bug.  
I modified only `requirements.txt`, so the current bug appear.  

After whole debug, I will fix original PR (#4402).  
Thank you for following up my works ;)

**Comment by Borda** [comment]
> It seems that I successfully find the cause.
> At least, dependency description for docs (`requrements/docs.txt`) cause the bug.

cool, so let's merge this also to master as separate PR, as it is 🐰

**Comment by tarepan** [comment]
> cool, so let's merge this also to master as separate PR, as it is 🐰

Fortunately, only when new dependency is added with improper way, the bug happen.  
(In PR #4402, new `fsspec[http]` cause the bug).  
So, current `master` is clean, no need of merge 👍

**Pull request closed without merging**
