### PR TITLE
Run black on the code base, add reformat commit to the git-blame-ignore list

### PR DESCRIPTION
**Pull request by f4hy**
## What does this PR do?
Update of #1967 

- [X] Update the pyproject.toml to set black to not normalize quotes
- [X] Format the entire code base
- [X] Add the format commit hash to `.git-blame-ignore-revs` so it will be ignored by git blame (so it doesn't look like I modified everything)
- [X] Update code-formatting.yml to run black as a check

(Will still cause merge conflicts all over though :shrug: )

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [X] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [X] Did you write any new necessary tests? 
- [X] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Always

### CODE REVIEW

**Comment by Borda** [comment]
what update means? seems to be duplicate to #1967

**Comment by ananyahjha93** [comment]
@Borda I read the previous PR as well, what's the consensus between core contributors? I don't think we should run black on the entire code base. 

1) I found black's reformatting disagree with pep8/flake8 at a number of places.
2) I second the view that this restricts coding style of individual conyributors.

**Comment by Borda** [comment]
that it the point, there is no consensus as we dislike some formatting patterns and probably they cannot be skipped...

**Comment by f4hy** [comment]
I can close this. I was just trying to add on a few fixes on top of #1967 . If this is not the route contributors want to go then this should be handled some other way.

**Pull request closed without merging**
