### PR TITLE
add auto_restore option to disable auto loading

### LINKED ISSUE #368: Disable automatic checkpoint loading
**Is your feature request related to a problem? Please describe.**
The last checkpoint is being automatically restored when a checkpoint exists. This is an issue for me when the model has previously been trained with different settings or I want to train a network from scratch. 

If I want to use a checkpoint I would prefer to explicitly pass the checkpoint that should be used.

**Describe the solution you'd like**
Provide an option to disable the automatic loading of checkpoints to the trainer.

**Describe alternatives you've considered**
An alternative would be to modify `ModelCheckpoint` class and add that option there so that only that class is responsible for checkpoint creation and loading.

### PR DESCRIPTION
**Pull request by Ir1d**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?
Fixes #368 (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

I think no one is actually working on this, so i brought a pr. 
As an hot fix, no breaking change is included.
Please get this solved asap. I'm fucked up by this auto loading..

### CODE REVIEW

**Comment by Ir1d** [comment]
@Borda @neggert @williamFalcon @ethanwharris please take a look

**Comment by williamFalcon** [comment]
i was thinking that we would just get rid of it altogether?

**Comment by Ir1d** [comment]
+1 for get rid of them all.
But it seems would be a huge update in docs, tests etc. I see the examples are associated with this feature. Also, someone might be still depending on this feature. So for now, I'm introducing this option as an intermediate option.

**Comment by Borda** [comment]
I do not have any strong opinion about it, I understand the point resume from lat automatically but it can be dangerous if you have a bit mess in your logging folder so resuming from a specific checkpoint is better...

**Comment by Ir1d** [comment]
anyway, I've edit my local pl to remove the restore function.. Feel free to close this PR if you'd like to remove the loading at once.

>  it can be dangerous if you have a bit mess in your logging folder so resuming from a specific checkpoint is better...

Indeed, the logging behavior is hidden and not clearly logged, and it is called inside model.fit, which overwrites any initialization all ckpt loading

**Comment by williamFalcon** [comment]
yeah,  let's remove it altogether

**Pull request closed without merging**
