### PR TITLE
[wip] Fix ddp incorrectly reading CUDA_VISIBLE_DEVICES 

### LINKED ISSUE #3422: DDP doesn't work properly with CUDA_VISIBLE_DEVICE
## 🐛 Bug

DDP trainer doesn't work properly when CUDA_VISIBLE_DEVICE is set.

### To Reproduce

1. Set `CUDA_VISIBLE_DEVICE=1,2`
2. Run DDP trainer with 2 GPUs
3. The main process will use `available_gpus[self.trainer.local_rank]` that is equal to `1`
4. The second process will use GPU `process_idx` that is again equal to `1`
5. Thus both processes will use the same single GPU, instead of both

### Expected behavior
Training should use both GPUs.

### Suggestion
Looks like the following if-statement causes the problem:
https://github.com/PyTorchLightning/pytorch-lightning/blob/5b4db52851000d5e4eca8c680d851bcdaafc3a80/pytorch_lightning/accelerators/ddp_backend.py#L204

Why do we use `int(available_gpus[self.trainer.local_rank])` instead of simple `process_idx`?
As far as I understand, the master process should always use GPU 0, which is equal to the first GPU in the `CUDA_VISIBLE_DEVICE` list. Please, correct me if I am wrong.

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Fixes #3422

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
I was able to reproduce the issue and verify the fix for DDP, but I can't test DDP2. 
@williamFalcon @teddykoker is the fix correct for DDP2? I would assume it is, due to the similarity to ddp.

**Comment by williamFalcon** [comment]
i don’t think this is correct... but i’ll double check.

**Comment by awaelchli** [comment]
ok, in case there is something more that needs to be done, let me know, happy to look into it. 
marking it wip until double checked on your cluster.

**Comment by Borda** [comment]
@awaelchli how about this one, is it still WIP or ready to review? 🐰

**Comment by awaelchli** [comment]
Yes it is wip until I have @williamFalcon's ok to go with this fix.

**Comment by Borda** [comment]
> Yes it is wip until I have @williamFalcon's OK to go with this fix.

he just mentioned that he is done with refactoring so I guess we can go...

**Comment by awaelchli** [comment]
ok, but I would like his explicit approval :) or at least someone else manually testing the fix. Because this is ddp, and I cannot check it on multi node.

**Comment by Borda** [comment]
@williamFalcon ^^

**Comment by williamFalcon** [comment]
ok, going through this now.

i want to confirm that ddp_spawn works as expected:

Using this command:
```CUDA_VISIBLE_DEVICES='0,3,4' python autoencoder.py --distributed_backend 'ddp_spawn' --gpus '1,2'```
image

**Comment by williamFalcon** [comment]
Now verified that my fix on #3733 is also correct:

By running command:
```CUDA_VISIBLE_DEVICES='0,3,4' python autoencoder.py --distributed_backend 'ddp' --gpus '1,2'```
image

**Comment by awaelchli** [comment]
@williamFalcon why would this 
`CUDA_VISIBLE_DEVICES='0,3,4' python autoencoder.py --distributed_backend 'ddp' --gpus '1,2'`

run on gpu 0 and 3. doesn't visible devices apply before the gpus flag?

**Pull request closed without merging**
