### PR TITLE
Annotate return type of TrainerProperties.from_argparse_args(...)

### PR DESCRIPTION
**Pull request by EliaCereda**
## What does this PR do?

Adds the return type annotation for the `TrainerProperties.from_argparse_args(...)` method.

Currently no annotation is present for the return type of `TrainerProperties.from_argparse_args`. This results in suboptimal developer experience when using it:
```python
trainer = Trainer.from_argparse_args(args)

# trainer's type is inferred to be Any, which means that IDEs cannot autocomplete 
# or show documentation for its methods.
trainer.fit(model)
```

## Alternatives
Instead of using the type variable, an alternative would be to directly annotate `from_argparse_args` as returning an instance of `Trainer`, since it's the only class that inherits from `TrainerProperties`. I went with the type variable because it looked like a more general solution to me, for little additional complexity.

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]
lgtm

**Review by ydcjeff — APPROVED** [review]
LGTM

**Review by SkafteNicki — APPROVED** [review]

**Review by akihironitta — APPROVED** [review]

**Review by s-rog — APPROVED** [review]

**Comment by s-rog** [comment]
That revert was a misclick, sorry about that

**Comment by Borda** [comment]
@s-rog it seems it brought some issue to master for PT 1.7
https://github.com/PyTorchLightning/pytorch-lightning/runs/1268380603
could you pls check it out?

**Comment by s-rog** [comment]
I just looked through the logs and looks like MNIST failed to download in one of the tests... possibly a temporary network issue, should I try re-running? @Borda 

<details>
  <summary>log snippet</summary>

```
2020-10-17T12:16:09.8365726Z tests/core/test_results.py:123: 
2020-10-17T12:16:09.8366076Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2020-10-17T12:16:09.8366641Z pytorch_lightning/trainer/trainer.py:414: in fit
2020-10-17T12:16:09.8367191Z     self.data_connector.prepare_data(model)
2020-10-17T12:16:09.8367851Z pytorch_lightning/trainer/connectors/data_connector.py:59: in prepare_data
2020-10-17T12:16:09.8368640Z     self.trainer.datamodule.prepare_data()
2020-10-17T12:16:09.8369344Z pytorch_lightning/core/datamodule.py:90: in wrapped_fn
2020-10-17T12:16:09.8369822Z     return fn(*args, **kwargs)
2020-10-17T12:16:09.8370342Z pytorch_lightning/utilities/distributed.py:35: in wrapped_fn
2020-10-17T12:16:09.8370856Z     return fn(*args, **kwargs)
2020-10-17T12:16:09.8371289Z tests/base/datamodules.py:31: in prepare_data
2020-10-17T12:16:09.8371845Z     TrialMNIST(self.data_dir, train=True, download=True)
2020-10-17T12:16:09.8378874Z tests/base/datasets.py:196: in __init__
2020-10-17T12:16:09.8379479Z     download=download
2020-10-17T12:16:09.8379877Z tests/base/datasets.py:73: in __init__
2020-10-17T12:16:09.8380310Z     self.prepare_data(download)
2020-10-17T12:16:09.8380772Z tests/base/datasets.py:220: in prepare_data
2020-10-17T12:16:09.8381255Z     self._download(super().cached_folder_path)
2020-10-17T12:16:09.8381726Z tests/base/datasets.py:118: in _download
2020-10-17T12:16:09.8382311Z     urllib.request.urlretrieve(url, fpath)
2020-10-17T12:16:09.8383070Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:247: in urlretrieve
2020-10-17T12:16:09.8383899Z     with contextlib.closing(urlopen(url, data)) as fp:
2020-10-17T12:16:09.8384532Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:222: in urlopen
2020-10-17T12:16:09.8385112Z     return opener.open(url, data, timeout)
2020-10-17T12:16:09.8385670Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:525: in open
2020-10-17T12:16:09.8386200Z     response = self._open(req, data)
2020-10-17T12:16:09.8386726Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:543: in _open
2020-10-17T12:16:09.8387473Z     '_open', req)
2020-10-17T12:16:09.8387953Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:503: in _call_chain
2020-10-17T12:16:09.8388454Z     result = func(*args)
2020-10-17T12:16:09.8388957Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:1393: in https_open
2020-10-17T12:16:09.8389598Z     context=self._context, check_hostname=self._check_hostname)
2020-10-17T12:16:09.8390224Z /root/miniconda3/envs/lightning/lib/python3.7/urllib/request.py:1353: in do_open
2020-10-17T12:16:09.8390734Z     r = h.getresponse()
2020-10-17T12:16:09.8391332Z /root/miniconda3/envs/lightning/lib/python3.7/http/client.py:1354: in getresponse
2020-10-17T12:16:09.8392004Z     response.begin()
2020-10-17T12:16:09.8392508Z /root/miniconda3/envs/lightning/lib/python3.7/http/client.py:306: in begin
2020-10-17T12:16:09.8393062Z     version, status, reason = self._read_status()
2020-10-17T12:16:09.8393672Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2020-10-17T12:16:09.8393862Z 
2020-10-17T12:16:09.8394374Z self = <http.client.HTTPResponse object at 0x7fa1dfbd7890>
2020-10-17T12:16:09.8394828Z 
2020-10-17T12:16:09.8395111Z     def _read_status(self):
2020-10-17T12:16:09.8395768Z         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2020-10-17T12:16:09.8396226Z         if len(line) > _MAXLINE:
2020-10-17T12:16:09.8396624Z             raise LineTooLong("status line")
2020-10-17T12:16:09.8397048Z         if self.debuglevel > 0:
2020-10-17T12:16:09.8397412Z             print("reply:", repr(line))
2020-10-17T12:16:09.8397729Z         if not line:
2020-10-17T12:16:09.8398168Z             # Presumably, the server closed the connection before
2020-10-17T12:16:09.8398667Z             # sending a valid response.
2020-10-17T12:16:09.8399244Z >           raise RemoteDisconnected("Remote end closed connection without"
2020-10-17T12:16:09.8399895Z                                      " response")
2020-10-17T12:16:09.8400609Z E           http.client.RemoteDisconnected: Remote end closed connection without response
2020-10-17T12:16:09.8401223Z 
2020-10-17T12:16:09.8401775Z /root/miniconda3/envs/lightning/lib/python3.7/http/client.py:275: RemoteDisconnected
```

</details>

**Pull request merged**
