### PR TITLE
Add warning on argparse gpus flag

### LINKED ISSUE #6228: cli: Confused on (str, int, List[int]) variants for argparse for --gpus flag?
## 🐛 Bug

A colleague (@siyuanfeng-tri) and I sometimes get confused on how the `--gpus` flag is to be interpreted by `argparse`. I see the following docs:
https://pytorch-lightning.readthedocs.io/en/1.2.1/advanced/multi_gpu.html#select-gpu-devices

But we're sometimes confused about when `argparse` interpretation will either assume it's the count of the gpu (int/str) or the device index (List[int]).

Are there docs for this? If not, can that be clarified somehow?

## Please reproduce using the BoringModel

see notebook

The main complaint is that `gpus=3` implies `gpus=[3]`, while `gpus="3"` implies `gpus=[0,1,2]`.
Mix that with implicit conversion from `argparse` from `str` to `int`, and you get a kinda weird public interface.

### To Reproduce

example notebook: https://colab.research.google.com/drive/1pe9_F2S73-gQ3hOeh_MMiGhmbXmGURDQ?usp=sharing

### Expected behavior

Less confusing / more explicit options? (maybe my complaint is with weird implicit behavior of `Trainer(gpus=...)`?)

### Environment

 - PyTorch Version (e.g., 1.7.1):
 - OS: Ubuntu 18.04
 - How you installed PyTorch: `pip`
 - Python version: 3.6.9
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by edenlightning**
fixes #6228.

### CODE REVIEW

**Review by kaushikb11 — APPROVED** [review]

**Comment by awaelchli** [comment]
This does not address #6228. This argparser here in the example doesn't have a type, so the string is forwarded to the trainer as if you would set Trainer(gpus="3"). This selects the third GPU, not [1, 2, 3] and it is different form our Lightning argparser. See this example:


```python
import os
from argparse import ArgumentParser

import torch
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    parser = ArgumentParser()
    parser.add_argument("--gpus", default=None)
    args = parser.parse_args()

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        num_sanity_val_steps=0,
        gpus=args.gpus,
        weights_summary=None,
    )
    trainer.fit(model, train_dataloader=train_data, val_dataloaders=val_data)
    trainer.test(model, test_dataloaders=test_data)


if __name__ == '__main__':
    run()
```

As I explained in the issue and on the linked PR, the issue is not with any of the arparser logic we have. The origin of the confusion is the argument in the Trainer itself, when passing in a string: `Trainer(gpus="3")`. 
The confusion comes from the fact that `Trainer(gpus="3")` does not mean the same as `Trainer(gpus=3)`

**Comment by tchaton** [comment]
Hey @awaelchli,

Should we change this behaviour and convert "3" to map to [0, 1, 2] instead. 
It will be a breaking change but we can add a warning that this behaviour will enforced in 1.5 ?

Your thoughts ?

**Comment by awaelchli** [comment]
To fix the confusion yes, it would be the best option IMO. And it's what I was doing here in this PR #6388 already to resolve the issue, but got push back because it's a backward incompatible change and so we are not allowed to change it.

**Comment by tchaton** [comment]
Hey @awaelchli, closing this PR then :)

**Pull request closed without merging**
