### PR TITLE
re-trigger build

### PR DESCRIPTION
**Pull request by williamFalcon**

### CODE REVIEW

**Comment by Borda** [comment]
@luiscape could the failed Drone be rather infrastructure issue then code issue?

**Comment by awaelchli** [comment]
It's a bus error. This is caused by hardware as far as I know.

**Comment by luiscape** [comment]
@Borda i checked the error logs on Drone and it reads "Bus error (core dumped)". I found [this](https://github.com/pytorch/pytorch/issues/2244) on the PyTorch tickets which makes me think that it's a memory-related issue. 

Did you try to restart it?

**Comment by awaelchli** [comment]
I had this a few times, it happens randomly. Restarting the job fixes the problem.

**Comment by Borda** [comment]
> @Borda i checked the error logs on Drone and it reads "Bus error (core dumped)". I found [this](https://github.com/pytorch/pytorch/issues/2244) on the PyTorch tickets which makes me think that it's a memory-related issue.
> 
> Did you try to restart it?

As @awaelchli mentioned we see it quite often randomly on several PRs, it may be also connected that in about the same time we upgraded Drone builds from PT 1.4 to 1.5

**Comment by williamFalcon** [comment]
rebased master with the accumulate batches pr and re-running

**Pull request merged**
