### PR TITLE
Add _gpus_arg_default in argparse_utils for backward compatibility

### LINKED ISSUE #7400: Loading a checkpoint that was saved in PL < 1.2 still breaks
## 🐛 Bug

Related Issue/PRs.
- #6549
- #6898
- #7031
- #7043

A checkpoint that was saved in PL < 1.2 with `Trainer.add_argparse_args` **still** breaks, when loaded in PL >= 1.2

```sh
AttributeError: Can't get attribute '_gpus_arg_default' on <module 'pytorch_lightning.utilities.argparse_utils' from 
```

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

```python
import argparse

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import Trainer, LightningModule


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self, **kwargs):
        super().__init__()
        self.save_hyperparameters()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def step(self, x):
        x = self(x)
        out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
        return out

    def training_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def test_step(self, batch, batch_idx):
        output = self(batch)
        loss = self.loss(batch, output)
        return {"y": loss}

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64))

    def val_dataloader(self):
        return DataLoader(RandomDataset(32, 64))

    def test_dataloader(self):
        return DataLoader(RandomDataset(32, 64))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser = Trainer.add_argparse_args(parser)
    args = parser.parse_args()
    model = BoringModel(**vars(args))
    trainer = Trainer.from_argparse_args(args, fast_dev_run=True)
    trainer.fit(model)
    
    # comment the line on >= 1.2.0
    trainer.save_checkpoint('model.pt')
    
    # comment the line below on < 1.2.0
    BoringModel.load_from_checkpoint('model.pt')
```

### Expected behavior

The model should load without any error.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Windows10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.6
 - CUDA/cuDNN version: 11.0 / 8.0.2
 - GPU models and configuration: RTX 3070
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by ryanking13**
## What does this PR do?

Fixes #7400.

`pytorch_lightning/utilities/argparse_utils.py` was renamed to `pytorch_lightning/utilities/argparse.py` at PL 1.2.0.

A checkpoint saved in PL < 1.2 tries to use argparse.utils._gpus_arg_default() which does not exists in PL >= 1.2.0.

```python
# pytorch_lightning/utilities/argparse_utils.py
from pytorch_lightning.utilities.argparse import *
```

The current solution for backward compatibility above does not work since the function starts with an underscore.

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by carmocca — COMMENTED** [review]
I think a better solution is to set

`__all__ = ['_gpus_arg_default']` in pytorch_lightning.utilities.argparse

since this file will be eventually removed

**Comment by ryanking13** [comment]
> I think a better solution is to set
> 
> `__all__ = ['_gpus_arg_default']` in pytorch_lightning.utilities.argparse
> 
> since this file will be eventually removed

I thought of that solution, but the `_gpus_arg_default` is already unused and remains only for backward compatibility.

After the `argparse_utils.py` is removed at v1.4, there will be no other file that imports the function.

**Comment by carmocca** [comment]
> is already unused and remains only for backward compatibility.

I know, but I would say it's nicer to have both things together.

> After the argparse_utils.py is removed at v1.4, there will be no other file that imports the function.

But if we remove this file in v1.4, will a checkpoint created before 1.2 be able to reload? As you said:

> A checkpoint saved in PL < 1.2 tries to use argparse.utils._gpus_arg_default()

**Comment by awaelchli** [comment]
In future versions, before loading the checkpoint we need to monkey patch a dummy function onto the modules where it was used. The fact that this function got pickled into the checkpoints means we will forever have to track changes surrounding that. Horrific. :(

**Review by awaelchli — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by carmocca — APPROVED** [review]

**Comment by ryanking13** [comment]
> But if we remove this file in v1.4, will a checkpoint created before 1.2 be able to reload?

That is the real problem. Both of the solutions won't help when this file is removed.
There should be a monkey patch function as @awaelchli said, which is not easy.

**Pull request merged**
