### PR TITLE
Add initial IPU CI job

### PR DESCRIPTION
**Pull request by kragniz**
This adds an azure-pipelines job targeting the graphcore-ipus worker pool
so we can verify the runners are connected correctly. Since the IPU branch
isn't merged, it won't yet give any actual IPU test coverage.

## What does this PR do?

Related to #3192.

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
just thinking to make it also a new Azure pipeline?

**Comment by kragniz** [comment]
You mean have another file alongside `azure-pipelines.yml` named something like `ipu-pipelines.yml` and manually configure a pipeline in azure to watch it?

**Comment by Borda** [comment]
> You mean have another file alongside `azure-pipelines.yml` named something like `ipu-pipelines.yml` and manually configure a pipeline in azure to watch it?

Yes, but as mentioned just thinking about it and we can group these pipelines to own folder... What do you think?

**Comment by kragniz** [comment]
Yep that sounds good to me, maybe rename the existing one to `.azure-pipelines/pytest.yml` or something. How about moving that into a new folder in a separate PR to keep this one smaller?

**Comment by kragniz** [comment]
Created a patch for that in #7276

**Review by Borda — APPROVED** [review]
lgtm

**Review by awaelchli — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
