### PR TITLE
Pin setup-gcloud to v0 instead of master

### PR DESCRIPTION
**Pull request by sethvargo**
## What does this PR do?

setup-gcloud will be updating the branch name from master to main in
a future release. Even though GitHub will establish redirects, this
will break any GitHub Actions workflows that pin to master. This PR
updates your GitHub Actions workflows to pin to v0, which is the
recommended best practice.

### Does your PR introduce any breaking changes? If yes, please list them.

No

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs) N/A
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs) N/A
- [x] Did you verify new and **existing tests pass** locally with your changes? N/A
- [x] Did you list all the **breaking changes** introduced by this pull request? N/A
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings) N/A

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified 

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by akihironitta — COMMENTED** [review]
LGTM! cc @kaushikb11

**Review by justusschock — APPROVED** [review]

**Review by akihironitta — APPROVED** [review]

**Comment by akihironitta** [comment]
> ci-tests Expected — Waiting for status to be reported

@Borda @kaushikb11 Any idea why CircleCI hasn't started yet?

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by Borda** [comment]
> > ci-tests Expected — Waiting for status to be reported
> 
> @Borda @kaushikb11 Any idea why the CircleCI job hasn't started yet?

not really, just try empty commit

**Review by Borda — APPROVED** [review]

**Comment by akihironitta** [comment]
Labelling P0 since the CI job is failing in master: https://github.com/PyTorchLightning/pytorch-lightning/runs/5655719091?check_suite_focus=true
```
Error: On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name.
```

**Pull request merged**
