### PR TITLE
reorder deprecated Trainer args

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
This is aiming at compatibility issue, as he deprecated some arguments the new placed just below the old ones it will crash for a user who is using positional Trainer setting

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by jeremyjordan** [comment]
>he deprecated some arguments the new placed just below the old ones it will crash for a user who is using positional Trainer setting

do you have a link to an Issue for this? i'm not sure how changing the order will **fix** old code which relies on positional ordering

**Comment by Borda** [comment]
There is no issue for this, just what I observed that in theory may happen...

**Comment by williamFalcon** [comment]
@jeremyjordan @Borda what's the verdict? if anything, i think this makes it less backward compatible haha

**Comment by Borda** [comment]
> @jeremyjordan @Borda what's the verdict? if anything, i think this makes it less backward compatible haha

it is other was around it make is more back-compatible because in past adding the new arg but after the old one shifted all following argument so it was crashing is user was using positional arguments only... but it is a truth that most users use key arguments...

**Pull request merged**
