### PR TITLE
add autopep8 to Contributions guide

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Fixes #53. Adding usage `autopep8` to guidelines

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@hadim ^^ something like this?

**Comment by hadim** [comment]
Looks good to me. Thanks!

**Comment by hadim** [comment]
In my test `autopep8 -v --in-place *.py` seems to be sufficient since it uses the various configurations present within the root folder of the repo.

Also running `autopep8 -v --in-place *.py` brings no modifications on `master` for me (which means that the code is correctly formatted).

**Comment by hadim** [comment]
Actually my command is wrong since it does not process the files... doing more tests now.

**Comment by hadim** [comment]
Here is the correct command: `autopep8 -v -r --in-place .`

**Comment by hadim** [comment]
Running it on `master` modify 3 files:

```
        modified:   pytorch_lightning/loggers/comet.py
        modified:   pytorch_lightning/loggers/neptune.py
        modified:   pytorch_lightning/trainer/trainer.py
```

Edits are minor. Maybe you could include this in the PR.

**Comment by Borda** [comment]
Sure, I have already applied the command as part of this PR but it creates change in the if statement which violate fake8 check...

> Here is the correct command: `autopep8 -v -r --in-place .`

That's better, thx

**Comment by hadim** [comment]
You should be able to ignore specific lines of code with `# noqa` (haven't tested).

**Comment by Borda** [comment]
> You should be able to ignore specific lines of code with `# noqa` (haven't tested).

Sure, we are already using it in deprecated inits, but we shall not use this local fix for systematic issues lol

**Comment by hadim** [comment]
Of course! Only for things that `autopep8` and/or `flake8` don't understand properly.

**Comment by Borda** [comment]
the problem was the if statement was not properly aligned on the next line so `autopep8` fix it but the fix was not correct according to `flake8`...

**Pull request merged**
