### PR TITLE
prune ignore

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

prune ignore file in base testing as we do not use sklearn metrics anymore...

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
you can probably also get rid of the logger ignores.

**Comment by Borda** [comment]
> you can probably also get rid of the logger ignores.

we still have loggers, right?

**Comment by awaelchli** [comment]
Yes, but in testing we have them mocked, so it will work without loggers installed (ci does not install loggers anymore). Maybe just try and revert if it fails :)

**Comment by Borda** [comment]
> Yes, but in testing we have them mocked, so it will work without loggers installed (ci does not install third party loggers anymore). Maybe just try and revert if it fails :)

ok, lets try...

**Review by ydcjeff — APPROVED** [review]

**Review by SeanNaren — APPROVED** [review]

**Pull request merged**
