### PR TITLE
[bug] [docs] Clearer optimizer_step override instructions

### LINKED ISSUE #4452: Training_step outputs not propagated
cc @ananthsub @awaelchli @justusschock
Hi, after updating to version 1.0.4,  i think  below approach seems to be not working as desired

```
def training_step(...):
    return {'loss': loss, 'random_thing': [1, 'a', Tensor(), ...]}

def training_epoch_end(self, training_step_outputs):
    for d in training_step_outputs:
        random_thing = d['random_thing']
```
    
`training_step_outputs` is always empty. On further debugging i find that `training_step` is never getting called, instead this function `training_step_and_backward` is called within `run_training_batch`

Any help appreciated and also apologies if i am making any mistake

_Originally posted by @nazim1021 in https://github.com/PyTorchLightning/pytorch-lightning/pull/3681#issuecomment-719849781_

### PR DESCRIPTION
**Pull request by ananyahjha93**
## What does this PR do?

Need to add a failing test first in the master.

bug: when the user overrides ``optimizer_step()`` function and calls ``optimizer.step()`` without using ``optimizer_closure`` parameter, the code crashes for 2 reasons:

- [accelerator.py's](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/accelerators/accelerator.py#L115) call to optimizer_step is missing the on_tpu=False parameter.
- [training_loop.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L705) passes ``train_step_and_backward_closure`` as optimizer_closure, which is results in not calling training_step if the user overrides optimizer_step() in LightningModule and does not use optimizer.step(closure=optimizer_closure)

Updates the docs to indicate that the user must pass ``optimizer_closure`` param to ``optimizer.step()`` when overriding optimizer_step function. This is required since training_loop.py defines ``train_step_and_backward_closure()`` within ``run_training_batch()``

Fixes #4452, #4447.

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.    
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by ananyahjha93** [comment]
@SeanNaren is adding the test for this.

**Comment by SeanNaren** [comment]
hey @ananyahjha93, I think your bug model script doesn't set TPU cores greater than 1, so TPUAccelerator is never enabled. This is what led to adding `on_tpu=false` in the accelerator, which isn't correct. Here is the fixed script:

```python
import os

from torch.utils.data import DataLoader, Dataset

import pytorch_lightning as pl
from pytorch_lightning.utilities import AMPType

import torch
from pytorch_lightning import LightningModule
import torch_xla.core.xla_model as xm


class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('fake_test_acc', loss)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

    def optimizer_step(
            self,
            epoch,
            batch_idx,
            optimizer,
            optimizer_idx,
            optimizer_closure,
            on_tpu,
            using_native_amp,
            using_lbfgs,
    ) -> None:
        if on_tpu:
            xm.optimizer_step(optimizer, optimizer_args={'closure': optimizer_closure})
        elif self.trainer.amp_backend == AMPType.NATIVE:
            # native amp does not yet support closures.
            # TODO: pass the closure to the step ASAP
            optimizer_closure()
            self.trainer.scaler.step(optimizer)
        elif self.trainer.amp_backend == AMPType.APEX:
            # apex amp does not yet support closures.
            # TODO: pass the closure to the step ASAP
            optimizer_closure()
            optimizer.step()
        else:
            optimizer.step(optimizer_closure)


def test_x(tmpdir):
    num_samples = 10000

    train = RandomDataset(32, num_samples)
    train = DataLoader(train, batch_size=32)

    val = RandomDataset(32, num_samples)
    val = DataLoader(val, batch_size=32)

    test = RandomDataset(32, num_samples)
    test = DataLoader(test, batch_size=32)

    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        max_epochs=1,
        progress_bar_refresh_rate=1,
        tpu_cores=1
    )

    # Train the model ⚡
    trainer.fit(model, train, val)

    trainer.test(test_dataloaders=test)


tmpdir = os.getcwd()
test_x(tmpdir)
```

Also when overriding optimizer_step, we should expect the user override the exact same function method with defaults (as I've done above).

I suggest removing the code changes and keeping documentation fixes in!

**Review by awaelchli — APPROVED** [review]

**Comment by justusschock** [comment]
@ananyahjha93 What do you think if we check if optimizer_step takes a closure and if not manually call it beforehand?

**Comment by tchaton** [comment]
> @ananyahjha93 What do you think if we check if optimizer_step takes a closure and if not manually call it beforehand (like we already do for AMP)?

I think it is a good idea !

**Comment by ananyahjha93** [comment]
@SeanNaren "I think your bug model script doesn't set TPU cores greater than 1, so TPUAccelerator is never enabled. This is what led to adding on_tpu=false in the accelerator, which isn't correct. Here is the fixed script:" - don't understand this, 

when you set ``tpu_cores=1`` in the bug script, the TPU accelerator is enabled which calls ``on_tpu=True``. But without the default ``on_tpu: bool = False`` in the definition of optimizer_step, it will fail since accelerator.py doesn't call ``on_tpu=False`` for optimizer_step. I wouldn't rely on the user getting the exact definition of optimizer_step right (with defaults), when overriding the method.

**Comment by ananyahjha93** [comment]
@tchaton @justusschock I think that might be a good idea, we can have a failing test where optimizer.step() without closure fails to call training_step and then add a fix which makes the test pass.

**Comment by SeanNaren** [comment]
` I wouldn't rely on the user getting the exact definition of optimizer_step right (with defaults), when overriding the method.` ah understood, I thought we would expect the user to define override the optimizer_step with defaults, in that case this fix is fine!

**Comment by SeanNaren** [comment]
PR should be ready to review. There are now no defaults set within the module object, and accelerators are responsible for setting arguments correctly. 

Function definition when overridden do not need to contain defaults anymore.

**Review by rohitgr7 — APPROVED** [review]

**Review by teddykoker — APPROVED** [review]

**Pull request merged**
