### PR TITLE
remove deprecated early_stop_callback

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

remove deprecated `early_stop_callback`

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by rohitgr7 — APPROVED** [review]
Why is it removed BTW?

**Comment by awaelchli** [comment]
@rohitgr7 because the 1) we can't guess the monitor key to use for early stopping, it is better for the user to explicitly set it. 2) there should be only one way to pass in callbacks (via callbacks arg)

**Comment by rohitgr7** [comment]
@awaelchli what about ModelCheckpoint? It's a callback too right?

**Comment by awaelchli** [comment]
yes, but Lightning does checkpoints by default, and if we removed that argument then there would be no way to turn checkpointing off (i.e. `checkpoint_callback=None`)

**Comment by chrismaliszewski** [comment]
So, should one pass ModelCheckpoint inside callbacks or still via checkpoint_callback?

**Comment by awaelchli** [comment]
sorry, missed your question. 
Via callbacks list is the preferred way for all callbacks. Passing ModelCheckpoint in to callbacks "should" already work on the latest master branch. However there are some edge cases we need to sort out with this usecase.
I personally recommend still using checkpoint_callback until ~v1.1.

**Pull request merged**
