### PR TITLE
clarify batch hooks

### LINKED ISSUE #1440: More granular callbacks
### Motivation

I am currently implementing #765 (make progress bar into a callback) and I need additional callback methods to do this.

### Pitch

introduce these new callback methods:

- `on_train_batch_start` (currently named `on_batch_start`)
- `on_train_batch_end` (currently named `on_batch_end`)
- `on_val_batch_start`
- `on_val_batch_end`
- `on_test_batch_start`
- `on_test_batch_end`

and make `on_batch_start` run on any of the above `*_start` (same for `on_batch_end`)

Further suggestions:
- introduce `on_train_epoch_start`, `on_val_epoch_start`, `on_test_epoch_start` and corresponding `*_end` methods.

### Alternatives

Keep as is, but I don't know how to implement the  progress bar callback otherwise for validation/test updates.

### PR DESCRIPTION
**Pull request by williamFalcon**
Fixes #1440

### CODE REVIEW

**Comment by awaelchli** [comment]
:rocket: Nice to see this uniformity! Makes much more sense to have it named like this (have asked for this previously in #1440). :smiley:

**Comment by williamFalcon** [comment]
:)

**Comment by williamFalcon** [comment]
@awaelchli i like your suggestion here as well:
on_batch_start

But i think this will break too many things haha. How about that in a few releases?

**Comment by awaelchli** [comment]
Yes agree, this can't be made backward compatible! It would need a big warning. I wasn't sure how useful it is in the end. I am very happy with the hooks we have so far :)

**Comment by Borda** [comment]
shall we add deprecation tests and "ToDo" to simplify future removal... ?

**Comment by williamFalcon** [comment]
yes. go for it!

**Pull request merged**
