### PR TITLE
Join Horovod workers at the end of trainer.fit() to prevent race conditions following training

### PR DESCRIPTION
**Pull request by tgaddair**
See: https://github.com/PyTorchLightning/pytorch-lightning/pull/1718#issuecomment-626986292

### CODE REVIEW

**Comment by awaelchli** [comment]
oh, I did not know it auto merges. Shouldn't there be a confirm button?

**Comment by Borda** [comment]
so be careful when you approve anything lol, there is a rule to merge all if tests pass and collect three approvals...

**Comment by williamFalcon** [comment]
lol. i moved those importa up bc they were failing flake8. but now they are at the bottom and flake passes?? @Borda

**Comment by Borda** [comment]
> lol. i moved those importa up bc they were failing flake8. but now they are at the bottom and flake passes?? @Borda

yes, there was added ignore, the case was with new `flake8` it started to check all warnings/error... before `flake8` raised the most important one...

**Comment by tgaddair** [comment]
> I was requested for review but can only accept with low confidence.
> I don't understand why the order of warning/import would cause a race condition.
> 
> Generally I would add a test for every bug fix to ensure it does not get re-introduced in the future, but not sure what to suggest here.
> 
> otherwise looks ok to me :)

Just to clarify, the race condition fix line is here: https://github.com/PyTorchLightning/pytorch-lightning/pull/1786/files#diff-d673a98c14aa5cd59610bcc447178852R631.  The other lines were introduced to make tests pass.

**Comment by williamFalcon** [comment]
awesome haha. I was commenting on our over-zealous flake8 haha :)

**Pull request merged**
