### PR TITLE
Remove `Strategy.on_tpu` property

### PR DESCRIPTION
**Pull request by ananthsub**
## What does this PR do?

Part of #10416 

Reasons for removal:
- This can be deduced from the `root_device` property. The property `on_tpu` is redundant yet it's also an `abstractmethod`. Requiring every strategy class to implement this is boilerplate.
- We don't offer `on_ipu` or `on_X` for existing accelerator implementations
- Given the Accelerator is also customizable/pluggable, the pattern of offering `on_gpu` and `on_tpu` flags doesn't scale.

### Does your PR introduce any breaking changes? If yes, please list them.

Yes: removes the `on_tpu` property from the Strategy base class.
Reason: The strategy is still an experimental API, and this is part of making it stable

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by kaushikb11 — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Comment by four4fish** [comment]
+1 for this change.

**Comment by four4fish** [comment]
We have

**Comment by four4fish** [comment]
+1 to this change. I realized the on_tpu is not actually used anywhere, only in tests. Other than on_tpu(), the _XLA_AVAILABLE check is only used at import time. Should we have device_availablity check at X_accelerator initialization time?

**Comment by ananthsub** [comment]
> +1 to this change. I realized the on_tpu is not actually used anywhere, only in tests. Other than on_tpu(), the _XLA_AVAILABLE check is only used at import time. Should we have device_availablity check at X_accelerator initialization time?

@kaushikb11 what do you think^?

In general I am in favor of those checks running as early as possible to avoid wasting users' time. In the GPU accelerator, we do check this here: https://github.com/PyTorchLightning/pytorch-lightning/blob/f41d1e5e5ebb7040a39d137695e818cada9a9234/pytorch_lightning/accelerators/gpu.py#L36-L44

But we don't assert that cuda is available - should we?
And should we do that at the init time vs in `setup_environment` ? 

@four4fish Would this also simplify the accelerator connector initialization logic?

**Comment by four4fish** [comment]
@ananthsub @kaushikb11 I think we can introduce a new function called _device_check() in X_Accelerator, which will be called by accelerator_connector right after accelerator initialization. 
We don't have consistent device availibliies check in neither accelerator class, strategies class nor accelerator_connector at this point, so I introduced it in the [new accelerator_connector rewrite ](https://github.com/PyTorchLightning/pytorch-lightning/blob/4ee369dcc90f57ec6746f9f4f24dc5380ebe9896/pytorch_lightning/trainer/connectors/accelerator_connector_new.py#L160-L162). But it's not ideal, I think it's a better fit in accelerator API.

**Comment by kaushikb11** [comment]
@four4fish @ananthsub I agree. We could add `device_check` functionality in the Accelerator Class. I had planned to add it after starting to work on #10687

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
