### PR TITLE
Fix Multi-GPU join for horovod

### LINKED ISSUE #6935: Resolve several Horovod test failures
## 🐛 Bug

We are currently skipping several Horovod tests. We should eventually address each one.

- [ ] Coverage issue: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L52
- [ ] Unclear feature: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L154-L156
- [x] Flaky test on ubuntu 1. Produces a [segfault](https://github.com/PyTorchLightning/pytorch-lightning/runs/2305849946#step:15:772): https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L243
- [x] Flaky test on ubuntu 2. Produces a segfault: https://github.com/PyTorchLightning/pytorch-lightning/blob/9402c052ed5a8acddce1b3afaafa5c881ed0c207/tests/models/test_horovod.py#L380
- [ ] Permissions issue 1: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L276
- [ ] Permissions issue 2: https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L326

cc: @Borda @tgaddair

### PR DESCRIPTION
**Pull request by irasit**
Horovd's join required local rank as argument for multi-gpu cases, code [here](https://github.com/horovod/horovod/blob/master/horovod/torch/mpi_ops.py#L882) 
The default join only works for cpu.

~Partly fixes #6935~
edit: does not seem like any skipped tests were fixed

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Comment by awaelchli** [comment]
Thanks for the fix <3
 I wonder if this solves any of the existing tests that we currently skip 
See #6935 for a list.

**Comment by irasit** [comment]
> Thanks for the fix <3
> I wonder if this solves any of the existing tests that we currently skip. We should try to undo the skip for some of these cpu tests to see if your PR resolves that.
> See #6935 for a list.

I do not think it related to the skip test, but seems related to [this one](https://github.com/PyTorchLightning/pytorch-lightning/blob/b9475c1ae913b647c18cbf5f445c53c2f793a7f5/tests/models/test_horovod.py#L118), seems the issue is not caught by this test before. 
The issue is reproducible in [my test ](https://github.com/horovod/horovod/pull/2713/files#diff-f637ce6e6549311fed853c9be4b4cebe297cb03c0518be3541375fa9d3a2d13e) where petastorm reader and spark estimator is used.

**Review by Borda — COMMENTED** [review]
shall we reenable Horovod tests back?

**Review by awaelchli — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM ! Thanks for your contribution.

**Pull request merged**
