### PR TITLE
Docs: upgrade packages

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

it turned out that some of our used docs plugins are not compatible with actually used Sphinx 2.x
so this is updating Sphinx to 3.x and pin some other related doc plugins

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
we couldn't upgrade sphinx before because one of the extensions was not yet ready with 3.0, but this seems to be resolved now. Looks good!

**Comment by ydcjeff** [comment]
Shall we also fix this?
```py
/home/docs/project/docs/source/conf.py:280: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript('copybutton.js')
```

**Comment by Borda** [comment]
> Shall we also fix this?
> 
> ```python
> /home/docs/project/docs/source/conf.py:280: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
>   app.add_javascript('copybutton.js')
> ```

well, this is linked to the package we are using, or do you have any idea how to fix it?

**Comment by ydcjeff** [comment]
Replace below
https://github.com/PyTorchLightning/pytorch-lightning/blob/e1c152b13c60f064a312f97ad0e326319bfda047/docs/source/conf.py#L281
with
```py
app.add_js_file('copybutton.js')
```
Since it's not in the changes, I can't make suggestion.

**Review by rohitgr7 — APPROVED** [review]
is mergify bot re-enabled?? ^^^^

**Review by ydcjeff — APPROVED** [review]

**Comment by Borda** [comment]
> Since it's not in the changes, I can't make suggestion.

completely right, just overlooked is I was a bit multitasking :D

**Review by s-rog — APPROVED** [review]

**Review by tchaton — APPROVED** [review]

**Pull request merged**
