### PR TITLE
diable val and test shuffling

### PR DESCRIPTION
**Pull request by williamFalcon**
Fixes part of #1551

### CODE REVIEW

**Comment by williamFalcon** [comment]
Need to request .shuffle in the dataloader

**Comment by awaelchli** [comment]
If shuffle is set to True, the DataLoader will set the RandomSampler, so as an alternative, we could check if `isinstance(dataloader.sampler, RandomSampler)`.

**Comment by williamFalcon** [comment]
@awaelchli ahhh there it is haha. good catch.

**Comment by Borda** [comment]
@williamFalcon check update

**Pull request merged**
