### PR TITLE
Add ModelSummary support for RichProgressBar

### PR DESCRIPTION
**Pull request by kaushikb11**
## What does this PR do?

Fixes #\<issue_number>

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by ananthsub — COMMENTED** [review]
Can you file an issue to track these new features?
- It sets a good example for new contributors around how contributions can be made to the project
- It's easier for people to provide feedback around the design on an issue compared to directly reviewing the PR
- The issue can be tracked in the sprint/project plans

cc @tchaton 

I raise this because I disagree with the approach here. I do not think we should be touching the `summarize` API to special case the Rich extension. Would we add yet another argument to `summarize` to support a different visualization scheme? That doesn't make sense to me 

Instead, why don't we offer a RichModelSummary callback (as laid out here: https://github.com/PyTorchLightning/pytorch-lightning/issues/9043) and let users configure this with the Trainer?

**Comment by kaushikb11** [comment]
@ananthsub Those are good points. As it was related to the `RichProgressBar` feature and has been decoupled into a separate PR, the feature was already part of the sprint plan. Anyway, creating a new issue to discuss a design change would be the ideal way to go.

Going through the linked Github issue, will add my comments there. Thank you for your feedback!

**Comment by tchaton** [comment]
Hey @kaushikb11, @ananthsub,

Thanks for pointing this out @ananthsub. Let's make sure every new PR is tracked by an issue.

Also, I agree with Ananth there, the ModelSummary shouldn't own the rich printing.

Option 1 would be to enable a function to be passed to specify how to print the summary.  

```py

def summary_terminal_display(arrays, total_parameters, trainable_parameters, model_size):
    ...

class ModelSummary

    def __init__(
        self,
        model,
        mode: Optional[str] = None,
        max_depth: Optional[int] = 1,
        summary_terminal_display: Optional[Callable] = None
    )
        ...

        self.summary_terminal_display = summary_terminal_display


    def summarize(self):


        if self.summary_terminal_display:
            summary_terminal_display(...)

in callback_connector

ModelSummary(..., trainer.progress_bar_callback.summary_terminal_display)
```

Option 2 would be for the ModelSummary to print on summarize and just provide the data to be logged, this would be passed to the progress bar.

Best,
T.C

**Comment by kaushikb11** [comment]
Hi @tchaton, we are taking a different approach! Closing this PR.

We have merged `ModelSummary` callback last week. We will subclass it and create a `RichModelSummary` callback and override the `summarize` method

Reference: https://github.com/PyTorchLightning/pytorch-lightning/commit/490a49340d2e963382fdc2aa0d7e554263103d15

**Pull request closed without merging**
