### PR TITLE
Validation Steps fullEpoch added for Clarity

### LINKED ISSUE #3164: Validation Step for Epoch Clarified
## 🚀 Feature

This simple change would add the `num_validation_sanity_steps` flag to also include `fullEpoch` in addition to the synonymous `-1` flag, to add clarity to the end-user. 

### Motivation
I grew frustrated with trying to find a way to easily run an entire validation epoch before using training loops in pytorch-lightning. After finding this parameter (https://github.com/PyTorchLightning/pytorch-lightning/pull/2246), I still did not like how the `-1` flag works. This also confused a colleague of mine, so I decided to submit this change as a means to add clarity to the end-user.

### Pitch
Allow `-1` and `fullEpoch` flags to run the validation sanity step on an entire batch prior to training

### Pull Request
https://github.com/PyTorchLightning/pytorch-lightning/pull/3166

### PR DESCRIPTION
**Pull request by dulayjm**
## What does this PR do?

Fixes #3164 

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by dulayjm** [comment]
Issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/3164

**Comment by williamFalcon** [comment]
thanks for the PR! mind waiting a week until we finish refactors?

**Comment by dulayjm** [comment]
That works for me, thanks!

**Review by Borda — CHANGES_REQUESTED** [review]
you have mixed with master (merged master to your branch), pls rebase master

**Comment by rohitgr7** [comment]
I don't think this is required. Everything is clearly mentioned in the docs.
https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.trainer.html#num-sanity-val-steps

**Comment by Borda** [comment]
@dulayjm mind sending another PR starting from the actual master, this was a bit hard...

**Comment by dulayjm** [comment]
Sure, sorry about that

**Pull request closed without merging**
