### PR TITLE
move to Pages dir

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

move docs pages to separate folders so it does not interfere with generated and moved files

so now the sub-folder structure is (basically follows the structure in index)
- advanced
- benchmarking
- clouds
- ecosystem
- extensions
- common
- starter

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:  

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
the failing mypy test on horovod file is unrelated...

**Comment by SeanNaren** [comment]
Big fan of this! I always was curious why we didn't opt for a sub-dir pattern (I assume we didn't initially and just continued onwards!).

**Comment by Borda** [comment]
> Big fan of this! I always was curious why we didn't opt for a sub-dir pattern (I assume we didn't initially and just continued onwards!).

Exactly, so mind approve if you like it?

**Review by SeanNaren — APPROVED** [review]

**Review by ydcjeff — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Review by williamFalcon — APPROVED** [review]

**Comment by Borda** [comment]
@awaelchli, @edenlightning, @tchaton, @justusschock, @teddykoker mind review? 🐰

**Review by justusschock — APPROVED** [review]

**Review by tchaton — APPROVED** [review]

**Comment by Borda** [comment]
@awaelchli mind review, seems you are the last remaining code-owner here :]

**Review by edenlightning — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]
@Borda why are warnings not treated as errors anymore? Even on 1.2 dev branch we get 195 warnings

**Comment by Borda** [comment]
> @Borda why are warnings not treated as errors anymore? Even on 1.2 dev branch we get 195 warnings

what warnings, I do not see any https://github.com/PyTorchLightning/pytorch-lightning/pull/4869/checks?check_run_id=1771248207
maybe update packages?

**Pull request merged**
