### PR TITLE
Model summary: add 1 decimal place

### PR DESCRIPTION
**Pull request by jonashaag**
## What does this PR do?

Show 1999 parameters as 1.9 K and 1000 parameters as 1.0 K, rather than both as 1 K.

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In in short, see following bullet-list:  

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by edenlightning** [comment]
mind adding a test for this?

**Comment by jonashaag** [comment]
The docs are the tests :) but I can add more tests if the feature is accepted.

**Comment by awaelchli** [comment]
@jonashaag the doctest is sufficient, you just need to fix the decimal point in the other places where the model summary string is tested.

**Review by Borda — COMMENTED** [review]
it is a good point to show decimal when there is only 1 digit but later when you have thousands the meaning of decimal is meaningless >> 5,000.0

**Comment by jonashaag** [comment]
I can add a special case for T if you want

**Comment by Borda** [comment]
> I can add a special case for T if you want

I would say whatever is above 100 does not need decimal and lower than 100 shows one decimal

**Comment by jonashaag** [comment]
OK, please review again.

**Review by Borda — APPROVED** [review]
nice, thx :]

**Review by tchaton — CHANGES_REQUESTED** [review]
Great addition ! Would you mind adding a test ?

**Comment by jonashaag** [comment]
As said, the tests are in the docs (doctest) but if you want I can add separate unit tests.

**Review by tchaton — APPROVED** [review]

**Review by SeanNaren — APPROVED** [review]

**Pull request merged**
