### PR TITLE
Add GitHub Actions build

### LINKED ISSUE #707: Investigate using Github CI
## 🚀 Feature
Experiment with novel Github CI - action

### Motivation
having builds for all main os in single CI, so we can drop Travis and Appveyo 
We would keep CircleCI for future GPU testing...

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Fixes #707. it runs all os in one place and it seems to be even faster, around 6min compare to previous solutions has build time around 10min... it cal also generate a badge CI testing
With this CI we would drop Travis and Appveyor :]
- Travis is recently changing his os images and debugging is painfull
- Appveyort prefer only one concurrency job so we are not testing almost anything

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
as a follow-up to this, we would add the new badge to readme and drop Travis and Appveyor...

**Comment by Borda** [comment]
over all the complete built for 12 envs took only 10min

**Comment by williamFalcon** [comment]
@Borda do we still need this after the travis fix?

**Comment by Borda** [comment]
it is faster and we have larger coverage of test for all major OS, python 3.6 & 3.7 and both minimal and lates requirements...
in past we had:
- linux, for py36 + py37 for min + latest requirements
- osx, for py37 for any (latest) requirements
- win, for py36 + py37 for any (latest) requirements

with this one we have:
- linux, for py36 + py37 for min + latest requirements
- osx, for py36 + py37 for min + latest requirements
- win, for py36 + py37 for min + latest requirements

moreover, it not for fist time when Travis changed something and our test start to crashing without any obvious reason... which is not very convenient... also having two different Ci platforms

**Comment by williamFalcon** [comment]
@Borda ok. can you submit a PR with the new badge?

**Pull request merged**
