### PR TITLE
[make] Create Makefile

### PR DESCRIPTION
**Pull request by ydcjeff**
## What does this PR do?

Creates Makefile

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In in short, see following bullet-list:  

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — COMMENTED** [review]
can we update Contribution accordingly and remove the single test script
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#testing

**Comment by ydcjeff** [comment]
Okay @Borda 
Any commands to add?
If we want to add flake8, isort, etc, we can add here then we don't need pre-commit anymore...

**Comment by Borda** [comment]
> Any commands to add?
> If we want to add flake8, isort, etc, we can add here then we don't need pre-commit anymore...

lest add just this one in this PR and propagate it in the repo, meaning rm the old script and update instructions in contribution :]

**Review by s-rog — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
Great PR !

**Pull request merged**
