### PR TITLE
WIP: Fix non-tensor scalar result aggregation

### LINKED ISSUE #2143: Fix checkpoint warning for floats
#1819 added this warning when saving checkpoints. https://github.com/PyTorchLightning/pytorch-lightning/blob/bd49b07fbba09b1e7d8851ee5a1ffce3d5925e9e/pytorch_lightning/callbacks/model_checkpoint.py#L259-L263

1. Is there a reason why native Python floats aren't supported? I think it's actually quite common especially when libraries e.g. scipy are involved when computing the metrics.
2. It says checkpoint not saved, but actually checkpoints are still saved. This check doesn't actually change the saving logic besides giving that warning.

### LINKED ISSUE #2636: nan metric breaking ModelCheckpoint
## 🐛 Bug

Comparing any numbers to `float('nan')` is `False` in Python so as a result if a _non-loss_ metric score is `nan` initially in training, then callback cannot checkpoint any scores after. 

### Expected behavior

Ignore a `nan` metric score. This is orthogonal to when grad or weights become `nan`.

### Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: Tesla V100

### Additional context

Previous issue wasn't addressed completely #1008

### LINKED ISSUE #3276: Logging non-tensor scalar with result breaks subsequent epoch aggregation
## 🐛 Bug
Logging non-tensor scalar with result breaks subsequent epoch/tbptt aggregation
(on both 0.9 and master)

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/accelerators/ddp_spawn_backend.py", line 165, in ddp_train
    results = self.trainer.run_pretrain_routine(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in run_pretrain_routine
    self.train()
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 396, in train
    self.run_training_epoch()
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 543, in run_training_epoch
    self.run_training_epoch_end(epoch_output, checkpoint_accumulator, early_stopping_accumulator, num_optimizers)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 672, in run_training_epoch_end
    epoch_log_metrics, epoch_progress_bar_metrics = self.__auto_reduce_results_on_epoch_end(epoch_output)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 696, in __auto_reduce_results_on_epoch_end
    tbptt_outs = tbptt_outs[0].__class__.reduce_across_time(tbptt_outs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/step_result.py", line 392, in reduce_across_time
    result[k] = tbptt_reduce_fx(value)
TypeError: mean(): argument 'input' (position 1) must be Tensor, not list
```

### To Reproduce
```
    def training_step(self, batch, batch_idx):
        x, y = batch[0], batch[1]
        x = self.forward(x)
        loss = self.loss(x, y)
        result = pl.TrainResult(loss)
        result.log("non tensor scalar", 1.0)
        result.log("loss", loss, on_step=False, on_epoch=True)
```
### To Fix
```
result.log("non tensor scalar", torch.tensor(1.0))
```
### Expected behavior
In `log()` of result objects, value should accept non tensor values as `value: Any` and not cause issues with other metrics to be logged

### Additional context
`log()` can be changed to only accept tensors, or have a built-in conversion, will update as I investigate further

### PR DESCRIPTION
**Pull request by s-rog**
## What does this PR do?

Fixes #3276
Fixes #2636
Resolves #2143

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

## Todo
~ddp sync for converted tensors?~
~convert in `log` or `__set_meta`?~
~write test(s)~
fix tests

### CODE REVIEW

**Comment by s-rog** [comment]
@justusschock any thoughts on the first two entries in my todo above?

**Comment by justusschock** [comment]
@s-rog I'd say convert ASAP and maybe the ddp_sync should come automatically with that

**Comment by s-rog** [comment]
@justusschock gotcha, I just put it there for now to maintain current (no) syncing behavior, update to come

**Comment by s-rog** [comment]
I'm trying to figure out why the code path is different for `results` between tests and examples, as the changes fixes the issue correctly in examples but not in tests.

**Comment by edenlightning** [comment]
@williamFalcon any advice?

**Comment by Borda** [comment]
fixed in #3855

**Pull request closed without merging**
