### PR TITLE
Skip horovod 0.24.0 only

### LINKED ISSUE #12209: horovod installation fails in docker build CI
## 🐛 Bug
The following jobs are failing in master due to the failure in installing horovod.
```
build-CUDA (3.7, 1.8)
build-Conda (3.8, 1.7)
build-Conda (3.8, 1.8)
build-Conda (3.8, 1.9)
build-Conda (3.8, 1.10)
```

```
#8 331.1 × Encountered error while trying to install package.
#8 331.1 ╰─> horovod
```

Full log here: https://gist.github.com/akihironitta/ee8f5895d444e918ce825562e1e00402

### To Reproduce
e.g.
```bash
docker buildx build --build-arg PYTHON_VERSION=3.7 --build-arg PYTORCH_VERSION=1.8 --file dockers/base-cuda/Dockerfile .
```

### Expected behavior
horovod is installed successfully.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Fixes #12209.

follow-up for https://github.com/horovod/horovod/issues/3449

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @tchaton @rohitgr7 @akihironitta @carmocca

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Review by kaushikb11 — APPROVED** [review]

**Comment by krshrimali** [comment]
@Borda - A quick question, is this PR supposed to fix the existing CI failures? (I see 5 tests failing, but I'm not sure if this PR was intended to fix them...). My question shouldn't block merging this PR if you feel it's good to go 🚀

**Comment by Borda** [comment]
> you set `HOROVOD_BUILD_CUDA_CC_LIST=$TORCH_CUDA_ARCH_LIST`
> but your `TORCH_CUDA_ARCH_LIST` has an invalid format for the Horovod build

thank you, that shall be fixed now, also updated `cmake` as needed, but still failing the build :/

**Comment by maxhgerlach** [comment]
This is from  **Docker / build-Conda (3.8, 1.8) (pull_request) Failing after 21m — build-Conda (3.8, 1.8)** https://pipelines.actions.githubusercontent.com/8vY1hLunpxmXHOOjnxk4T2akXjPKdiG2jHSABcGIXOHjLPuuGK/_apis/pipelines/1/runs/519734/signedlogcontent/2?urlExpires=2022-03-10T10%3A20%3A44.4995001Z&urlSigningMethod=HMACV1&urlSignature=6ll3k8AlImNSsjhRwTG%2FfjN3OJn5hZSqCtYxLAH6BlA%3D
```
2022-03-09T12:18:26.6646973Z #14 366.5       Traceback (most recent call last):
2022-03-09T12:18:26.6649474Z #14 366.5         File "<string>", line 1, in <module>
2022-03-09T12:18:26.6650279Z #14 366.5         File "/tmp/pip-install-bnnjykp5/horovod_1bcf363b33024ee5b3fc2d26d0a311a4/cmake/build_utils.py", line 111, in get_nvcc_flags
2022-03-09T12:18:26.6654824Z #14 366.5           cc_list = full_cc_list if cc_list_env is None else [int(x) for x in cc_list_env.split(',')]
2022-03-09T12:18:26.6658007Z #14 366.5         File "/tmp/pip-install-bnnjykp5/horovod_1bcf363b33024ee5b3fc2d26d0a311a4/cmake/build_utils.py", line 111, in <listcomp>
2022-03-09T12:18:26.6661260Z #14 366.5           cc_list = full_cc_list if cc_list_env is None else [int(x) for x in cc_list_env.split(',')]
2022-03-09T12:18:26.6664234Z #14 366.5       ValueError: invalid literal for int() with base 10: '3.7'
```
Apparently some other invalid value was plugged into `HOROVOD_BUILD_CUDA_CC_LIST`. It should be a comma-separated list of integers. Is `3.7` some Python version identifier that slipped in there somehow? 🙂

**Comment by Borda** [comment]
> Apparently some other invalid value was plugged into `HOROVOD_BUILD_CUDA_CC_LIST`. It should be a comma-separated list of integers. Is `3.7` some Python version identifier that slipped in there somehow?

let me understand what is the `HOROVOD_BUILD_CUDA_CC_LIST`... is it CUDA arch or CUDA major version?

**Comment by maxhgerlach** [comment]
Ah, this is confusing!

HOROVOD_BUILD_CUDA_CC_LIST wants to see the compute capability versions formatted as integers so they can be passed into the `-gencode` argument to `nvcc`. Examples are here: https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list

I've only ever dealt with these integer numbers XY, but as I see now in reference docs they list them as X.Y -- https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities

I think just dropping the `.` from `3.7` could satisfy the Horovod build.

**Comment by Borda** [comment]
> I think just dropping the `.` from `3.7` could satisfy the Horovod build.

let me try, but in past, the dot notation was valid as these env variables were set by @tgaddair

**Comment by Borda** [comment]
Falling TPU is unrelated and the CUDA build will be fixed later

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by Borda** [comment]
@kaushikb11 any idea why the TPU tests are failing?

**Comment by akihironitta** [comment]
@maxhgerlach Thank you very much for your help!

**Pull request merged**
