### PR TITLE
Fix documentation error

### PR DESCRIPTION
**Pull request by ctlaltdefeat**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes error in documentation, method ```test_end``` should refer to ```test_loss``` rather than  ```val_loss```

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
personally I would wait with any documentation updates/fixes until #521 is resolved, otherwise, these changes will be almost impossible to track back and apply so they will be lost... :cry:

**Comment by Borda** [comment]
@ctlaltdefeat could you update your fix to the actual master

**Comment by ctlaltdefeat** [comment]
Is there a way to rebase to head from Github's web interface?

**Comment by Borda** [comment]
I have never tried it from web, but note that the documentation moved to the code...

**Comment by williamFalcon** [comment]
@ctlaltdefeat mind rebasing?

**Comment by williamFalcon** [comment]
@ctlaltdefeat can you make changes to new docs?

**Pull request closed without merging**
