### PR TITLE
Missing training_step outputs in training_epoch_end

### PR DESCRIPTION
**Pull request by mmiakashs**
Possible bug fix of #2320

### CODE REVIEW

**Comment by williamFalcon** [comment]
@mmiakashs mind trying master now? the solution in this PR wasn't quite 100% right and needed more testing

**Comment by Borda** [comment]
> This PR is likely not needed anymore but we need to add you as co-author to #2328 @Borda

to be done, this PR shall be merged to the other PR, but as this is closed and the other merged, there is nothing to do... pls ping me next time before close/merge :rabbit:

**Comment by williamFalcon** [comment]
yes... but this PR was incorrect

**Comment by mmiakashs** [comment]
> @mmiakashs mind trying master now? the solution in this PR wasn't quite 100% right and needed more testing.
> 
> This PR is likely not needed anymore but we need to add you as co-author to #2328 @Borda

@williamFalcon Thanks a lot for the PR. One confusion: I just noticed that all the training_step end log metrics are combined with the dict key named `'log_metrics'`, however, the validation log metrics are combined with the dict key named `'log'`. Is this variation intentional?

**Comment by mmiakashs** [comment]
@williamFalcon I debug again and found out that the issue [#2320](https://github.com/PyTorchLightning/pytorch-lightning/issues/2320) still occurred only for training_step outputs. training_step outputs for the first optimizer iteration are missing, however, the second optimizer iteration outputs are merged properly.

**Comment by Borda** [comment]
@mmiakashs do you see a fix for it, mind send a PR?

**Pull request closed without merging**
