### PR TITLE
Mock packages for RTD docs build (follow up to doctests)

### PR DESCRIPTION
**Pull request by awaelchli**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Doc build on RTD is broken since #1511 because I mistakenly removed the mocking of some packages. Packages should be mocked because we don't want to install them on RTD server. 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
@Borda I think this should fix it. Could you set RTD build to this branch?

**Comment by Borda** [comment]
> I think this should fix it. Could you set RTD build to this branch?

https://readthedocs.org/projects/pytorch-lightning/builds/10974678/

**Comment by awaelchli** [comment]
Everything seems to be there and links are working again.

**Comment by Borda** [comment]
> Everything seems to be there and links are working again.

well, it was passing even before so not sure what you were referring as failing...

**Comment by awaelchli** [comment]
> well, it was passing even before so not sure what you were referring as failing...

I don't know why it said "build successful" but all links are grayed out and pages are missing, see latest master build:
https://pytorch-lightning.readthedocs.io/en/latest/lightning-module.html

but now on this branch, it's back to normal.

**Comment by Borda** [comment]
this is the link to see resulting docs - https://pytorch-lightning.readthedocs.io/en/docs-mockrtd
have you checked the docs preview in CircleCI artefacts?

**Comment by awaelchli** [comment]
Yes everything looks good now. Artifacts in circle ci, RTD build and locally. The missing pages are back and links are working again. The mocking definitely fixed the issue.

**Pull request merged**
