### PR TITLE
[docs]: add newline to correctly render Example

### PR DESCRIPTION
**Pull request by msarmi9**
## What does this PR do?

Fixes small error in docs preventing an Example from rendering correctly.

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [X] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [X] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [X] Is this pull request ready for review? (if not, please submit in draft mode)
 - [X] Check that all items from **Before submitting** are resolved
 - [X] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by ananthsub — CHANGES_REQUESTED** [review]
thanks for working on this @msarmi9 ! Could you run `pre-commit` to ensure the CI formatting tests pass?

**Comment by awaelchli** [comment]
The author's repository/branch disappeared. We can't make further changes here. Resubmitted here #7064

**Comment by msarmi9** [comment]
@awaelchli Whoops! Really sorry about that. Forgot about this PR and deleted my fork because I had another patch merged in.🤦‍♂️

**Comment by awaelchli** [comment]
No worries. Thanks for your contribution :)

**Pull request closed without merging**
