### PR TITLE
Add torch v1.11.0 to the list of versions in adjust_versions.py

### LINKED ISSUE #9676: 3 Docker CI jobs failing on master
## 🐛 Bug

These are the failing jobs:
* build-XLA (3.7, nightly)
   - link: https://github.com/PyTorchLightning/pytorch-lightning/runs/3693387242
   - error: `ValueError: Missing 1.11.0 in [{'torch': '1.10.0', 'torchvision': '0.11.*', 'torchtext': ''}, {'torch': '1.9.1', 'torchvision': '0.10.1', 'torchtext': '0.10.1'}, {'torch': '1.9.0', 'torchvision': '0.10.0', 'torchtext': '0.10.0'}, {'torch': '1.8.2', 'torchvision': '0.9.1', 'torchtext': '0.9.1'}, {'torch': '1.8.1', 'torchvision': '0.9.1', 'torchtext': '0.9.1'}, {'torch': '1.8.0', 'torchvision': '0.9.0', 'torchtext': '0.9.0'}, {'torch': '1.7.1', 'torchvision': '0.8.2', 'torchtext': '0.8.1'}, {'torch': '1.7.0', 'torchvision': '0.8.1', 'torchtext': '0.8.0'}, {'torch': '1.6.0', 'torchvision': '0.7.0', 'torchtext': '0.7'}]`

* build-CUDA (3.7, 1.6)
   - link: https://github.com/PyTorchLightning/pytorch-lightning/runs/3693385716
   - error: `Downloading matplotlib-3.1.2.tar.gz Error: The action has timed out.`

* build-CUDA (3.9, 1.9)
   - link: https://github.com/PyTorchLightning/pytorch-lightning/runs/3693385768
   - error: `Downloading matplotlib-3.1.2.tar.gz Error: The action has timed out.`

### To Reproduce

check latest CI jobs on master

### Expected behavior

Green CI!

### PR DESCRIPTION
**Pull request by daniellepintz**
## What does this PR do?
Fixes a broken CI job, caused by new nightly version of Pytorch, v1.11 

Fixes #9676

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Review by awaelchli — APPROVED** [review]

**Comment by daniellepintz** [comment]
We are seeing similar CI failures to #9676, now more widespread across `CI build Docker` jobs

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by Borda** [comment]
@daniellepintz this is irrelevant since you drop these devel runs from CI =D

**Comment by daniellepintz** [comment]
@Borda I don't see how it's irrelevant, there are 6 new failures from this PR :/ I think we have to fix before merging

**Review by Borda — APPROVED** [review]

**Comment by daniellepintz** [comment]
Merging since there are similar failures on the last merged PR #9612

**Pull request merged**
