### PR TITLE
Set warnings : Unify epoch numbers to be zero-based : #675

### LINKED ISSUE #675: Mismatch of displayed 'epoch'
## 🐛 Bug

The display of epoch's number mismatches between the progress bar and the checkpoint indicator. I wonder this mismatch could confuse users.

- progress bar: The number of epochs starts from 1.
- checkpoint indicator: The number of epochs starts from 0.
- metrics.csv also starts from 0.

I think that to change checkpoint and metrics.csv causes a serious problem.
So progress bar should be changed in my opinion.

What do you think about it?

```
Epoch 32: 100%|██████████| 331/331 [00:05<00:00, 88.73batch/s, batch_idx=17, loss=1.148, train_batch_loss=1.02, v_num=0, val_loss=1.05]
AINFO:root:
Epoch 00031: val_loss reached 1.04545 (best 1.04545), saving model to /dummy/version_0/checkpoints/_ckpt_epoch_31.ckpt as top 1
{'loss': 1.022357702255249, 'train_batch_loss': 1.022357702255249, 'val_loss': 1.0454469919204712}
Epoch 33:   5%|▌         | 18/331 [00:00<00:05, 61.06batch/s, batch_idx=17, loss=1.073, train_batch_loss=1.31, v_num=0, val_loss=1.05]
```

### Environment

 - PyTorch Version : 1.3.1
 - OS : macOS 10.14.6
 - How you installed PyTorch : `pip install git+https://github.com/williamFalcon/pytorch-lightning.git@master --upgrade`
 - Python version : 3.7.3
 - use CPU

### PR DESCRIPTION
**Pull request by onkyo14taro**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   

## What does this PR do?
Fixes #675 .

## Others
Zero-based unification will be done in v0.8.0.

### CODE REVIEW

**Comment by Borda** [comment]
what is the difference to past #785?

**Comment by onkyo14taro** [comment]
> what is the difference to past #785?

I'm sorry, I closed #785 by mistake, so, and then opened a new PR #786.

**Comment by Borda** [comment]
well, next time rather reopen the issue then create its twin... ;)

**Comment by onkyo14taro** [comment]
Thank you, I'll do next time...

**Pull request merged**
