### PR TITLE
Add forgotten deterministic trainer flag to doctest

### PR DESCRIPTION
**Pull request by awaelchli**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
I think this PR #1572 forgot to add the flag to doctest and made the master branch fail.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
If one adds or changes a Trainer flag, it has to be changed in two locations

**Comment by Borda** [comment]
it is also here #1791

**Comment by williamFalcon** [comment]
Yeah, that seems weird... why not pull the defaults out of the trainer for that test?

**Comment by Borda** [comment]
just curious how it got to the master...

**Comment by awaelchli** [comment]
no idea. maybe we need to rethink that doctest. it will happen again in the future. nobody will remember to change the flag in two places. 

probably a proper test instead of doctest and inspect the signature like william suggests

**Comment by Borda** [comment]
@awaelchli so you say that that
A) the doctest are not running 
B) due to the Git history / overlap the tests did not run properly?
What do you mean by inspect signatures, can not see Will's comment about it...

**Pull request merged**
