### PR TITLE
Sharded Plugin 3/n: Unify distributed accelerators

### PR DESCRIPTION
**Pull request by SeanNaren**
## What does this PR do?

Relates to #4178

To integrated the sharded plugin I had to make a few API changes to the accelerator. This was very ugly as it involved modifying the logic in all DDP based accelerators.

This PR adds a unified distributed accelerator which all DDP accelerators inherit from. This has reduced the code duplication and allowed for API changes to happen for all DDP supported accelerators. Included is the addition of a plugin extension to move inputs to the appropriate device, required for custom DDP wrappers (like sharded DDP).

cc @ananthsub @williamFalcon @awaelchli @justusschock @Borda @tchaton 

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In in short, see following bullet-list:  

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
so i don’t love going down this route. i already did this a while back, made all ddp inherit from the same ddp. 

then contributors made changes to the core class and broke every accelerator. 

so i undid that change and make them all independent again. 

but here we go back to making them all dependent. 

the problem with this is that contributors are selfish lol. they fix an issue for “their” accelerator and don’t think about all the other accelerators. so it’s a mouse game. fix accelerator a and accelerator b,c,d break. then fix accelerator b and a, c, d break

**Review by williamFalcon — CHANGES_REQUESTED** [review]
i don’t want to unify all accelerators. please keep them separate as they are today. 

if we let this happen we will go back to accelerators being broken often

**Comment by SeanNaren** [comment]
This is fair, the code for accelerators are liable to be broken unexpectedly if they are unified in this way. No problem here, but atleast will be able to reference back to this decision!

**Comment by williamFalcon** [comment]
can we follow up with this pr and add the warning on top of each accelerator about unification?

fyi @justusschock for your refactors

**Pull request closed without merging**
