### PR TITLE
fix loading model with kwargs

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Fix loading from checkpoint...

Fixes # (issue)

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
nice!

**Comment by nischal-sanil** [comment]
Does this pr solve these issues #2386 #2359 #2364 ?

**Comment by Borda** [comment]
@nischal-sanil even they are similar, but I guess it is not fix... Mind try the master and eventually share minimal examples to reproduce? :)

**Comment by nischal-sanil** [comment]
@Borda Sorry I had forgotten to add the steps to reproduce the error. I have updated my current issue #2386 to contain the same.

**Pull request merged**
