### PR TITLE
Remove deprecated property `is_using_torchelastic` from AcceleratorConnector

### PR DESCRIPTION
**Pull request by daniellepintz**
## What does this PR do?

as title

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by ananthsub — APPROVED** [review]

**Review by rohitgr7 — APPROVED** [review]
aren't all deprecations removed in a single PR?? there is 1 more.

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
@rohitgr7 I can't see any more usages that are from the accelerator connector. All the rest are from the TorchElasticEnvironment

**Comment by rohitgr7** [comment]
@awaelchli I meant the other deprecation. https://github.com/PyTorchLightning/pytorch-lightning/blob/131176b9f5e544a1133240a46dca1960308b7849/pytorch_lightning/trainer/trainer.py#L230

**Comment by awaelchli** [comment]
there is already a PR for it but its blocked: #9246 
normally deprecated api gets removed in individual PRs

**Review by carmocca — APPROVED** [review]

**Pull request merged**
