### PR TITLE
Fix requirements-extra.txt Trains package to release version

### PR DESCRIPTION
**Pull request by bmartinn**
@Borda , I noticed the `requirements-extra.txt` points to an RC version of *Trains*.
Since if in a `requirements.txt` the minimum version is an RC version, pip will always pull the latest pre-release version. I don't think this is what we want, especially with the CI :)
I fixed `requirements-extra.txt` to point to the latest released version.

Apologies for the mess ...

EDIT:
For the sake of completeness, I also added a reference to Trains in the README visualization section

### CODE REVIEW

**Comment by Borda** [comment]
Thx, could you please rebase on on actual master?

**Comment by bmartinn** [comment]
@borda, I already just (2 hours ago) merged the latest mater into my branch and pushed the PR.
GitHub somehow shows previous commits that are unrelated... 
Am I missing something ?

**Comment by Borda** [comment]
that is the difference between merge and rebase... merge just add the missing commits to your branch... on the other hand, rebase takes mater and place your commit on the top so the diff shows just the newly added commits, pls see https://medium.com/datadriveninvestor/git-rebase-vs-merge-cc5199edd77c
image

**Comment by bmartinn** [comment]
@Borda, my deepest apologizes, I can totally see my mistake. Let me see if I can fix it...

**Comment by Borda** [comment]
@bmartinn no need for an apology! I meant it just as friendly advice and we thank you for you contribution!

**Comment by Borda** [comment]
another FRIENDLY advice, there is no need to creating new Prs, after the rebase you just `git push --force` to the actual branch and it updates the PR :]

**Comment by bmartinn** [comment]
Actually the PR closed automatically the minute I forced pushed the upstream/master head (I guess since the original PR commit id was deleted ...)

**Comment by Borda** [comment]
yeah, true it closes if the content is identical, so it is better to push it after rebase... it is also possible to reopen it but never mind, let's continue :]

**Pull request closed without merging**
