### PR TITLE
testing new speed

### PR DESCRIPTION
**Pull request by williamFalcon**
## What does this PR do?
Fixes # (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by jeremyjordan** [comment]
is this a work in progress? only change i see here is adding some prints

**Comment by williamFalcon** [comment]
@Borda we need to merge+close this

**Comment by Borda** [comment]
> @Borda we need to merge+close this

sure, I ll take it as priority now

**Comment by Borda** [comment]
@williamFalcon it is ready now, the docs will be updated in #2072

**Comment by williamFalcon** [comment]
ok, let’s add a todo for memory parity to catch leaks @Borda @edenafek

**Pull request merged**
