### PR TITLE
run full TPU pytests

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

A this moment we execute just single file and if any TPU test is elsewhere it has to be added, so we rather run on whole package so we do not accidentally (in future) update this separate test case...

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
failing dome TPU tests
```
terminate called after throwing an instance of 'std::runtime_error'

  what():  tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1106 : Check failed: session->session()->Run( feed_inputs, {}, {cached_node.operations[0]}, &outputs) == ::tensorflow::Status::OK() (Not found: From /job:tpu_worker/replica:0/task:0:

XRT memory handle not found: 3824064254680872

	 [[{{node XRTReleaseAllocationHandle}}]] vs. OK)

*** Begin stack trace ***

	tensorflow::CurrentStackTrace[abi:cxx11]()

	xla::XrtComputationClient::ReleaseHandles(std::vector<xla::XrtComputationClient::DeviceHandle, std::allocator<xla::XrtComputationClient::DeviceHandle> >*, std::function<xla::XrtSession::CachedNode const& (xla::XrtSession*, tensorflow::Scope const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&, xla::metrics::Metric*, xla::metrics::Counter*)

	xla::XrtComputationClient::HandleReleaser()

	xla::util::TriggeredTask::Runner()
```
@zcain117 any idea what it could be?

**Comment by Borda** [comment]
sunning the same test in Collab
https://colab.research.google.com/drive/1Gr1Wg4zVnu15WHE_-dU2YKr4Z5xsy-fL#scrollTo=Mx61q3X5bwoW

**Comment by Borda** [comment]
the only limitation is that it would take longer to finish TPU test which is even not the longer from all others...

**Comment by Borda** [comment]
@zcain117 any ide why even the TPU tests are failing?

**Comment by edenlightning** [comment]
@Borda do we want to revive this?

**Comment by Borda** [comment]
it would be nice to be sure that all PL is working on TPU but very important at this moment :]

**Review by awaelchli — APPROVED** [review]

**Comment by Borda** [comment]
update:
```
=========================== short test summary info ============================
FAILED tests/checkpointing/test_model_checkpoint.py::test_model_checkpoint_no_extraneous_invocations
FAILED tests/checkpointing/test_torch_saving.py::test_model_torch_save_ddp_cpu
FAILED tests/core/test_metric_result_integration.py::test_result_reduce_ddp
FAILED tests/core/test_results.py::test_result_reduce_ddp[Result] - Exception...
FAILED tests/core/test_results.py::test_result_reduce_ddp[TrainResult] - Exce...
FAILED tests/core/test_results.py::test_result_reduce_ddp[EvalResult] - Excep...
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[CometLogger]
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[NeptuneLogger]
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[TensorBoardLogger]
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[TestTubeLogger]
FAILED tests/loggers/test_mlflow.py::test_mlflow_logger_dirs_creation - Impor...
FAILED tests/metrics/test_ddp.py::test_ddp[_test_ddp_cat] - Exception: proces...
FAILED tests/metrics/test_ddp.py::test_ddp[_test_ddp_sum] - Exception: proces...
FAILED tests/metrics/test_ddp.py::test_ddp[_test_ddp_sum_cat] - Exception: pr...
FAILED tests/models/test_cpu.py::test_multi_cpu_model_ddp - Exception: proces...
FAILED tests/models/test_horovod.py::test_horovod_cpu - assert 127 == 0
FAILED tests/models/test_horovod.py::test_horovod_cpu_implicit - assert 127 == 0
FAILED tests/models/test_horovod.py::test_horovod_multi_optimizer - pytorch_l...
FAILED tests/trainer/logging_tests/test_distributed_logging.py::test_global_zero_only_logging_ddp_cpu
FAILED tests/utilities/test_xla_device_utils.py::test_tpu_device_presence - A...
= 20 failed, 1563 passed, 137 skipped, 3 xfailed, 2045 warnings in 358.25s (0:05:58) =
```

**Comment by Borda** [comment]
@zcain117 any idea why even the TPU tests are failing?

**Comment by zcain117** [comment]
> @zcain117 any idea why even the TPU tests are failing?
> also wondering why some CPU tests with distributed execution fail...

One error I'm seeing a lot of is this:

`Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library. Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.`

I ran into this once and I ran this command to fix it before tests start: 

`export MKL_THREADING_LAYER=GNU`

**Comment by Borda** [comment]
TODO: it seems that the docker build and push takes too long, about 5min, check what is the most time consuming part

**Comment by Borda** [comment]
@zcain117 any idea why the reposts are not transfers correctly? always ends with `Done with log retrieval attempt.`
Also, it seems that all test shave not finished at the time it ended/terminated

**Comment by zcain117** [comment]
> @zcain117 any idea why the reposts are not transfers correctly? always ends with `Done with log retrieval attempt.`
> Also, it seems that all test shave not finished at the time it ended/terminated

so the logs come from the `kubectl logs` command, which prints out everything until the GKE machine gets deleted. I see this line in your logs `Done waiting. Job status code: 1` which means the GKE machine exited with non-success status while midway through testing

I think you might need to extend the timeout of the GKE machine here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/dockers/tpu-tests/tpu_test_cases.jsonnet#L11

maybe also change the test command to print timestamps for each stdout line (optional) but CircleCI says 15m45s for that step

**Comment by Borda** [comment]
l I am wondering what happened that a few weeks ago I was able to get lost of a falling test within a few minutes and 30 min is not enough... could it be that some tests are hanging now?

**Comment by Borda** [comment]
@zcain117 mind have look or any suggestion who can I ask?

**Comment by Borda** [comment]
@zcain117 mind have look ^^

**Comment by Borda** [comment]
```
=========================== short test summary info ============================
FAILED tests/callbacks/test_pruning.py::test_pruning_callback_ddp_cpu - Excep...
FAILED tests/callbacks/test_swa.py::test_swa_callback_ddp_cpu - Exception: pr...
FAILED tests/checkpointing/test_model_checkpoint.py::test_model_checkpoint_no_extraneous_invocations
FAILED tests/checkpointing/test_torch_saving.py::test_model_torch_save_ddp_cpu
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[MLFlowLogger]
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[NeptuneLogger]
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[TensorBoardLogger]
FAILED tests/loggers/test_all.py::test_logger_created_on_rank_zero_only[TestTubeLogger]
FAILED tests/models/test_cpu.py::test_multi_cpu_model_ddp - Exception: proces...
FAILED tests/models/test_horovod.py::test_horovod_cpu - assert 127 == 0
FAILED tests/models/test_horovod.py::test_horovod_cpu_implicit - assert 127 == 0
FAILED tests/models/test_horovod.py::test_horovod_multi_optimizer - pytorch_l...
FAILED tests/models/test_tpu.py::test_model_tpu_cores_1 - AssertionError: exp...
FAILED tests/models/test_tpu.py::test_model_tpu_index[1] - AssertionError: ex...
FAILED tests/models/test_tpu.py::test_model_tpu_index[5] - AssertionError: ex...
FAILED tests/models/test_tpu.py::test_model_16bit_tpu_cores_1 - AssertionErro...
FAILED tests/models/test_tpu.py::test_model_16bit_tpu_index[1] - AssertionErr...
FAILED tests/models/test_tpu.py::test_model_16bit_tpu_index[5] - AssertionErr...
FAILED tests/models/test_tpu.py::test_model_tpu_early_stop - AssertionError: ...
FAILED tests/models/test_tpu.py::test_tpu_grad_norm - AssertionError: expecte...
FAILED tests/trainer/test_trainer.py::test_pytorch_profiler_nested - Assertio...
FAILED tests/trainer/logging_/test_distributed_logging.py::test_global_zero_only_logging_ddp_cpu
FAILED tests/trainer/properties/test_get_model.py::test_get_model_ddp_cpu - E...
FAILED tests/utilities/test_all_gather_grad.py::test_all_gather_ddp - Excepti...
= 24 failed, 3369 passed, 477 skipped, 3 xfailed, 2959 warnings in 1559.35s (0:25:59) =
```

**Comment by Borda** [comment]
it would be nice to have it also with #6078 🐰

**Review by tchaton — COMMENTED** [review]
Not sure we should have all our tests on TPU as it takes 30 min.

**Comment by carmocca** [comment]
I agree with Thomas. I would try to avoid adding extra test time to TPUs since they are a bottleneck in our CI pipeline and we get random kubernetes failures from time to time.

If what we want to avoid is people forgetting to add the test to a `tpu_test.sh` file. We could define the tests which require TPU with a marker and we indicate pytest to only run those tests. see:

https://docs.pytest.org/en/stable/example/markers.html

**Comment by Borda** [comment]
> I agree with Thomas. I would try to avoid adding extra test time to TPUs since they are a bottleneck in our CI pipeline and we get random kubernetes failures from time to time.

I see your point with time, but what you say is we do not case if TPU works except for some selected cases...

**Comment by carmocca** [comment]
> we do not case if TPU works except for some selected cases...

Can the CPU tests fail if they are run in an environment with TPUs?

**Comment by Borda** [comment]
> > we do not case if TPU works except for some selected cases...
> 
> Can the CPU tests fail if they are run in an environment with TPUs?

t is what the tests shall tell you...

**Pull request closed without merging**
