### PR TITLE
check if checkpoint_callback exists

### LINKED ISSUE #2547: Can't use None (anymore) in checkpoint_callback
## 🐛 Bug
using None in checkpoint_callback now errors out

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 562, in ddp_train
    q.put(self.checkpoint_callback.best_model_path)
AttributeError: 'NoneType' object has no attribute 'best_model_path'
```

### To Reproduce
`trainer = Trainer(checkpoint_callback=None)`

Ran into this issue from upgrading to masters, was using masters from a few commits ago before

Edit: `False` casuses the same error as well

### PR DESCRIPTION
**Pull request by s-rog**
## What does this PR do?

check checkpoint_callback before setting best_model_path for ddp_spawn

Fixes #2547 

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by justusschock** [comment]
Why could it ever happen, that you don't have this callback?

**Comment by Borda** [comment]
> Why could it ever happen, that you don't have this callback?

good question, @s-rog mind elaborate what is the scenario so we may add a test case...

**Comment by awaelchli** [comment]
The user can set `Trainer(checkpoint_callback=None)`, which explicitly disables checkpointing. By default, it is turned on.

**Comment by Borda** [comment]
@s-rog mind add test case with disabled checkpointing?

**Comment by s-rog** [comment]
@Borda should it be under trainer or callbacks?

**Comment by Borda** [comment]
> @Borda should it be under trainer or callbacks?

as the callback is missing, I would put it under Trainer

**Comment by s-rog** [comment]
I just noticed that there are already other tests with `checkpoint_callback=False` but no tests are ran with the `ddp_spawn` option

Should I just add a specific test for none checkpoint using ddp_spawn?

**Comment by Borda** [comment]
> Should I just add a specific test for none checkpoint using ddp_spawn?

yes, add extra or try to run it as test parameter

**Comment by Borda** [comment]
seems @williamFalcon was to hurry... @s-rog mind open a new PR with adding the test...

**Comment by s-rog** [comment]
yeah I'll do that as soon as I can, have only taken a quick look at existing tests

**Pull request merged**
