### PR TITLE
updated hooks

### PR DESCRIPTION
**Pull request by williamFalcon**

### CODE REVIEW

**Comment by Borda** [comment]
btw, careful with `setup` and `teardown` adding extra argument in middle would be breaking changes... :/

**Comment by awaelchli** [comment]
This PR breaks all user callbacks and hooks, is this intended?
Also it remove the test for a recent fix?
The call to `is_implemented` is not necessary as it is anyway true always and every hook/callback is a no-op by default, so we can just call it anyway.

**Comment by Borda** [comment]
> This PR breaks all user callbacks and hooks, is this intended?

if a user uses positional arguments, then yes :/

**Comment by awaelchli** [comment]
no, the user does't call the callback themselves. The user inherits them, so after this change the user has to go to every callback they have implemented and change the signatures manually. This is what you will have to do also in bolts I assume.

**Comment by williamFalcon** [comment]
yeah,  but it’s kind of a necessary evil for 1.0. unless u guys have a way of making it compatible?  maybe we can try catch them or something

**Comment by williamFalcon** [comment]
but i’m pretty sure only the new hooks i introduced have these new args. those hooks aren’t live yet, so it’s a fair change since they only live on master

**Comment by awaelchli** [comment]
Ok, I just wanted to make sure you are aware of it.

**Pull request merged**
