### PR TITLE
CI pass

### PR DESCRIPTION
**Pull request by Borda**
# Before submitting
minor fixes to gets the CI passing @neggert 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by neggert** [comment]
Could you also increase `num_epochs` to 4 in `test_restore_models.py::test_running_test_pretrained_model_dp`? Same issue, but only shows up when running on GPUs.

**Comment by Borda** [comment]
@neggert done ^^

**Comment by neggert** [comment]
LGTM

**Comment by Borda** [comment]
@williamFalcon ^^

**Pull request merged**
