### PR TITLE
[WIP] accelerator base class and unify interface (waiting on bottoms up refactors first)

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Draw basic Accelator interface and update all backends

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
@Borda this is premature. please wait until we finish the other refactors.

**Comment by justusschock** [comment]
Regarding that Interface:

shouldn't the overall stuff be to have the trainer, that calls the backend and not vice versa?

E.g.

```
def train(self):
    self.setup_backends():
    for epoch in range(self.num_epochs):
        for batch in (self.train_loader):
            model.train_step(batch)

```

Right now, the overall flow of which class is in charge of what is quite problematic and non-trivial since we switch to responsibilities between trainer and backends quite often, which makes it hard to do this.

In general, I'd prefer to have the backends more like some kind of callback, that is called by trainer and trainer to handling everything else

**Comment by awaelchli** [comment]
Agree with @justusschock. If possible, I'd like to be able to do this in the future: `Trainer(distributed_backend=MyBackend())` Where MyBackend inherits the (abstract) class for Backend.

**Comment by williamFalcon** [comment]
yes guys lol... that's the end goal. We're going bottoms up to get there. but that's exactly the reason i introduced this abstraction weeks ago haha.

**Pull request closed without merging**
