### PR TITLE
fix codecov reports

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Code coverage is 0% even test are passing
```
==> Uploading
--
1786 | .url https://codecov.io
1787 | .query commit=7c7e50ca4702a5b35bc1b80d44bca7606552093a&branch=master&token=<secret>&yaml=.codecov.yml&package=py2.0.22
1788 | Pinging Codecov...
1789 | Uploading to S3...
1790 | Error: 400 Client Error: Bad Request for url: https://storage.googleapis.com/codecov/v4/raw/2020-05-17/58A692D2985A264F96A68126BE73B9B0/7c7e50ca4702a5b35bc1b80d44bca7606552093a/b07d5371-d622-4f23-a9b9-bf5b3852c5fb.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EQX6OZVJGHKK3633AAFGLBUCOOATRACRQRQF6HMSMLYUP6EAD6XSWAAY%2F20200517%2FUS%2Fs3%2Faws4_request&X-Amz-Date=20200517T205829Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=08b8d05d691f71bbaaacd01a319298e142ff660078e19e74ed63b154072e789e
```
https://codecov.io/gh/PyTorchLightning/pytorch-lightning/branch/master/commits?page=1

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
https://community.codecov.io/t/http-400-while-uploading-to-s3-with-python-codecov-from-travis/1428

**Comment by Borda** [comment]
reported in https://github.com/codecov/codecov-python/issues/251

**Comment by williamFalcon** [comment]
merge?

**Comment by Borda** [comment]
> merge?

no, the issue is not on our side, codecov has some problem so I keep for link and track their progress

**Pull request merged**
