### PR TITLE
add validation_epoch(), train_epoch(), test_epoch() for trainer

### PR DESCRIPTION
**Pull request by davinnovation**
add option for running train, in run_pretrain function for 'pytest'

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/1911

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
i think a more general solution is to support

```
trainer.validation_epoch()
trainer.train_epoch()
```

or something like that no?

**Comment by davinnovation** [comment]
trainer.validation_epoch(), train_epoch() should be more general.

**Comment by williamFalcon** [comment]
go for it! maybe convert this PR into that?

**Comment by davinnovation** [comment]
Sure. I'll start with v1 - single_gpu. Thanks for a great guide :)

**Comment by awaelchli** [comment]
I thought the goal was to separate training and testing and not rely on pretrain_routine for testing?

**Comment by jeremyjordan** [comment]
Yes, there's a related issue: #1195 

In my opinion, the pre-train routine should be exactly how it sounds, a routine run before training which sets everything up. We should **not** be invoking training within the pre-train routine.

**Comment by Borda** [comment]
@davinnovation @jeremyjordan how is it going here, ready for review?

**Comment by jeremyjordan** [comment]
@davinnovation can you help me understand the motivation for this PR? Is it so that we can perform all of the necessary setup without triggering a training run? Given that this method is not part of the public API, how do you plan to use the new feature? Are you invoking `run_pretrain_routine` directly or would this be wrapped up into a call to `fit()`?

Agree that this is just a small step into the direction of refactoring for what is needed in #1195.

**Comment by davinnovation** [comment]
@jeremyjordan Motivation was `run_pretrain_routine` should work as documented - "sanity check a few things before starting actual training" + and it can be used for code testing 'before running train phase'

IMO, invoking `run_pretrain_routine`  with option can be a good start for refactoring #1195

**Comment by Borda** [comment]
@davinnovation is this still valid PR? mind check it...

**Comment by davinnovation** [comment]
@Borda Might be this PR has been outdated by other commits... closing. Thanks for remind

**Pull request closed without merging**
