### PR TITLE
add python 3.8 testing

### LINKED ISSUE #910: Python 3.8 support
Hello!

With pytorch now supporting python 3.8, I was wondering if there is a plan to support py 3.8 for lightning too? I was curious about upgrading to 3.8 for the type hints to better organize my own code. Is there something that prevents 3.8 support in lightning inherently?

Cheers!

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Fixes #910. I have run CI for 3.8 and it seems that not all packages are ported to 3.8 yet, e.g. `torchvision` Which comes we shall drop `torchvision` even from test dependencies #859 #942 #986 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
@Borda how's this going

**Comment by Borda** [comment]
lets keep this for future, `lightning` in its installation does not depend on `torchvision` the solution to this are:
- install `torchvision` from source/git
- wait till `torchvision` is available on pip for py3.8
- having own MNIST dataset #942

**Comment by williamFalcon** [comment]
@Borda is this dead?

**Comment by Borda** [comment]
no, just resumed, it was blocked by #986 which was merged right now...

**Comment by Borda** [comment]
seems that PyTorch 1.1 does not exist for py3.8 is, the minimal version is 1.2

**Pull request merged**
