### PR TITLE
update docs on checkpoint_callback Trainer argument

### LINKED ISSUE #4446: Checkpoint docs update
make sure we don't use the old interface in notebooks and old examples

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Fixes  #4446
Adds docs update to deprecation introduced in  #4336 

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

### CODE REVIEW

**Review by SeanNaren — APPROVED** [review]

**Comment by rohitgr7** [comment]
what if both a checkpoint_callback is passed in callbacks and `checkpoint_callback = True`, should we raise a warning here?

**Comment by awaelchli** [comment]
@rohitgr7 no, because `checkpoint_callback = True` is the default, so it would always lead to a warning if we did that. True is ignored if we pass in a callback through the list.

**Comment by rohitgr7** [comment]
@awaelchli not always I think. Only if someone passes a ModelCheckpoint explicitly in the callbacks.

**Comment by awaelchli** [comment]
@rohitgr7 
```python
Trainer(checkpoint_callback=ModelCheckpoint(...))  # this is now a warning
```

```python
Trainer(callbacks=[ModelCheckpoint(...)])  # this should not throw a warning, because it is now the recommended way
```

```python
# equivalent
Trainer(checkpoint_callback=True (default), callbacks=[ModelCheckpoint(...)]) 
```

**Review by rohitgr7 — APPROVED** [review]
oh okay got it, where the hell is my head :sweat_smile: 
just one more regarding the deprecation. @Borda said it's always +v0.2 but this thing is marked as deprecated in v1.1 and removed in v1.4

**Review by s-rog — APPROVED** [review]

**Pull request merged**
