### PR TITLE
prune changelog

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
removing empty/none release sub-actions

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@jeffling just design but agree that it is not better so I ll move it back or do you have other suggestions?

**Comment by jeffling** [comment]
I think it's fine either way. Slight preference for having the date be separately surrounded by whitespace for easy grepping (ie `@ 2000-01-01`) 

Don't have an opinion on what the delimiter actually is. Could be `-`, `@`, even `on`

**Comment by ethanwharris** [comment]
Ideally we would stick with dashes so that we are consistent with [keepachangelog.com](https://keepachangelog.com/en/1.0.0/)

**Comment by Borda** [comment]
> Ideally we would stick with dashes so that we are consistent with [keepachangelog.com](https://keepachangelog.com/en/1.0.0/)

Ok, I ll change it =)

**Pull request merged**
