### PR TITLE
Fix backwards compatibility for deprecated logging module

### LINKED ISSUE #798: Optional dependencies are required for deprecated logging module
🐛 Bug

There is a backwards compatibility issues coming from PR #767. Notably, if a user doesn't have any of the extra logging dependencies then they'll be an import error.

### To Reproduce

1. Remove all logging dependencies from your environment (E.g. comet)
2. Depend on the deprecated pytorch_lightning.logging package and run

### Expected behavior

We expect to maintain backwards compatibility here so optional dependencies shouldn't be required.

### PR DESCRIPTION
**Pull request by tullie**
# Before submitting
- [X] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [X] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [X] Did you make sure to update the docs?   
- [X] Did you write any new necessary tests?  

## What does this PR do?
Fixes #798

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
Maybe we do not have open an issue if have already fix... And rather write the description here instead...

**Comment by Borda** [comment]
it seems that it does fix one hole but breaks other compatibility...
```
import pytorch_lightning.loggers.mlflow
import pytorch_lightning.logging.mlflow
Traceback (most recent call last):
  File "/home/jb/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-8c3cb4802809>", line 1, in <module>
    import pytorch_lightning.logging.mlflow
  File "/home/jb/Applications/pycharm-2019/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pytorch_lightning.logging.mlflow'
```

**Comment by tullie** [comment]
Yeah agreed that making the issues doesn't make sense. I only did it because the PR description prompted me too. 

Good point. I'll revise today to fix that too.

**Comment by Borda** [comment]
@williamFalcon it was not fixed... @tullie wanted to continue on this...

**Comment by williamFalcon** [comment]
@Borda oh shoot, sorry  didn't  read that last comment. Let's finish this in a separate PR?

**Comment by Borda** [comment]
Well as you already merged it, it has to done in other PR #815?

**Pull request merged**
