### PR TITLE
Adding a new section to the docs: Example Lightning Project Structures

### PR DESCRIPTION
**Pull request by Erlemar**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
In a slack discussion it was decided to add sample project structures with lightning code. A new section between tutorials and use cases was added.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.

## Did you have fun?
Yes, I had fun :)

### CODE REVIEW

**Comment by justusschock** [comment]
@Erlemar TBH I would not like to link your personal repo here, since we kind of need to control it (we can't be sure, what you'll change in future). Additionally I think such repos should be installable packages.

**Comment by williamFalcon** [comment]
sorry, that was my suggestion. but now that i think about it it makes sense to keep the seed one there not the other. 

But we can do a few things:
1. if you want, we can fork and add to the community examples (with clear letters to look at the original repo in the readme)

**Comment by Erlemar** [comment]
I understand, it would be a better practice to freeze the code and to be sure it won't be changed in the future unexpectedly indeed. I would be excited if my repo were forked and added to the community examples.

**Comment by Borda** [comment]
Could it be part of Bolts?

**Comment by williamFalcon** [comment]
@Erlemar ok made the changes. will merge when tests clear

**Pull request merged**
