### PR TITLE
Add docs about example dependencies

### LINKED ISSUE #2120: Unable to run tests locally due to missing dependencies
## 🐛 Bug

Unable to run tests locally due to missing dependencies on torchvision and gym packages.

### To Reproduce

1. Follow the instructions to run tests locally in the contributing guide.

#### Error message

```bash
_______________________________________________________ ERROR collecting pl_examples/__init__.py ________________________________________________________
pl_examples/__init__.py:143: in <module>
    from pl_examples.models.lightning_template import LightningTemplateModel
pl_examples/models/lightning_template.py:10: in <module>
    import torchvision.transforms as transforms
E   ModuleNotFoundError: No module named 'torchvision'

...

_________________________________________ ERROR collecting pl_examples/domain_templates/reinforce_learn_Qnet.py _________________________________________
pl_examples/domain_templates/reinforce_learn_Qnet.py:26: in <module>
    import gym
E   ModuleNotFoundError: No module named 'gym'
```

### Expected behavior

The packages should be added in tests/requirements.txt

### PR DESCRIPTION
**Pull request by uditarora**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Fixes #2120.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
it is already here https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/requirements.txt

**Comment by uditarora** [comment]
Oh I see. Maybe this needs to be mentioned in the Contribution guide then?

**Comment by Borda** [comment]
ok, mind updating the info as part of this PR?

**Comment by uditarora** [comment]
I've pushed the changes on my PR branch, but they didn't show up here perhaps because the PR is closed. Please update the status of the PR.

**Pull request merged**
