### PR TITLE
log on rank_zero only while saving last checkpoint.

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

log on rank_zero only while saving last checkpoint.

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by rohitgr7** [comment]
is there some problem with tests?? `##[error]The operation was canceled.` never seen this before.

**Comment by awaelchli** [comment]
comes from master, some logger test hangs.

**Comment by awaelchli** [comment]
@rohitgr7 do you see this message multiple times? because it should save only on rank 0 anyways.

**Comment by rohitgr7** [comment]
@awaelchli yes, in case of TPU. Yeah, it's saving on rank_zero but this message should also log on rank_zero too.

**Comment by awaelchli** [comment]
yeah sorry, this is in on train end. makes sense.

**Review by awaelchli — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Comment by awaelchli** [comment]
@rohitgr7 It was fixed here #3483

**Comment by rohitgr7** [comment]
I wonder why is it marked as a warning. Should be a simple info log.

**Pull request closed without merging**
