### PR TITLE
join coverage

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

join coverage reports from GPU and TPU

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by justusschock** [comment]
@Borda while we're on it, can we also cover the reports from cpu runs? IMO every run should upload a report and all of these should be joined

**Comment by Borda** [comment]
> @Borda while we're on it, can we also cover the reports from cpu runs? IMO every run should upload a report and all of these should be joined

good point but now I have still problems even to merge two gpu-tpu reports in one... :( @justusschock any suggestion?

**Comment by justusschock** [comment]
With codecov it usually merges them automatically if you just upload multiple reports...

**Comment by Borda** [comment]
let's see here: https://codecov.io/gh/PyTorchLightning/pytorch-lightning/pull/2460

**Comment by justusschock** [comment]
usually my `.codecov.yml` looks like this:

```yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.50
        base: auto
    patch: off

ignore:
  - "tests/"
  - "*/__init.py"
```

And afaik this just works

**Comment by awaelchli** [comment]
a while back when I tried to include the sphinx doctests it would upload the report but the problem was that the coverage database was empty. Never figured out why but maybe it's the same here. just a thought.

**Comment by Borda** [comment]
I think I see the issue, it seems that the TPU coverage has mapped `pytorch_lightning` as `main/pytorch_lightning` which somehow appears as another package... @zcain117

**Comment by Borda** [comment]
a bit confused about this error from TPU
```
+ coverage run --source=pytorch_lightning -m pytest tests/models/test_tpu.py -v
ImportError while loading conftest '/pytorch-lightning/tests/conftest.py'.
tests/__init__.py:4: in <module>
    import torch
/root/miniconda3/envs/container/lib/python3.7/site-packages/torch/__init__.py:188: in <module>
    _load_global_deps()
/root/miniconda3/envs/container/lib/python3.7/site-packages/torch/__init__.py:141: in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
/root/miniconda3/envs/container/lib/python3.7/ctypes/__init__.py:364: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
```

**Comment by Borda** [comment]
Codecov was messing with Drone as it was automatically getting kind of random commit hash so even it was uploaded to Codecov server it was not match to the proper commit/PR...

**Pull request merged**
