### PR TITLE
add CSVLogger to tests

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

just adding the to tests with other loggers

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by ananthsub — APPROVED** [review]

**Comment by ananthsub** [comment]
how'd you find this?

**Comment by Borda** [comment]
> how'd you find this?

not fixed anything yet, just draft so I do not miss it... 🐰

**Comment by Borda** [comment]
ok, leaving this as adding the import only and try to fix in another try...

**Review by ethanwharris — APPROVED** [review]

**Comment by awaelchli** [comment]
It's closing #7899 right? Added to PR description

**Comment by Borda** [comment]
> It's closing #7899 right? Added to PR description

no, I did not have time to search the issue so leaving it open and describe in the new issue, see https://github.com/PyTorchLightning/pytorch-lightning/pull/6854#issuecomment-857617226

**Review by awaelchli — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Pull request merged**
