### PR TITLE
[Metrics] PrecisionRecallCurve, ROC and AveragePrecision class interface

### PR DESCRIPTION
**Pull request by SkafteNicki**
## What does this PR do?

* Add class interface `PrecisionRecallCurve`, `ROC`, `AveragePrecision` metrics
* Unifies functional and class interface for the three metrics
* Unifies binary and multiclass interface meaning that instead of having both a `roc` and `multiclass_roc` metric, we only have `roc` metric where the user would need to specify `num_classes` in multiclass tasks.
* Adds multiclass support for `average_precision` metric
* Support for multidim tensors
* Much better testing, some where not tested at all

The PR is on the larger size, but the three metrics are connected and therefore needs to be updated in one go

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In in short, see following bullet-list:  

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by teddykoker — APPROVED** [review]
Amazing work @SkafteNicki, great job :)

**Comment by teddykoker** [comment]
It seems SSIM tests are failing occasionally (I know you didn't touch it in this PR), do you think we should increase the tolerance? It is quite high already... I feel we might want to remove SSIM until it is actually implemented correctly

**Comment by SkafteNicki** [comment]
@teddykoker, I would
* Increase tolerance for now
* Mention directly in docstring of SSIM that results may be a bit unstable
* Open a issue and hope someone wants to tackle this

**Review by teddykoker — APPROVED** [review]
LGTM!!

**Review by justusschock — APPROVED** [review]

**Pull request merged**
