### PR TITLE
[ModelPruning] Add missing attribute with use_global_unstructured=False and verbose

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

`__name__` is lost with partial and this wasn't covered with the current tests because it needs verbose.

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [n/a] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [n/a] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@carmocca "ready-to-go" is meant for the first positive reviewer, otherwise, there is no reason to use it...

**Review by SeanNaren — APPROVED** [review]

**Comment by carmocca** [comment]
> @carmocca "ready-to-go" is meant for the first positive reviewer, otherwise, there is no reason to use it...

Well i'm positive this works 😄

Just added it because the PR is so small but I'll hold off for next time.

**Comment by Borda** [comment]
there is something fishy on codecov, this minimal changes shall pass, maybe because of edited lines that are not covered by tests?

**Review by tchaton — APPROVED** [review]
LGTM !

**Pull request merged**
