### PR TITLE
quick patch __code__

### PR DESCRIPTION
**Pull request by williamFalcon**
fixing pickle error from earlier PR

### CODE REVIEW

**Comment by Borda** [comment]
@bmartinn with removing the line above we are getting Trains issue:
```
Traceback (most recent call last):
  File "/home/software/miniconda3/envs/pl10/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/backend_interface/logger.py", line 197, in run
    while not self._exit_event.wait(period or 1.0):
  File "/home/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/logger.py", line 522, in flush
    return self._task.flush()
  File "/home/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/task.py", line 751, in flush
    LoggerRoot.flush()
  File "/home/software/miniconda3/envs/pl10/lib/python3.7/site-packages/trains/debugging/log.py", line 92, in flush
    h.flush()
  File "/home/software/miniconda3/envs/pl10/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
ValueError: I/O operation on closed file.
```

**Comment by bmartinn** [comment]
@Borda is this related to the TrainsLogger ? How do I reproduce this bug?

**Comment by bmartinn** [comment]
@williamFalcon @Borda I just tested the merged master, seems to pass the `test_trains.py`. 
Is the bug still there?

**Comment by Borda** [comment]
According to CI everything is passing new - http://35.192.60.23/PyTorchLightning/pytorch-lightning/1049

**Comment by bmartinn** [comment]
@Borda Can I assume [this](https://github.com/PyTorchLightning/pytorch-lightning/issues/929#issuecomment-608131633) is not relevant anymore ?
out of curiosity, what caused the issue in the first place? and what exactly was executed triggering the aforementioned trace, I could not locate any execution path leading to it...

**Comment by williamFalcon** [comment]
@bmartinn 
```
=================================== FAILURES ===================================
___________ [doctest] pytorch_lightning.loggers.trains.TrainsLogger ____________
059 
060     Examples:
061         >>> logger = TrainsLogger("lightning_log", "my-test", output_uri=".")  # doctest: +ELLIPSIS
062         TRAINS Task: ...
063         TRAINS results page: https://demoapp.trains.allegro.ai/.../log
064         >>> logger.log_metrics({"val_loss": 1.23}, step=0)
065         >>> logger.log_text("sample test")
066         sample test
067         >>> import numpy as np
068         >>> logger.log_artifact("confusion matrix", np.ones((2, 3)))
Expected nothing
Got:
    TRAINS Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring
```

Still very relevant. we get these sporadic failures in tests which are caused by trains.

**Comment by bmartinn** [comment]
@williamFalcon @Borda , for the CI test you have to use `TrainsLogger.set_bypass_mode(True)` otherwise it will have to have a backend-server to communicate with...
This is why we added it in the `test_trains.py` tests.

**Comment by Borda** [comment]
but the bypass is not it shall be used, right? meaning we do not want to have it in the example...

**Comment by bmartinn** [comment]
@Borda True but *Trains* does a lot of stuff in the background, monitoring mostly, and this will break CI as output will be changing from run to run. Also we cannot move everything to stderr, because this will break projects using *Trains* and monitoring stderr ... 

A few ideas on a solution:
1) Add a flag (OS environment) controlling the bypass mode (to be used in the CI, or using an OS environment that CI already sets, in order to automatically switch to bypass_mode)
2) Use set_bypass_mode in the doctest and add a remark that it should be used for "offline/CI mode"
3) Add a flag (OS environment) piping all the *Trains* messages to stderr instead of stdout.

I think (1) makes most sense, this should be a very quick fix.
What do you think?

**Pull request merged**
