### PR TITLE
tests: Remove usage of --flake8 flag

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
## What does this PR do?

I tried running this on my venv, but got the following:
```sh
$ python -m pytest tests -v --flake8
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --flake8
  inifile: <path>/pytorch-lightning/setup.cfg
  rootdir: <path>/pytorch-lightning
```

From looking at live-code that either doesn't use `--flake8` or has it
commented out, I assume this is now a dead flag.

## Before submitting
- (N/A) Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- (N/A) Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- (N/A) Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?

Yes :grimacing:

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Output of `pip freeze` for my `virtualenv`:
https://gist.github.com/EricCousineau-TRI/c3ce90bc372ba7fdc5388f459c6a62ab#file-pytorch-lightning-pr5909-pip-freeze-txt-L111

**Comment by Borda** [comment]
yes, for that you would need to install `pytest-flake8` which we dropped from requirements
so would you prefer to add it back to req. or remove it from examples?

**Comment by EricCousineau-TRI** [comment]
I think removing it from examples would be good!
(I have no stake in the `--flake8` flag, was just blindly copying and pasting from the `Makefile` and docs)

**Comment by Borda** [comment]
@EricCousineau-TRI thank you for sending your PR, just a minor issue coming from our side... we have swapped branches regarding upcoming feat 1.2, mind rebase on actual `master`? if needed see [How to fix PR with mixed base and target branches?](https://pytorch-lightning.readthedocs.io/en/latest/generated/CONTRIBUTING.html#how-to-fix-pr-with-mixed-base-and-target-branches)

**Comment by EricCousineau-TRI** [comment]
Done!

**Review by carmocca — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Comment by EricCousineau-TRI** [comment]
Failures appear unrelated to this PR - is this still able to auto-merge?

**Pull request merged**
