### PR TITLE
Fix docs typo

### PR DESCRIPTION
**Pull request by siahuat0727**
## What does this PR do?

Fixes docs typo

### CODE REVIEW

**Comment by rohitgr7** [comment]
@siahuat0727 There are more down below, can you fix those too here :)

**Comment by siahuat0727** [comment]
@rohitgr7 

Hihi, but I'm not sure is it all the single quotes here should be changed to double?

image

**Comment by awaelchli** [comment]
We unfortunately have not set any guidelines/agreement yet regarding the usage of the quotes. So far it is mixed across the documentation. I tried to approach this once but gave up, it is too much work and will drive you insane lol.

**Comment by Borda** [comment]
@@rohitgr7 @siahuat0727 mind draft a recommendation and update docs accordingly... 🐰

**Comment by rohitgr7** [comment]
Most users refer docs and highlighted text makes it more readable rather than plain text. I guess in possible cases single ` should be replaced with ``. Yeah, it's too much work to do it manually.

**Comment by Borda** [comment]
> Most users refer docs and highlighted text makes it more readable rather than plain text. I guess in possible cases single ` should be replaced with ``. Yeah, it's too much work to do it manually.

@awaelchli @rohitgr7 mind opening a new issue and lest discuss our future docs tyle direction there... 🐰 
cc: @PyTorchLightning/core-contributors

**Comment by Borda** [comment]
@siahuat0727 mind rebase on master, these issues shall be resolved there... 🐰

**Comment by siahuat0727** [comment]
I'm not familiar with these flows... Anyone with the will is welcome to take the lead!

**Pull request merged**
