### PR TITLE
Temporarily pin docker image used in GPU CI

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Pins the docker version to make some time to fix the following issues.

### Failures

1. We've been seeing hangs since around (see ones terminated in 1hr 40min):
Screen Shot 2022-06-07 at 12 51 03

2. and a horovod version mismatch issue (ones failing within 30-40min):
Screen Shot 2022-06-07 at 12 52 04

### Does your PR introduce any breaking changes? If yes, please list them.
None

## Before submitting

- [n/a] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [n/a] Did you make sure to **update the documentation** with your changes? (if necessary)
- [n/a] Did you write any **new necessary tests**? (not for typos and docs)
- [n/a] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [n/a] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or minor internal changes/refactors)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @tchaton @rohitgr7 @carmocca @akihironitta @borda

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Comment by akihironitta** [comment]
Just realised that there seems another issue 😞 I'll be AFK for a few hours, so if someone has an idea, any help is welcome while I'm away...

```
E           RuntimeError: CUDA error: the launch timed out and was terminated
```
https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=74048&view=logs&j=5ea502cf-d418-510c-3b5f-c4ba606ae534&t=1700365d-a4bb-5551-f2b3-aeaf0f75aa1c

**Comment by carmocca** [comment]
Might be caused by the fact that @Borda recently switched to K80 GPUs. I don't think this is a problem in our codebase.

**Comment by Borda** [comment]
> Might be caused by the fact that @Borda recently switched to K80 GPUs. I don't think this is a problem in our codebase.

for TM we just migrated to use LTS with CUDA 10.2, see https://github.com/PyTorchLightning/metrics/pull/1071

**Comment by akihironitta** [comment]
@Borda Thank you for working on the investigation of the above error in #13245.

Looked for similar issues on GH and SO, but all I could find so far is only https://github.com/NVIDIA/MinkowskiEngine/issues/235 (K80 and CUDA 10.2) which has no solution...

**Comment by Borda** [comment]
I think we can close it as it turned out the failing builds were unrelated to the used docker image but to the recent switch of resources... the NC12 used in the last few days has been likely sharing GPU with other machines... so switch to NC24 seem to resolve the issue :rabbit: 
see: https://docs.microsoft.com/en-us/azure/virtual-machines/nc-series
image

**Comment by Borda** [comment]
well, not sure then, but for while, all was almost fine (just one normally failing test) on master

**Pull request closed without merging**
