### PR TITLE
Fix global seed missing bug with DDP [WIP]

### LINKED ISSUE #3898: TypeError: expected str, bytes or os.PathLike object, not NoneType
## 🐛 Bug

I am summarizing the source of the issue to speedup the fix.
After this line of code 
https://github.com/PyTorchLightning/pytorch-lightning/blob/90929fa4333e5136020e9f9dcb7c1133e4c290f3/pytorch_lightning/accelerators/ddp_backend.py#L119

I have that `env_copy['PL_GLOBAL_SEED']` is `None` and having an environment variable set to None breaks `subprocess.Popen` here
https://github.com/PyTorchLightning/pytorch-lightning/blob/90929fa4333e5136020e9f9dcb7c1133e4c290f3/pytorch_lightning/accelerators/ddp_backend.py#L127

My fix at the moment is to add
```
if env_copy['PL_GLOBAL_SEED'] is None:
                del env_copy['PL_GLOBAL_SEED']
```
after 

https://github.com/PyTorchLightning/pytorch-lightning/blob/90929fa4333e5136020e9f9dcb7c1133e4c290f3/pytorch_lightning/accelerators/ddp_backend.py#L119

### Environment

```
* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.6.0
	- pytorch-lightning: 0.10.0rc1
	- tqdm:              4.48.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.7
	- version:           #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020
```

### PR DESCRIPTION
**Pull request by SeanNaren**
## What does this PR do?
Closes #3898.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by SeanNaren** [comment]
Awaiting response on the issue to create a test to ensure case is fixed.

**Review by awaelchli — CHANGES_REQUESTED** [review]
but this doesn't set the seed if it is not None, I think you need to keep the assignment

**Comment by williamFalcon** [comment]
@SeanNaren  good catch!
want to look through the other env vars there to make sure they aren't set if None?

**Comment by SeanNaren** [comment]
> but this doesn't set the seed if it is not None, I think you need to keep the assignment

@awaelchli Shouldn't this already be set in env_copy since we're doing a copy?

> want to look through the other env vars there to make sure they aren't set if None?

@williamFalcon Will do, I really want to add a test because I'm unsure how to reproduce this and what's the case where this pops up. Any ideas?

**Comment by williamFalcon** [comment]
yeah, that's hard haha... i don't know where this would happen either. It looks like if you set an envvar and use popopen then it will crash?

likely because a user calls popen themselves which is fine. the test is very involved though, we can talk offline about it.

**Comment by williamFalcon** [comment]
> but this doesn't set the seed if it is not None, I think you need to keep the assignment

i don't understand what you mean by this

**Comment by awaelchli** [comment]
Two cases: 
1) `"GLOBAL_SEED" not in os.environ`, then `del os.environ["GLOBAL_SEED"]` will throw KeyError.
2) `os.environ["GLOBAL_SEED"] = None`, then this fix works but the env variable should not get added in the first place.

**Comment by awaelchli** [comment]
As I said, if the user does not set the seed, running our mnist example with ddp gives

```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [2,3]
Traceback (most recent call last):
  File "pl_examples/basic_examples/mnist.py", line 112, in <module>
    cli_main()
  File "pl_examples/basic_examples/mnist.py", line 103, in cli_main
    trainer.fit(model, train_loader, val_loader)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 482, in fit
    self.accelerator_backend.setup(model)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/accelerators/ddp_backend.py", line 59, in setup
    self._call_children_scripts()
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/accelerators/ddp_backend.py", line 121, in _call_children_scripts
    del env_copy['PL_GLOBAL_SEED']
KeyError: 'PL_GLOBAL_SEED'
```

**Comment by SeanNaren** [comment]
Thanks @awaelchli realised we were missing a check... has already been fixed in https://github.com/PyTorchLightning/pytorch-lightning/pull/3927

**Pull request merged**
