### PR TITLE
[WIP] Accept Result checkpoint_on 0 tensors; exclude bool

### PR DESCRIPTION
**Pull request by abrahambotros**
## What does this PR do?

Fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/3099

- Result checkpoint_on typing updated to only accept Tensor or None;
  no longer accept bool.
- Remove checkpoint_on truthy check on Result init, which was causing
  0-valued Tensors to be incorrectly dropped.
- Add tests for checkpoint_on keeping zero and nonzero tensor values.
  Also update an existing test that was passing checkpoint_on=False to
  just pass None instead.
- (Also updates `TrainResult`'s `early_stop_on` typing from `Tensor` -> `Optional[Tensor]`; already defaults to None. This felt small and relevant, but can move to a different PR or exclude in general if we want.)

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by abrahambotros** [comment]
Ah, from the failing tests (namely, https://github.com/PyTorchLightning/pytorch-lightning/blob/a7705c8677b9e2b5105e26a38db9d1b650182576/tests/base/deterministic_model.py#L113 on master), I see an issue in my logic. The `checkpoint_on=False` apparently was to specifically prevent `checkpoint_on` from defaulting to the `minimize` value [here on master](https://github.com/PyTorchLightning/pytorch-lightning/blob/a7705c8677b9e2b5105e26a38db9d1b650182576/pytorch_lightning/core/step_result.py#L51). Marking this PR as WIP until there is a better workaround.

A couple possible options:
- Revert `checkpoint_on` to being one of `Tensor`, `bool`, `None`, and modify the conditional at https://github.com/PyTorchLightning/pytorch-lightning/blob/a7705c8677b9e2b5105e26a38db9d1b650182576/pytorch_lightning/core/step_result.py#L42 to be `if checkpoint_on is not None and checkpoint_on is not False`. This allows accepting 0-valued Tensors, allows the existing tests to pass, and allows defaulting to `minimize` if `checkpoint_on` is `None` instead of `False`.
- Entirely remove the behavior of defaulting to `minimize` when `checkpoint_on` is `None` and `minimize` is present. This can be done by simply removing the block at https://github.com/PyTorchLightning/pytorch-lightning/blob/a7705c8677b9e2b5105e26a38db9d1b650182576/pytorch_lightning/core/step_result.py#L51 , and would fix the failing tests.

To me, the latter seems cleaner since it removes some non-obvious behavior (checkpointing even if `checkpoint_on` is not given), but maybe this is breaking for others if they've assumed this. The former option above is easier for now, but leaves this non-obvious behavior in place. Any thoughts @Borda ?

**Comment by Borda** [comment]
@abefetterman how about this one, is it still WIP or ready to review? 🐰

**Comment by abefetterman** [comment]
> @abefetterman how about this one, is it still WIP or ready to review? 🐰

Tagged the wrong abe! @abrahambotros

**Comment by abrahambotros** [comment]
@abefetterman thanks fellow Abe haha

@Borda this one is not ready for review. If you have any thoughts to the questions above, let me know; those questions will have to be decided before I can make fixes to this PR and get it to the review stage. In the meantime, I'll close this PR so it's not taking up the queue, and we can continue discussing it until it's ready to open again.

**Pull request closed without merging**
