### PR TITLE
Re-attempt slurm auto resume call if non-shell call fails

### PR DESCRIPTION
**Pull request by titu1994**
Signed-off-by: smajumdar <titu1994@gmail.com>

## What does this PR do?

`SLURMConnector` attempts to call `scontrol requeue {job_id}` without a shell context, which on some HPC systems will raise the following (truncated) error - because the subprocess call is not under a shell context.

```python
...
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/slurm_connector.py", line 97, in sig_handler
    result = call(cmd)
  File "/opt/conda/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scontrol'
``` 

This PR attempts the default approach (subprocess call without shell context), and if it catches the above `FileNotFoundError` - will reattempt the command - but using a shell context this time. 

Fixes # (issue) <- N/A

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)  -- Discussed via Slack.
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by carmocca** [comment]
What are the disadvantages of calling with `shell=True` by default?

**Comment by titu1994** [comment]
> What are the disadvantages of calling with shell=True by default?
Technically should be no issue. I kept it for backward compatibility with earlier PTL versions.

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by titu1994** [comment]
About the tests, I dont think this PR should affect any of the tests. Can the tests be rerun or should I push an empty commit?

**Review by Borda — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Pull request merged**
