### PR TITLE
Fix docs metrics formatting

### LINKED ISSUE #4908: Formatting issues in metric docs
There are some formatting issues with the arguments (the incorrect blocks and apostrophes). I've yet to go through the whole metrics docs, noting them here as I find them for when I get a chance to fix them or if anyone wants to help!

Incorrect:
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#f1-func
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#fbeta-func

Correct examples:
https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#iou-func
(among others)

Related: #4837

Edit:
Also noticed that F1 has an unused beta arg that shouldn't be there (we have fbeta), though that's probably a separate issue.

### PR DESCRIPTION
**Pull request by s-rog**
Fixes #4908

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:  

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by ydcjeff** [comment]
Formatting still seems incorrect. Also we can fix F1 too. https://80481-178626720-gh.circle-artifacts.com/0/html/metrics.html#f1
preview - https://80481-178626720-gh.circle-artifacts.com/0/html/metrics.html#fbeta

**Comment by ydcjeff** [comment]
@s-rog  using 2 spaces after line break works.

**Comment by s-rog** [comment]
@ydcjeff ahhh I see, thanks!

**Comment by s-rog** [comment]
Fixed now :]
https://80500-178626720-gh.circle-artifacts.com/0/html/metrics.html#f1

**Review by ydcjeff — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM

**Review by SkafteNicki — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Pull request merged**
