### PR TITLE
Change the seq of on_train_batch_end, on_batch_end & on_train_epoch_end, on_epoch_end hooks

### LINKED ISSUE #5042: train_epoch_end called before epoch_end
### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L858

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by kaushikb11**
## What does this PR do?

Fixes #5042

The idea is to have a sequence of hooks ending from specific to generic.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by rohitgr7** [comment]
I'd suggest we should deprecate these 2 hooks and remove them in the future.

**Comment by Borda** [comment]
> I'd suggest we should deprecate these 2 hooks and remove them in the future. They are doing nothing different.

thoughts? @PyTorchLightning/core-contributors

**Comment by kaushikb11** [comment]
> > I'd suggest we should deprecate these 2 hooks and remove them in the future. They are doing nothing different.
> 
> thoughts? @PyTorchLightning/core-contributors

Will had made a valid point of what if we want to do something on batch end across all three steps? We would have to duplicate the code in three methods.

**Comment by ananyahjha93** [comment]
@Borda @kaushikb11 @rohitgr7  I can think of use cases for these hooks, so its better not to deprecate them.

**Comment by rohitgr7** [comment]
> > > I'd suggest we should deprecate these 2 hooks and remove them in the future. They are doing nothing different.
> > 
> > 
> > thoughts? @PyTorchLightning/core-contributors
> 
> Will had made a valid point of what if we want to do something on batch end across all three steps? We would have to duplicate the code in three methods.

one can still do:
```
def _on_epoch_end_common(...):
    ...

def on_train_epoch_end(...):
   self._on_epoch_end_common(...)..

def on_validation_epoch_end(...):
   self._on_epoch_end_common(...)

def on_test_epoch_end(...):
   self._on_epoch_end_common(...)
```
we can configure above by allowing `on_epoch_end` irrespective of the running_stage, but that is just one case. If some one wants to make the behavior same in case of train & val only, one has to use the above code structure.

my point here mostly users think of epoch as something that happens during training since epoch means nothing in case of validation/test. I have already seen many issues raised w.r.t to the difference between `on_validation_epoch_end` and `on_validation_end` and adding one more might create more confusion.

But if everyone thinks this is a good option, not a problem since I don't use this hook anymore :v:

**Comment by rohitgr7** [comment]
> @Borda @kaushikb11 @rohitgr7 I can think of use cases for these hooks, so its better not to deprecate them.

@ananyahjha93 mind share a use-case?

**Comment by ananyahjha93** [comment]
@rohitgr7 ``on_validation_epoch_end`` is ModelHook and ``on_validation_end`` is from callbacks so they definitely serve two different purposes. 

Keeping both ``on_epoch_end`` and ``on_train_epoch_end`` if say I just have to plot GAN generated images at the end of each train, val and test loops, I can do that with ``on_epoch_end`` instead of repeating my code.

**Comment by rohitgr7** [comment]
> @rohitgr7 `on_validation_epoch_end` is ModelHook and `on_validation_end` is from callbacks so they definitely serve two different purposes.
> 
> Keeping both `on_epoch_end` and `on_train_epoch_end` if say I just have to plot GAN generated images at the end of each train, val and test loops, I can do that with `on_epoch_end` instead of repeating my code.

@ananyahjha93 it's a callback hook too: https://github.com/PyTorchLightning/pytorch-lightning/blob/50fd4879a9d4f8b83ace27ee580b7633d4746361/pytorch_lightning/callbacks/base.py#L86

**Comment by ananyahjha93** [comment]
@rohitgr7 I have code in swav which utilizes both callback and model hook version of this function. So, deprecating one of them will probably change a lot of code not just in our repositories but other people's repositories as well. 

Callbacks I would say serve a slightly different purpose at times than just calling the same function code in ModelHook's version of that method.

**Comment by rohitgr7** [comment]
yeah valid point, but one has to update the code even if we change it's behavior now.

**Comment by ananyahjha93** [comment]
@rohitgr7 the reordering ideally should not change any code. Deprecating this would probably.

**Comment by rohitgr7** [comment]
> @rohitgr7 the reordering ideally should not change any code. Deprecating this would probably.

I meant changing it's behavior to run irrespective of train/val/test will require a code change. Re-ordering is not a problem.

**Review by s-rog — APPROVED** [review]

**Comment by s-rog** [comment]
@kaushikb11 Training hooks changes LGTM, do validation hooks have a similar ordering issue?

**Review by tchaton — APPROVED** [review]
Hey @kaushikb11, great work !

**Comment by rohitgr7** [comment]
should we reorder `on_epoch_start/on_batch_start` too? currently it's
```
on_epoch_start
on_train_epoch_start
...
...
on_train_epoch_end
on_epoch_end
```
same for `on_batch_start`

**Comment by kaushikb11** [comment]
@rohitgr7 We could move the discussion for `on_spoch_start` hook in the Issues.

**Review by carmocca — APPROVED** [review]

**Pull request merged**
