### PR TITLE
Conda: PT 1.8

### LINKED ISSUE #4587: Segmentation fault on import with RTX 3090
I've just installed an RTX 3090 in my DL machine. I have the following dependencies installed

Driver Version: 455.32
Cuda Version: 11.0
Python Version: 3.8.6
Pytorch Version: 1.7.0+cu11  (`pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`)

After initially having issues (installed cuda-11-1 rather than cuda-11-0) torch appears to work. I ran a  CIFAR10 example on GPU, I verified with nvidia-smi that it was indeed running on the GPU.

I installed the latest pytorch-lightning, i.e. `pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade` but I cannot import, i.e.

```
>>> import pytorch_lightning as pl
Segmentation fault (core dumped)
```

Should this work? If so is there anything I've done wrong? If not, is there anything I can do to assist in tracking down the issue. Ironically I've just discovered that the CRF decoder is quicker on CPU (at least cf my older 1080Ti) so I don't need the GPU backend but atm I crashing on import is problematic ;)

### LINKED ISSUE #4596: upgrading PL via pip uninstalls pytorch-1.8
### To Reproduce

```
$ pip install pytorch-lightning -U
[...]
Installing collected packages: torch, pytorch-lightning
  Attempting uninstall: torch
    Found existing installation: torch 1.8.0.dev20201106+cu110
    Uninstalling torch-1.8.0.dev20201106+cu110:
      Successfully uninstalled torch-1.8.0.dev20201106+cu110
```

### Expected behavior

It shouldn't uninstall pytorch-1.8.

Nvidia RTX-30* don't work with pytorch < 1.8.

### Environment

```
* CUDA:
        - GPU:
                - GeForce RTX 3090
                - GeForce GTX 1070 Ti
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.19.4
        - pyTorch_debug:     True
        - pyTorch_version:   1.7.0
        - pytorch-lightning: 1.0.5
        - tqdm:              4.50.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.5
        - version:           #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
```

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

PT 1.7 was removed from pytorch-nightly channel but still missing on standard pytorch...
Resolves #4596
resolves #4587

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
good point here https://github.com/actions/toolkit/issues/399#issuecomment-721060990

**Comment by ydcjeff** [comment]
@Borda how about this kind of nightly testing?

**Comment by Borda** [comment]
@ydcjeff I would probably just add testing in Conda env as it will be just one extra test and not 3 (per OS) * 2 (py) = 6
also, it would be consistent with other PT versions we are testing...

**Comment by ydcjeff** [comment]
Ok @Borda sorry for the inconvenience.

**Comment by Borda** [comment]
> Ok @Borda sorry for the inconvenience.
> Also you may want to unfreeze torchvision too.

all good, if you want I left a few todos, basically to check how could we install PT with pip, I could not find a solution... (the only one which I do not like is to download the wheel locally and try install but not sure about OS/Py/versions compatibility)

**Review by ydcjeff — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
Great work there !

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
