### PR TITLE
Pin `coverage<6.3`

### LINKED ISSUE #11633: `test_signal_handlers_restored_in_teardown` failing on mac and linux
## 🐛 Bug
In all ongoing PRs,`test_signal_handlers_restored_in_teardown` fails, and a few test cases after, the job is terminated.

```
tests/trainer/connectors/test_signal_connector.py::test_signal_handlers_restored_in_teardown FAILED [ 79%]
tests/trainer/connectors/test_signal_connector.py::test_fault_tolerant_sig_handler[False-False] PASSED [ 79%]
tests/trainer/connectors/test_signal_connector.py::test_fault_tolerant_sig_handler[False-True] PASSED [ 79%]
Terminated
tests/trainer/connectors/test_signal_connector.py::test_fault_tolerant_sig_handler[True-False] 
Error: Process completed with exit code 143.
```

### To Reproduce
https://github.com/PyTorchLightning/pytorch-lightning/actions/runs/1751182495

### Expected behavior
- No test failure of the test case above.
- No termination of CI jobs

### Additional context

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Fixes #11633.

### Does your PR introduce any breaking changes? If yes, please list them.
None

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [n/a] Did you make sure to **update the documentation** with your changes? (if necessary)
- [n/a] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [n/a] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

### CODE REVIEW

**Comment by akihironitta** [comment]
Here's the minimal reproducible command and its error msg

```console
$ coverage --version
Coverage.py, version 6.3 with C extension
Full documentation is at https://coverage.readthedocs.io
$ coverage run -m pytest tests/trainer/connectors/test_signal_connector.py::test_signal_handlers_restored_in_teardown -vv
=============================================================== test session starts ===============================================================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /home/nitta/.pyenv/versions/miniconda3-latest/envs/dev-pl39/bin/python
cachedir: .pytest_cache
rootdir: /home/nitta/work/github.com/PyTorchLightning/pytorch-lightning, configfile: setup.cfg
plugins: rerunfailures-10.2, hydra-core-1.1.1
collected 1 item                                                                                                                                  

tests/trainer/connectors/test_signal_connector.py::test_signal_handlers_restored_in_teardown FAILED                                         [100%]

==================================================================== FAILURES =====================================================================
____________________________________________________ test_signal_handlers_restored_in_teardown ____________________________________________________

    @RunIf(skip_windows=True)
    @mock.patch.dict(os.environ, {"PL_FAULT_TOLERANT_TRAINING": "1"})
    def test_signal_handlers_restored_in_teardown():
        """Test that the SignalConnector restores the previously configured handler on teardown."""
>       assert signal.getsignal(signal.SIGTERM) is signal.SIG_DFL
E       assert <bound method Coverage._on_sigterm of <coverage.control.Coverage object at 0x7f75a9ee05b0>> is <Handlers.SIG_DFL: 0>
E        +  where <bound method Coverage._on_sigterm of <coverage.control.Coverage object at 0x7f75a9ee05b0>> = <function getsignal at 0x7f75a9d98820>(<Signals.SIGTERM: 15>)
E        +    where <function getsignal at 0x7f75a9d98820> = signal.getsignal
E        +    and   <Signals.SIGTERM: 15> = signal.SIGTERM
E        +  and   <Handlers.SIG_DFL: 0> = signal.SIG_DFL

tests/trainer/connectors/test_signal_connector.py:34: AssertionError
============================================================= short test summary info =============================================================
FAILED tests/trainer/connectors/test_signal_connector.py::test_signal_handlers_restored_in_teardown - assert <bound method Coverage._on_sigterm ...
========================================================== 1 failed, 4 warnings in 0.53s ==========================================================
```

**Review by awaelchli — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Review by ananthsub — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Review by daniellepintz — APPROVED** [review]
Thanks for fixing this issue! Can we override the queued GPU test to merge this?

**Comment by akihironitta** [comment]
> Can we override the queued GPU test to merge this?

@daniellepintz I don't think that's feasible without the repo "admin" privilege since it's one of the jobs that are required to pass before merging. In my understanding, #11634 blocks all PRs basically...

**Pull request merged**
