### PR TITLE
Fix root node resolution for SLURM cluster with dash in host name

### LINKED ISSUE #1943: `TrainerDDPMixin.resolve_root_node_address` fails if the host name contains a dash
## 🐛 Bug

When running under SLURM, if the nodes host names contains `-`, `MASTER_ADDR` omits the number part of the master host name (which of course makes everything else fail).

if `MASTER_ADDR` is not given, pl infers it from the node list using [`TrainerDDPMixin.resolve_root_node_address`](https://github.com/PyTorchLightning/pytorch-lightning/blob/8f6b7a2b4fea9b7bd0b873f5973e6364b3981412/pytorch_lightning/trainer/distrib_data_parallel.py#L427)

### To Reproduce

- Use pl in a SLURM cluster where nodes host names contains at least a dash (e.g. `jean-zay-ia810`)

The job should fail with something like this

```text
  File "<snip>/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 834, in fit
    self.ddp_train(task, model)
  File "<snip>/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 353, in ddp_train
    model.init_ddp_connection(self.proc_rank, self.world_size, self.is_slurm_managing_tasks)
  File "<snip>/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 957, in init_ddp_connection
    torch_distrib.init_process_group(torch_backend, rank=proc_rank, world_size=world_size)
  File "<snip>/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "<snip>/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Name or service not known
```
In my case, looking into `os.environ` gives `'SLURM_NODELIST': 'jean-zay-ia[810,817-819]'` and `'MASTER_ADDR': 'jean-zay-ia'`.

The root cause being that

```python-console
>>> resolve_root_node_address("jean-zay-ia[810,817-819]")
'jean-zay-ia'
```

Fixing it should not be hard, should I submit a PR?

### PR DESCRIPTION
**Pull request by LoicGrobol**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
  - No need for a bugfix, right?
- [ ] Did you write any new necessary tests?
  - Not sure if this need any new tests as the general behaviour of the function is already tested  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
Fixes #1943 

For now this is about the minimal change to fix the issue, but it might be better to completely rewrite the function as

```python
def resolve_root_node_address(root_node):
    """Extract a root node from a SLURM node list."""
    m = re.match(r"(?P<name>.*?)\[(?P<number>\d+)(-\d+)?(,.*)?\]", root_node)
    if not m:
        return root_node
    if m.group("number") is None:
        return m.group("name")
    return m.group("name") + m.group("number")
```

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
Don't we have tests for this? Mind adding a test just to make sure we don't break the other cases?

**Comment by LoicGrobol** [comment]
@williamFalcon Well it's already tested (but weirdly enough, it's in [the amp tests](https://github.com/PyTorchLightning/pytorch-lightning/blob/3af4994d5a84bc80738b50983b4b42c3eb946433/tests/models/test_amp.py#L88) so maybe it would be worth it to move these elsewhere) for a basic case (`abc[23-24, 45-40, 40]` and some variants). I don't mind adding test cases with a dash or other quirks but I am not sure it is really interesting so you tell me :-)

**Comment by williamFalcon** [comment]
@LoicGrobol great! thanks for the PR :)

**Comment by LoicGrobol** [comment]
@williamFalcon Haha, just scratching my itch, thanks for merging :-)

**Pull request merged**
