### PR TITLE
Removed test_dataloader call in check_testing_model_configuration

### LINKED ISSUE #1562: test_dataloader called during check_testing_model_configuration
## 🐛 Bug

When testing a model that has been loaded using the `resume_from_checkpoint` Trainer flag (note: `.fit()` has **not** been called yet in this case), the `check_testing_model_configuration` method [calls](https://github.com/PyTorchLightning/pytorch-lightning/blob/c1c6e3b6c988c690f9e2cd5726da4ab3402dbd03/pytorch_lightning/trainer/trainer.py#L1026) `test_dataloader()`, which results in undefined attribute errors if the test dataloader depends on stuff set during `prepare_data` (which is called at the beginning of `fit`)

### To Reproduce

1. Initialize a Trainer like `trainer = Trainer(model, resume_from_checkpoint="...", ...)` (make sure `.fit` is not called yet)
2. Run `trainer.test()`
3. If test dataloader depends on prepare_data, errors will be thrown that trace back to `check_testing_model_configuration`

### Additional context

This seems like It could be fixed with a simple change--remove the `model.test_dataloader()` call from this [line](https://github.com/PyTorchLightning/pytorch-lightning/blob/c1c6e3b6c988c690f9e2cd5726da4ab3402dbd03/pytorch_lightning/trainer/trainer.py#L1026) and replace `hasattr` with `is_overriden` call . I can submit a PR if this solution is acceptable.

### PR DESCRIPTION
**Pull request by kevinc13**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?
Fixes #1562 .

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by kevinc13** [comment]
Seems like failing tests are setting test_dataloader function to a lambda (actually overriding it), causing the check to pass when it shouldn't. Not sure best way to proceed here

**Comment by jeremyjordan** [comment]
@Borda I know there was discussion regarding `model.test_dataloader = lambda: None` vs `model.test_dataloader = LightningModule.test_dataloader`, can you remind me why we chose the former and not the latter? we need to document our test conventions

**Comment by Borda** [comment]
> @Borda I know there was discussion regarding `model.test_dataloader = lambda: None` vs `model.test_dataloader = LightningModule.test_dataloader`, can you remind me why we chose the former and not the latter? we need to document our test conventions

I think that it was just @williamFalcon recommendation to use the None/labda None...
I would prefer to use the `LightningModule.` as it is cleaner to see that the particular method was not defined

**Comment by jeremyjordan** [comment]
this PR provides an example which motivates the usage of `model.test_dataloader = LightningModule.test_dataloader` (for tests which tests code that check for methods being overwritten)

**Comment by kevinc13** [comment]
@Borda @jeremyjordan Modified the existing tests to use `LightningModule.test_dataloader`

**Comment by williamFalcon** [comment]
@Borda i actually would rather not use lambda... there is an empty one we can use. I'm not sure where this idea came from...

**Comment by Borda** [comment]
the lambda was used for dataloader method as it is called and `None` can not be called so you needed to wrap it as an empty function

**Pull request merged**
