### PR TITLE
Pin Docker image for testing on GPUs

### LINKED ISSUE #12314: AttributeError: module 'horovod.torch' has no attribute 'nccl_built'
The `PL.pytorch-lightning (GPUs)` CI job is failing with `AttributeError: module 'horovod.torch' has no attribute 'nccl_built'`

https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=61024&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=059bb337-5de1-5e6a-4c56-42f55a328c0e

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Temporary fix for #12314. For unblocking other PRs, tries to pin the most recent docker image in which the tests were running successfully.

Specifically, the one used in https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=61012&view=logs&j=3afc50db-e620-5b81-6016-870a6976ad29&t=bd0a18db-4e66-438b-93e9-00d86028355e.

### Does your PR introduce any breaking changes? If yes, please list them.
None

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [n/a] Did you make sure to **update the documentation** with your changes? (if necessary)
- [n/a] Did you write any **new necessary tests**? (not for typos and docs)
- [n/a] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [n/a] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @tchaton @rohitgr7 @akihironitta @carmocca @borda

### CODE REVIEW

**Comment by akihironitta** [comment]
The CI job hasn't been finished yet, but it seems alright so far.

**Review by kaushikb11 — APPROVED** [review]

**Review by daniellepintz — APPROVED** [review]
Thanks @akihironitta!

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
also curious how we uploaded corrupted image as each image at the end shall have its own testing...

**Comment by akihironitta** [comment]
@Borda The corrupted image doesn't raise any error as seen in this "successful run" [build-CUDA (3.7, 1.8)](https://github.com/PyTorchLightning/pytorch-lightning/runs/5567550527?check_suite_focus=true) for instance. Building itself was successful, but since there's no sanity check (`import horovod.torch` raises a warning but not an exception) at the moment in the Dockerfile, the built image got uploaded to the hub. As you've already done in your PR, something like `from horovod.torch import nccl_built; nccl_built()` should avoid this issue since it raises an exception if the dependency isn't installed in the image.

**Review by awaelchli — APPROVED** [review]

**Comment by awaelchli** [comment]
Thank you so much @akihironitta

**Pull request merged**
