### PR TITLE
build more docker configs

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

lets guild more base images so we can lay over PL on top of it...
Follow-up of #3074 

**TODO**
- [x] increase the nb check in mergify...

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
seems that Cuda docker always installs the latest version...

**Comment by Borda** [comment]
failing install Horovod `subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.`

**Comment by tgaddair** [comment]
@Borda can you point me to the failing test logs?  I can't find them in the last set of tests.

**Comment by Borda** [comment]
> @Borda can you point me to the failing test logs? I can't find them in the last set of tests.

maybe it is a false alarm as the tests. seems to be failing randomly on other places... so I ll let you know if I find a solid example...

**Comment by Borda** [comment]
strange that the TPU passes to...

**Review by nateraw — APPROVED** [review]
LGTM. good work Jirka 😄

**Review by teddykoker — APPROVED** [review]
LGTM, presume this is needed for nightly support

**Review by ananyahjha93 — APPROVED** [review]

**Pull request merged**
