### PR TITLE
Update slack link

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

Fixes #\<issue_number>

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @rohitgr7

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Review by Borda — APPROVED** [review]
pls check when generating this link that it is without expiration :rabbit:

**Comment by rohitgr7** [comment]
> pls check when generating this link that it is without expiration 🐰

I didn't generate this. Can you confirm with Will? the old one seems to be without any expiration date since it's still working.

**Comment by Borda** [comment]
> > pls check when generating this link that it is without expiration rabbit
> 
> I didn't generate this. Can you confirm with Will? the old one seems to be without any expiration date since it's still working.

it is correct, just as discussed, lets create and use a permanent one :)

**Review by akihironitta — APPROVED** [review]

**Comment by akihironitta** [comment]
> pls check when generating this link that it is without expiration 🐰

I remember even if it's generated without expiration, it'll be expired after a certain number of people join Slack with the link, so I guess maybe we need to have a permanent proxy link and update its redirection occasionally.

**Pull request merged**
