### PR TITLE
Fixes EarlyStopping With Precision=16

### LINKED ISSUE #1815: Set precision=16 (using apex) would cause early stopping break
## 🐛 Bug

The current early stopping monitor initilize by comparing if the function monitor_op is equal to torch.lt.

`self.best = torch_inf if self.monitor_op == torch.lt else -torch_inf`

https://github.com/PyTorchLightning/pytorch-lightning/blob/12138ced7c730b8b1a72f798ce74f1452ec8f4e0/pytorch_lightning/callbacks/early_stopping.py#L110

However when intializing with the apex, it seems that the torch.lt would change and this evaluation would be always false and thus the `self.best` is intialized to -inf instead of +inf.

### To Reproduce

```
import torch
from pytorch_lightning.callbacks.early_stopping import EarlyStopping
import apex.amp as amp

es = EarlyStopping()
es.monitor_op == torch.lt
Out[6]: True

model = torch.Linear(5, 5).to('cuda')
optimizers = torch.optim.Adam(model.parameters(), lr=1e-3)
amp.initialize(model, optimizers)

es.monitor_op == torch.lt
Out[22]: False
```

And this bug leads to the initialization of `self.best` to be -inf instead of inf

### Expected behavior

`self.best` should be initialized to inf instead of -inf.

### Environment

* CUDA:
        - GPU:
                - TITAN Xp
                - Quadro P400
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.4.0
        - pytorch-lightning: 0.7.5
        - tensorboard:       2.1.1
        - tqdm:              4.43.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.6.10
        - version:           #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019
### Additional context

I bump into this bug after downloading from the master branch couple days ago. I would guess the old version is fine but did not test it.

### PR DESCRIPTION
**Pull request by authman**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you write any new necessary tests?  Sorta, see below

## What does this PR do?
Fixes #1815 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## The Problem
The problem and code to reproduce is available in the Issue #1815 

Here is some common sense / sanity code to validate the one-liner patch works according to specification:

```
import torch
import numpy as np
import apex.amp as amp
from pytorch_lightning.callbacks.early_stopping import EarlyStopping
torch_inf = torch.tensor(np.Inf)
es = EarlyStopping(mode='min')


torch_inf if es.monitor_op == torch.lt else -torch_inf 
Out[1]: tensor(inf)

-torch_inf if es.monitor_op(torch.Tensor(1), torch.Tensor(2))[0].item() else torch_inf
Out[2]: tensor(inf)

es = EarlyStopping(mode='max')
torch_inf if es.monitor_op == torch.lt else -torch_inf 
Out[3]: tensor(-inf)

-torch_inf if es.monitor_op(torch.Tensor(1), torch.Tensor(2))[0].item() else torch_inf
Out[4]: tensor(-inf)


es = EarlyStopping(mode='min')
model = torch.nn.Linear(5, 5).to('cuda')
optimizers = torch.optim.Adam(model.parameters(), lr=1e-3)
amp.initialize(model, optimizers)
torch_inf if es.monitor_op == torch.gt else -torch_inf
Out[5]: tensor(-inf)

# NOTE!! The above is incorrect, and is what this patch fixed

-torch_inf if es.monitor_op(torch.Tensor(1), torch.Tensor(2))[0].item() else torch_inf
Out[5]: tensor(inf)
```

### CODE REVIEW

**Comment by authman** [comment]
Can the cancelled CICD check get re-ran? Looks like it was a freak time-out.

**Comment by jeremyjordan** [comment]
> However when intializing with the apex, it seems that the torch.lt would change and this evaluation would be always false and thus the self.best is intialized to -inf instead of +inf.

what does the value change to when amp is initialized? if it was something like `torch.amp_lt` i think it would be more readable to do something like:

```
self.best = torch_inf if self.monitor_op in (torch.lt, torch.amp_lt) else -torch_inf
```

also, we should add a test for this under the tests for amp to prevent future regressions :)

**Comment by Borda** [comment]
> Can the cancelled CICD check get re-ran? Looks like it was a freak time-out.

yes, it can, tell me which one...

**Comment by authman** [comment]
> what does the value change to when amp is initialized? if it was something like torch.amp_lt

It decorates them with some kind of method. See: https://github.com/NVIDIA/apex/blob/47144979b3a348b06e06ebbb7eccfd375936aef5/apex/amp/amp.py#L113-L121

Also, this only the case for amp_level='O1'. With O2 and O3, the model weights themselves rather than the ops are casted as fp16, and so we don't actually encounter the issue presented in #1815. Due to these reasons, I thought it simpler to just evaluate the method directly. That way, it doesn't matter what they change it to, the result is based off of the function implementation rather than definition.

> also, we should add a test for this under the tests for amp to prevent future regressions :)

Makes sense. But also goes in line with thought process above / future proofing.

**Comment by williamFalcon** [comment]
@authman thank you!

**Comment by awaelchli** [comment]
This is highly incorrect. This has to be reverted. 

1. torch.Tensor(1) gives a 1d uninitialized tensor, a comparison with torch.Tensor(2) makes NO sense
2. the sign was flipped without explanation
3. For every bug fix there should be a test that satisfies the two conditions (a) test fails on master without the fix, (b) test passes with the fix

**Comment by authman** [comment]
You're right about the uninit tensor. This should have been es.monitor_op(torch.Tensor(**[1]**), torch.Tensor(**[2]**)).item(). I will add the requested two unit tests.

**Pull request merged**
