### PR TITLE
Update docs regarding support of tuner with DDP

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Part of #10560.

For more than one year, the docs have mentioned since #1835 that tuner with DDP is not supported.
> For the moment, this feature only works with models having a single optimizer. LR Finder support for DDP and any of its variations is not implemented yet. It is coming soon.
> https://pytorch-lightning.readthedocs.io/en/latest/advanced/lr_finder.html?highlight=lr%20finder

> Batch size finder is not yet supported for DDP or any of its variations, it is coming soon.
> https://pytorch-lightning.readthedocs.io/en/latest/advanced/training_tricks.html?highlight=tuner#auto-scaling-of-batch-size

However, there seems no reason why Lightning doesn't support tuner with DDP.

### Does your PR introduce any breaking changes? If yes, please list them.
None

## Before submitting

- [n/a] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [n/a] Did you make sure to **update the documentation** with your changes? (if necessary)
- [n/a] Did you write any **new necessary tests**? (not for typos and docs)
- [n/a] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [n/a] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda @akihironitta

### CODE REVIEW

**Comment by akihironitta** [comment]
Not sure if this PR should land in 1.5.x or 1.6.

**Review by awaelchli — APPROVED** [review]
I haven't tested it, we don't have tests for it, and I wouldn't be surprised if a process hangs :)

**Comment by tchaton** [comment]
Hey @akihironitta, we should test this before removing the disclaimer. I would prefer not to merge this PR.

**Comment by akihironitta** [comment]
Closing this PR for now.

**Pull request closed without merging**
