### PR TITLE
default test logger

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Setting TensorBoard as default logger even for tests

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
any experince with faling in spawn lock?
```
>       result = trainer.fit(model)

tests/models/test_restore.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pytorch_lightning/trainer/trainer.py:736: in fit
    mp.spawn(self.ddp_train, nprocs=self.num_gpus, args=(model,))
/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py:162: in spawn
    process.start()
/opt/conda/lib/python3.7/multiprocessing/process.py:112: in start
    self._popen = self._Popen(self)
/opt/conda/lib/python3.7/multiprocessing/context.py:284: in _Popen
    return Popen(process_obj)
/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/conda/lib/python3.7/multiprocessing/popen_fork.py:20: in __init__
    self._launch(process_obj)
/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <SpawnProcess(SpawnProcess-15, initial)>
file = <_io.BytesIO object at 0x7fe9bc0d1e90>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       TypeError: can't pickle _thread.lock objects
```

**Comment by jeremyjordan** [comment]
> any experince with faling in spawn lock?

@Borda yes i've seen that on my machine too...

**Comment by Borda** [comment]
> > any experince with faling in spawn lock?
> 
> @Borda yes i've seen that on my machine too...

mind help debugging, because I am not able to replicate it locally without GPUs

**Comment by Borda** [comment]
ok, the pickle solved, but another remaining:
```
tests/trainer/test_dataloaders.py:558: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pytorch_lightning/trainer/data_loading.py:109: in auto_add_sampler
    sampler = DistributedSampler(dataloader.dataset)
/opt/conda/lib/python3.7/site-packages/torch/utils/data/distributed.py:30: in __init__
    num_replicas = dist.get_world_size()
/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:586: in get_world_size
    return _get_group_size(group)
/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:202: in _get_group_size
    _check_default_pg()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _check_default_pg():
        """
        Helper that checks if the default ProcessGroup has been initializd, with
        assertion
    
        """
        assert _default_pg is not None, \
>           "Default process group is not initialized"
E       AssertionError: Default process group is not initialized
```

**Comment by Borda** [comment]
@williamFalcon ^^

**Comment by williamFalcon** [comment]
@Borda this PR is huge? why is this messing with ddp?

**Comment by Borda** [comment]
Not sure, I was just replacing test tube by trnsorboard as default logger and fixing all issues to get it pass... The cpu-ddp was using custom wrap func which I replaced by the standard one from python native...

**Pull request merged**
