### PR TITLE
Apply untoggle_optimizer when result is None

### LINKED ISSUE #5723: Wrong `requires_grad` state after `return None` with multiple optimizers
## 🐛 Bug

When I use multiple optimizers, I cannot use `return None` to skip one step, since it would cause error. I found that it was because `requires_grad` property of the corresponding network is not set to `True`. 

For instance, with two optimizers:

```
  def configure_optimizers(self):
      optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
      optimizer2 = torch.optim.SGD(self.layer2.parameters(), lr=0.1)
      return [optimizer, optimizer2], []
```

In the training step, 
```
def training_step(self, batch, batch_idx, optimizer_idx):
    print('optimizer_idx',optimizer_idx)
    print('layer:',next(self.layer.parameters()).requires_grad)
    print('layer2:',next(self.layer2.parameters()).requires_grad)
    ...
    return loss # loss is not None
```
we should get
```
optimizer_idx 0
layer: True
layer2: False

optimizer_idx 1
layer: False
layer2: True
...
```

However, if we return `None`, i.e.
```
def training_step(self, batch, batch_idx, optimizer_idx):
    ...
    return None
```
we would get
```
optimizer_idx 0
layer: True
layer2: False

optimizer_idx 1
layer: False
layer2: False
```
since returning `None` causes failure to change `requires_grad` state of layer2. 

### To Reproduce

https://colab.research.google.com/drive/1kRTKix1bxCOBJY0eR0h8jOVaRxt7L_6g?usp=sharing

### Expected behavior

`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

### Environment

* CUDA:
	- GPU:
		- GeForce RTX 2080 SUPER
	- available:         True
	- version:           11.0
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1
	- pytorch-lightning: 1.1.6
	- tqdm:              4.50.2
* System:
	- OS:                Windows
	- architecture:
		- 64bit
		- WindowsPE
	- processor:         Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
	- python:            3.8.5
	- version:           10.0.18362

### PR DESCRIPTION
**Pull request by deng-cy**
## What does this PR do?

Fixes #5723.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by carmocca** [comment]
Can you write a test that fails without the changes here?

**Comment by deng-cy** [comment]
> Can you write a test that fails without the changes here?

I have some difficulty to find relevant test files. Is there any test when `training_step` returns None? I can start to work from there.

**Comment by carmocca** [comment]
See: https://github.com/PyTorchLightning/pytorch-lightning/blob/c6b1a7264321ca81682dc1aaa4ba21edce67c399/tests/trainer/data_flow/test_train_loop_flow_scalar_1_0.py#L207-L272

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@deng-cy  there won't be any more releases in 1.1.x so I have changed your destination branch to feat 1.2
pls, there is no need to close this PR, just rebase on the target branch, or maybe easier just cherry-pick the commit (@kaushikb11 will help you if needed)

**Comment by tchaton** [comment]
Hey @deng-cy,

Can you rebase your PR onto master ?

Best,
T.C

**Comment by Borda** [comment]
@tchaton any reason for closing?

**Comment by kaushikb11** [comment]
@Borda https://github.com/PyTorchLightning/pytorch-lightning/pull/5983

**Comment by deng-cy** [comment]
Sorry I have been too busy recently to write a test case for this. Thanks for the new PR. I will look into details as soon as possible.

**Pull request closed without merging**
