### PR TITLE
Add a test to try to catch running out of memory

### PR DESCRIPTION
**Pull request by EricWiener**
https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1628607162358400?thread_ts=1628540065.338800&cid=CRBLFHY79

## What does this PR do?

Fixes #\<issue_number>

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by carmocca** [comment]
Hi @EricWiener 

I have pushed a commit modifying the GPU CI file so only your test runs.

Saving the trees and your time :)
Hope that helps.

**Comment by EricWiener** [comment]
@carmocca thank you!

**Comment by tchaton** [comment]
Hey @EricWiener,

Any updates on this PR ?

Best,
T.C

**Comment by EricWiener** [comment]
Hey @tchaton,

Sorry for the delay. I still have an issue with training freezing (but not erroring out) if the number of workers is too high and uses up all the memory. The data loader will time out, but the DDP won't be stopped and will just wait. This test was meant to show that was an issue. I bypassed this issue by decreasing the number of workers and using an Ampere GPU node instead of Turing (which also resulted in an increase of 200 GB of RAM). I will try to get an update on this test within 1-2 weeks.

Thanks,
Eric

**Comment by EricWiener** [comment]
Sorry - have had much less time than I expected to have. This is still a major issue, but haven't had a chance to get to it

**Pull request closed without merging**
