### PR TITLE
Use xm.save to save model on TPU

### LINKED ISSUE #2700: Checkpointing is broken on TPUs
## 🐛 Bug

Pytorch/XLA saves checkpoints using the following syntax which is not supported in pytorch-lightning.
```
import torch_xla.core.xla_model as xm
xm.save()
```
It is a little tricky to support because `xm.save()` has a barrier inside it and it checks for rank=0 while `torch.save` doesn't. This means `torch.save` should be called only on the process with rank=0 (which pytorch-lighting does) but `xm.save()` should be called by all processes (or it will wait forever at the barrier). This means pytorch-lightning code that checks for the rank ([here](https://github.com/PyTorchLightning/pytorch-lightning/blob/0.8.5/pytorch_lightning/callbacks/model_checkpoint.py#L265-L269) will need to be switched off on TPUs.

### To Reproduce

1. Train any model on TPUs using PyTorch/XLA with `ptl.Trainer(checkpoint_callback=[ModelCheckpoint(...)], num_tpu_cores=8)`
2. Wait until the model saves one checkpoint then kill the process
3. Try to load the saved checkpoint with `ptl.Trainer(resume_from_checkpoint='path_to_saved_checkpoint', num_tpu_cores=8)`

### Expected behavior

Loading checkpoint successfully. 

### Environment

pytorch-lightning==v0.8.5

### Additional Context

Thanks to @matt-peters for finding the bug and suggesting the solution mention below.

### PR DESCRIPTION
**Pull request by lezwon**
## What does this PR do?
Fixes #2700 

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by edenlightning** [comment]
Hey @lezwon, any ETA on this fix?

**Comment by lezwon** [comment]
@edenafek it has a lot of breaking changes. Also there was an issue due to which it was hanging at the 4th epoch.
Had it on pause due to the refactors happening. Will try to get this done on the weekend. :)

**Comment by Borda** [comment]
@lezwon how is this going, can we get it done today?
pls mind rebase on master... maybe it would be easier for you to squash it fist and then rebase...

**Comment by edenlightning** [comment]
@lezwon can we revive this fix?

**Comment by lezwon** [comment]
@edenlightning I'm using a new branch to fix this issue. Will close this one as it is stale.

**Comment by Borda** [comment]
@lezwon mind link here the new PR?

**Pull request closed without merging**
