### PR TITLE
[CI] Move DeepSpeed into CUDA image, remove DeepSpeed install from azure

### PR DESCRIPTION
**Pull request by SeanNaren**
## What does this PR do?

Moves DeepSpeed to be installed within the CUDA image, and the azure pipeline to not install it everytime.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by carmocca — APPROVED** [review]

**Review by Borda — APPROVED** [review]
have you populated the docker hub with this new image, otherwise, it will fail because this new image is not used and Azure already dropped install...

**Comment by SeanNaren** [comment]
> have you populated the docker hub with this new image, otherwise, it will fail because this new image is not used and Azure already dropped install...

I learnt from my master @Borda and have already :)

**Comment by Borda** [comment]
> > have you populated the docker hub with this new image, otherwise, it will fail because this new image is not used and Azure already dropped install...
> 
> I learnt from my master @Borda and have already :)

just noticed push/pull :D

**Review by tchaton — APPROVED** [review]
Smart !

**Pull request merged**
