### PR TITLE
Fix mypy 0.800 plus when prepending $PYTHONPATH to sys.path

### PR DESCRIPTION
**Pull request by sumanthratna**
## What does this PR do?

- makes mypy not complain about trying to use `str.split` on None
- fixes other mypy errors

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [x] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
nice, but it seems that for some reason it fails in other places, mind fix it too?

**Comment by sumanthratna** [comment]
> nice, but it seems that for some reason it fails in other places, mind fix it too?

Do you mean the ~31 other mypy errors? I'd be happy to fix them (I initially didn't because I didn't want the PR to become too bloated)

**Comment by sumanthratna** [comment]
> > nice, but it seems that for some reason it fails in other places, mind fix it too?
> 
> Do you mean the ~31 other mypy errors? I'd be happy to fix them

@Borda I have no idea why those are coming up (they should be ignored, according to `setup.cfg`). I'll keep thinking about this issue but for now, I think we should leave this PR as-is; what do you think?

**Comment by Borda** [comment]
> > > nice, but it seems that for some reason it fails in other places, mind fix it too?
> > 
> > 
> > Do you mean the ~31 other mypy errors? I'd be happy to fix them
> 
> @Borda I have no idea why those are coming up (they should be ignored, according to `setup.cfg`). I'll keep thinking about this issue but for now, I think we should leave this PR as-is; what do you think?

yes, it is a known issue with recent 0.800 see https://github.com/python/mypy/issues/8309
I have fixed it now so it shall be fine :]

**Review by Borda — APPROVED** [review]

**Review by tchaton — APPROVED** [review]

**Review by ydcjeff — APPROVED** [review]

**Review by carmocca — APPROVED** [review]

**Pull request merged**
