### PR TITLE
compatibility TM v0.4

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Fixes #<issue_number>

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by kaushikb11** [comment]
@Borda Why is this required?

**Comment by Borda** [comment]
> @Borda Why is this required?

TM with a recent 0.4 dropped some arguments...
cc: @awaelchli

**Review by carmocca — APPROVED** [review]

**Comment by Borda** [comment]
@tchaton is this also the logging you were talking about?
```
E       torch.multiprocessing.spawn.ProcessRaisedException: 
E       
E       -- Process 0 terminated with the following error:
E       Traceback (most recent call last):
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
E           fn(i, *args)
E         File "/home/runner/work/pytorch-lightning/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 175, in new_process
E           self.transfer_distrib_spawn_state_on_fit_end(results)
E         File "/home/runner/work/pytorch-lightning/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 252, in transfer_distrib_spawn_state_on_fit_end
E           atomic_save(self.on_save(self.lightning_module.state_dict()), last_path)
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1259, in state_dict
E           module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 421, in state_dict
E           with self.sync_context(dist_sync_fn=self.dist_sync_fn):
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/contextlib.py", line 113, in __enter__
E           return next(self.gen)
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 299, in sync_context
E           cache = self.sync(
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 272, in sync
E           self._sync_dist(dist_sync_fn, process_group=process_group)
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 213, in _sync_dist
E           output_dict = apply_to_collection(
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 195, in apply_to_collection
E           return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 195, in <dictcomp>
E           return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 191, in apply_to_collection
E           return function(data, *args, **kwargs)
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/distributed.py", line 120, in gather_all_tensors
E           torch.distributed.barrier(group=group)
E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2531, in barrier
E           work.wait()
E       RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [10.1.0.19]:33684
```

**Comment by tchaton** [comment]
> @tchaton is this also the logging you were talking about?
> 
> ```
> E       torch.multiprocessing.spawn.ProcessRaisedException: 
> E       
> E       -- Process 0 terminated with the following error:
> E       Traceback (most recent call last):
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
> E           fn(i, *args)
> E         File "/home/runner/work/pytorch-lightning/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 175, in new_process
> E           self.transfer_distrib_spawn_state_on_fit_end(results)
> E         File "/home/runner/work/pytorch-lightning/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 252, in transfer_distrib_spawn_state_on_fit_end
> E           atomic_save(self.on_save(self.lightning_module.state_dict()), last_path)
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1259, in state_dict
> E           module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 421, in state_dict
> E           with self.sync_context(dist_sync_fn=self.dist_sync_fn):
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/contextlib.py", line 113, in __enter__
> E           return next(self.gen)
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 299, in sync_context
> E           cache = self.sync(
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 272, in sync
> E           self._sync_dist(dist_sync_fn, process_group=process_group)
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/metric.py", line 213, in _sync_dist
> E           output_dict = apply_to_collection(
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 195, in apply_to_collection
> E           return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 195, in <dictcomp>
> E           return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 191, in apply_to_collection
> E           return function(data, *args, **kwargs)
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torchmetrics/utilities/distributed.py", line 120, in gather_all_tensors
> E           torch.distributed.barrier(group=group)
> E         File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2531, in barrier
> E           work.wait()
> E       RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [10.1.0.19]:33684
> ```

Yes.

**Review by justusschock — APPROVED** [review]

**Review by SeanNaren — APPROVED** [review]

**Comment by awaelchli** [comment]
one test failing, not yet sure what's up

**Review by awaelchli — APPROVED** [review]

**Pull request merged**
