### PR TITLE
remove extra kwargs from Trainer init

### PR DESCRIPTION
**Pull request by awaelchli**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## What does this PR do?
- If you misspell a Trainer arg, it will go to kwargs and there will be no error. This should not be. 
You can actually observe this in tests!

### CODE REVIEW

**Comment by awaelchli** [comment]
as you can see in the first commit here, the tests fail because the flags `train_check_interval` and `train_check_interval` do not actually exist!

**Comment by Borda** [comment]
we already had this discussion and it breaks inheritance...

**Comment by awaelchli** [comment]
where was the discussion? I would like to know how it breaks inheritance.

**Comment by Borda** [comment]
> where was the discussion? I would like to know how it breaks inheritance.

at least in IDE if the child has different arguments, @justusschock we talked about it, right?

**Comment by awaelchli** [comment]
well, that's very unfortunate, because this PR shows then the tests are flawed if we allow unknown flags to be passed in without throwing an error

**Comment by awaelchli** [comment]
So I looked at the discussion you link #1180 and I really don't get it. 

1. We don't have any subclasses of Trainer
2. Trainer doesn't even call super().__init__()
3. Some of the Mixins that Trainer inherits from have a __init__ (e.g. TrainerCallbackHookMixin) but they are never called because Trainer does not call super

@oplatek maybe you can explain it to me in super simple words? :)

**Comment by Borda** [comment]
@awaelchli I agree with you that the benefit of more strict testing is larger than having Trainer simple to inherit... @PyTorchLightning/core-contributors do you see use-case when user need to inherit Trainer and add/remove some arguments?

**Comment by oplatek** [comment]
I thought the main arguments were:

1. Users will subclass Trainer class for example create  `class SubTrainer(Trainer)`
2. Users will call super.init() in their SubTrainer class
3. For the SubTrainer is super convenient to just pass **kwargs in SubTrainer.__init__ to the Trainer.__init__ method

Ad 3 I see it as is super convenient but for very rare use case and I see it as error prone when creating Trainer instance e.g. Trainer(max_epochs) vs Trainer(max_pochs) which fails silently.

**Comment by awaelchli** [comment]
@optalek I agree with you, except that we don't have to make any compromises. 
See the test that I added, it shows that Subclassing and parsing the arguments is not probalem. 
At least I could not find one, but the test in my view proofs the basic use cases of inheritance as I know it.

**Comment by justusschock** [comment]
@Borda I don't remember having such a discussion with you, but that may also be on me :D 

In general I would also opt for removing kwargs wherever possible

**Comment by williamFalcon** [comment]
nice @awaelchli

**Pull request merged**
