### PR TITLE
Update Trainer config tests to use accelerator and devices

### PR DESCRIPTION
**Pull request by kaushikb11**
## What does this PR do?

Update Trainer config tests to use accelerator and devices

### Does your PR introduce any breaking changes? If yes, please list them.

None

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

cc @justusschock @awaelchli @rohitgr7 @borda @akihironitta

### CODE REVIEW

**Review by ananthsub — APPROVED** [review]

**Review by carmocca — APPROVED** [review]
Thanks for doing this!

**Review by awaelchli — COMMENTED** [review]
Where will the tests for the gpus=x notation move? It's not deprecated and we should still test it. What is the plan? Have we done that somewhere else?

**Review by four4fish — APPROVED** [review]

**Comment by four4fish** [comment]
Thank you for updating this @kaushikb11!!
@daniellepintz  this should make deprecate gpus, num_processes task easier.

**Review by daniellepintz — APPROVED** [review]

**Comment by kaushikb11** [comment]
> Where will the tests for the gpus=x notation move? It's not deprecated and we should still test it.

Updated the tests.

**Pull request merged**
