### PR TITLE
fix typo in Readme

### PR DESCRIPTION
**Pull request by skmatz**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?

Fixes typo in method's Docstrings.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by rish-16** [comment]
Thanks! Let me scan for others

**Comment by Borda** [comment]
@rish-16 just changed the name to Work-In-Progress, pls remove the tag from name when you finish scanning :]

**Comment by rish-16** [comment]
There are no other apparent errors in the README. Removing the tags

**Comment by rish-16** [comment]
Are 3 contributors supposed to approve this before merging? 😅 @Borda

**Pull request merged**
