### PR TITLE
Lightning_template.py fix

### LINKED ISSUE #2663: Template Module missing save_hyperparameters() /  has unused args
## 📚 Documentation / Examples

The main example is missing the current hparams best-practice outlined in: https://pytorch-lightning.readthedocs.io/en/latest/hyperparameters.html

This means in the current example there is no automatic tensorboard logging of hparams which is insanely useful.

It also includes ` optimizer_name: str = 'adam'` which is not actually used in `configure_optimizers()` since the optimizer is hard-coded to adam.

### PR DESCRIPTION
**Pull request by romesc-CMU**
## What does this PR do?

Fixes #2663

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
nO

### CODE REVIEW

**Comment by awaelchli** [comment]
> Did you have fun?
> nO

😢 

I'm wondering why this did not show up before, because we run the pl_examples from the test, right @Borda?

**Comment by Borda** [comment]
> I'm wondering why this did not show up before, because we run the pl_examples from the tests, right @Borda?

we run only two scripts with some default arguments, see https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/test_examples.py

**Comment by romesc-CMU** [comment]
Sorry I just realized this branch has the history of my other open PR! I can fix that.

Does the test currently check if `hparams` is logged?

**Comment by Borda** [comment]
> Sorry I just realized this branch has the history of my other open PR! I can fix that.

sure, just rebase to `upstream/master` or we can help :]

**Comment by romesc-CMU** [comment]
> > Sorry I just realized this branch has the history of my other open PR! I can fix that.
> 
> sure, just rebase to `upstream/master` or we can help :]

Should be all set now! 😁

**Pull request merged**
