### PR TITLE
epoch instead of step for epoch metrics

### PR DESCRIPTION
**Pull request by s-rog**
# What does this PR do?
change epoch lvl metrics to log using epoch instead of steps for x
addresses #3228 

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by awaelchli — CHANGES_REQUESTED** [review]
I'm not convinced. Metrics should be logged w.r.t. global step always to make them all comparable. In addition, we log epoch as a function of the global_step, so you can always select that as the abscissa in your logging tools.

**Comment by s-rog** [comment]
Oh I was only thinking about tensorboard logger, which doesn't let you do much in terms of comparing/overlaying different graphs/metrics.

I don't have much experience with other loggers so yes def still need more input from users of non-tb loggers.

**Comment by Borda** [comment]
@s-rog maybe a bit patient with implemented new features, till v1.0 we shall be very conservative with adding new things and I am also not very convinced about this API change... 🐰

**Comment by williamFalcon** [comment]
yeah let’s wait. this is also wrong. it would break all metrics.

**Pull request closed without merging**
