### PR TITLE
Fix failing conda CI

### PR DESCRIPTION
**Pull request by ydcjeff**
## What does this PR do?

Fixes master

`conda` isn't working sometimes, so removed it.

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.    
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by justusschock — APPROVED** [review]
LGTM since those commands aren't needed. Still is there another way to get those outputs?

**Comment by ydcjeff** [comment]
> LGTM since those commands aren't needed. Still is there another way to get those outputs?

Yes, there is pip

**Comment by SeanNaren** [comment]
Just for reference I assume this is the failing test: https://github.com/PyTorchLightning/pytorch-lightning/runs/1305924012. I assume it's failing because the reference to conda hasn't been correctly set? Just ensuring we're not breaking coverage of conda compatibility by removing these commands.

**Comment by ydcjeff** [comment]
> Just for reference I assume this is the failing test: https://github.com/PyTorchLightning/pytorch-lightning/runs/1305924012. I assume it's failing because the reference to conda hasn't been correctly set? Just ensuring we're not breaking coverage of conda compatibility by removing these commands.

Yes, those commands are just used to see info about envs, doesn't related to the tests and coverage.

**Review by Borda — CHANGES_REQUESTED** [review]
this looks rather we do not use Conda image

**Comment by Borda** [comment]
also fixed in #3658

**Comment by ydcjeff** [comment]
Closing it

**Pull request closed without merging**
