### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

Fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/5431

pre-commit and mypy are no longer enforced for PRs.
There's no point to keep mypy in pre-commit as any other PR might have broken it

Also mypy is usually too slow. It's better to run it in a separate CI job (if we choose to run it again in CI)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [n/a] Did you make sure to update the documentation with your changes? (if necessary)
- [n/a] Did you write any new necessary tests? (not for typos and docs)
- [n/a] Did you verify new and existing tests pass locally with your changes?
- [n/a] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Review by kaushikb11 — APPROVED** [review]

**Comment by ananthsub** [comment]
@carmocca n00b question: does this make it easier for PRs to not add typing? if it's run in a CI job, how do we ensure the local dev experience matches as closely as possible to lightning CI?

**Comment by williamFalcon** [comment]
@ananthsub the fewer checks contributors have to make on typing the more PRs we can land since this is a blocker for people (most aren’t familiar with typing).  but we all agree it’s important for consistency.  so, is there a happy medium where contributors don’t have to worry? but we run auto typing or something?

**Comment by justusschock** [comment]
@williamFalcon I am not aware of some autotyping. And I also somewhat disagree here. i think it is more frustrating to see a CI failure due to such things and don't have the proper config for local dev. So I'd rather have the pre-commit untouched (nobody is forced to use it).

**Comment by Borda** [comment]
> but we run auto typing or something?

sounds to me like you are asking if there is an auto programmer or something... 🐰 
I do not think that typing was a problem for anyone never the lest we still have most of our codebase ignoring mypy check so these checks are or at least shall be enforced only on files we ready did full typing so not dishonest work of people who spent their time just adding these types... :]

**Review by SkafteNicki — APPROVED** [review]

**Comment by justusschock** [comment]
@carmocca What about keeping it in pre-commit and replace precommit ci with separate CIs for other steps? Since pre-commit is not meant for CI, but for checking the files before you commit them (which shouldn't be many and thus being slow would be ok

**Comment by carmocca** [comment]
> does this make it easier for PRs to not add typing? if it's run in a CI job, how do we ensure the local dev experience matches as closely as possible to lightning CI?

There isn't any forced check right now for mypy or typing (other than our personal reviews) so I wouldn't say this makes it easier or harder. I don't know about others workflows but I usually focus on resolving the PR, push it, and then fix any typing/pep8 issues afterwards assuming a CI check is run for them. That is not the case anymore.

> What about keeping it in pre-commit and replace precommit ci with separate CIs for other steps? Since pre-commit is not meant for CI, but for checking the files before you commit them (which shouldn't be many and thus being slow would be ok

Running pre-commit in CI is cool with me (in fact, I prefer it for simplicity). However, I feel like mypy is kind of a heavyweight and I prefer to run it separately. Usually just `mypy` works

In any case we no longer run either any pre-commit hooks or mypy in CI. That's the point I was trying to make, that it doesn't make sense to keep it in pre-commit currently as it will fail due to any other PR which broke it.

If it was my choice to make, I'd keep all these things and run them in CI (`pre-commit` + `mypy`) but the decision was made a bit ago.

**Pull request merged**
