### PR TITLE
Improve skipping steps tests

### PR DESCRIPTION
**Pull request by carmocca**
## What does this PR do?

Leftovers from #3566

- Makes sure `validation_step` is called even though `training_step` is skipped
- Adds one test with only some skipped steps

## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

### CODE REVIEW

**Comment by awaelchli** [comment]
hmm, this new feature is automatically requesting review from everybody.
It was not intentional. The only thing I did was merge master with the button "update branch".

**Comment by Borda** [comment]
> hmm, this new feature is automatically requesting review from everybody.
> It was not intentional. The only thing I did was merge master with the button "update branch".

which feature?

**Comment by edenlightning** [comment]
hi @carmocca, is this PR still needed?

**Comment by carmocca** [comment]
The added tests do not fail on master. But they could avoid a bug in the future. If core thinks there is value in having them, they can merge it. Although it's not strictly necessary

**Comment by carmocca** [comment]
Closing, considering there doesn't seem to be interest in these

**Comment by Borda** [comment]
@carmocca sorry, I have missed this one, let me check it again :]

**Comment by Borda** [comment]
@tchaton

**Review by Borda — COMMENTED** [review]
lgtm

**Review by ydcjeff — APPROVED** [review]

**Review by tchaton — APPROVED** [review]

**Review by SeanNaren — APPROVED** [review]

**Pull request merged**
