### PR TITLE
Fix pre-commit fix for isort for benchmark folder.

### PR DESCRIPTION
**Pull request by arnaudgelas**
Following @Borda 's input, here is the fix for isort for benchmark folder.

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
how it differs from #5387? it seems to fix the same thing...

**Comment by arnaudgelas** [comment]
@Borda I am confused. I am opening PRs to be merged onto release/1.2-dev, but you also want me to open PRs to be merged onto master. Is that correct?

**Comment by Borda** [comment]
> @Borda I am confused. I am opening PRs to be merged onto release/1.2-dev, but you also want me to open PRs to be merged onto master. Is that correct?

all import/isort fixes shall go to 1.2 (here it was just reopened as stated isort and for each PR we can change target any time later, just it may contain collisions so I was thinking about using it...)
compare to the whitespaces which were already merged to master

**Comment by Borda** [comment]
closing in favor #5400

**Pull request closed without merging**
