### PR TITLE
ensure reset method works in notebooks

### LINKED ISSUE #1092: tqdm fails in notebook for versions tqdm< 4.41.0
##  🐛 Bug

tqdm_notebook doesn't have a `reset` method until [version 4.41.0](https://github.com/tqdm/tqdm/releases/tag/v4.41.0). Training fails in notebooks if you have a lower version of tqdm (current requirements enforce >=4.35.0).

### To Reproduce

Train any model with tqdm<4.41.0 in a Colab notebook.

### Expected behavior

```
AttributeError: 'tqdm_notebook' object has no attribute 'reset'
```

### PR DESCRIPTION
**Pull request by jeremyjordan**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CHANGELOG.md)?

## What does this PR do?
Fixes #1092 most likely also #1112

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
hey there, we have added GPU CI test, so could we kindly ask to rebase/merge master which will trigger these tests so we do not need to test it manually... Thx for your understanding :robot:

**Comment by Borda** [comment]
@jeremyjordan we have added GPU CI test, so could we kindly ask to rebase/merge master which will trigger these tests so we do not need to test it manually... Thx for your understanding :robot:

**Comment by jeremyjordan** [comment]
@Borda oops, thanks for the tag - somehow missed your first message.

**Comment by yikuanli** [comment]
Sorry, not sure I understand what's the solution here, could you please be more specific what do you mean about reset methods ? Thanks a lot

**Pull request merged**
