### PR TITLE
Weekly Patch Release v.1.2.6 [full merge, no squash]

### PR DESCRIPTION
**Pull request by carmocca**
## PR review

related to #6083

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Comment by Borda** [comment]
shall we include `RunIf` in this release?
cc: @PyTorchLightning/core-contributors

**Comment by carmocca** [comment]
I don't see why not. It's testing code. Can't even be imported by users.

**Comment by SeanNaren** [comment]
> shall we include `RunIf` in this release?
> cc: @PyTorchLightning/core-contributors

please do, it will make further releases more manageable

**Review by tchaton — APPROVED** [review]
LGTM ! Great work !

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
