### PR TITLE
move pl_develop & add Datasets

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Move datasets to PL utils as they will be used also in PL-Bolts
Added CIFAR dataset with the tiny version...

Fixes # (issue)

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by justusschock** [comment]
One general question: Those datasets are a very specific case and does not apply for all users (e.g only for vision guys). Shall we rather move them to bolts entirely?

**Comment by Borda** [comment]
> One general question: Those datasets are a very specific case and does not apply for all users (e.g only for vision guys). Shall we rather move them to bolts entirely?

the point is that we want to use them in the test for Pl as well as Bolts... and if we have it in bolts we need to copy-paste it is here so I thought that we could have the basic here... or do you have any other ideas how to structure this?

cc: @PyTorchLightning/core-contributors

**Comment by Borda** [comment]
After a chat with @justusschock we came with an idea to move all Test template and datasets to `pl_develop` as we want to clearly separate it from PL but we (or at least me) feel that this still may be useful for other depending projects (for sure for Bolts) and at this moment they are not installable

> we developed own / hacked own mainly for testing
> as we wanted just a partition of the general dataset
> and as I see some other people may be interested in using it too
> so not sure at this moment

cc: @awaelchli

**Comment by Borda** [comment]
there is a problem with Horovod, but not sure why... @tgaddair any idea?

**Comment by tgaddair** [comment]
> there is a problem with Horovod, but not sure why... @tgaddair any idea?

Looks like an issue with the dataset.  I'll take a look today and try to repro.

**Comment by Borda** [comment]
> Looks like an issue with the dataset. I'll take a look today and try to repro.

we are postponing this for no, so no need, bt thx :rabbit:

**Pull request closed without merging**
