### PR TITLE
Clarify what gpus=0 means in docs

### LINKED ISSUE #2837: Trainer.on_gpu incorrectly set to False when specifying `gpus=0`
## 🐛 Bug

When creating a trainer with the arg `gpus=0`, the field `on_gpu` is always set `False`, even on machines with CUDA available.

The existing logic for `on_gpu` is:

```
self.on_gpu = True if (gpus and torch.cuda.is_available()) else False
```

is buggy because `0` is "falsy". It should probably be:

```
self.on_gpu = gpus is not None and torch.cuda.is_available()
```

### To Reproduce

```
trainer = trainer.Trainer(gpus=0, ...)
```

### PR DESCRIPTION
**Pull request by awaelchli**
## What does this PR do?

Fixes #2837

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by ydcjeff** [comment]
@Borda @awaelchli 
would it be also good to add this?
```py
# train on GPUs 1 and 4 across nodes
trainer = Trainer(gpus=[1, 4], num_nodes=4)
```

**Comment by awaelchli** [comment]
not sure, there is already
`trainer = Trainer(gpus=2, num_nodes=4)
`
a few lines below.
not sure if it is substantially different in the information provided, but I have no objections.
@Borda ?

**Comment by Borda** [comment]
> @Borda @awaelchli
> would it be also good to add this?
> 
> ```python
> # train on GPUs 1 and 4 across nodes
> trainer = Trainer(gpus=[1, 4], num_nodes=4)
> ```

this would fail on a machine without GPU, so that why do not have it in tested code...

**Comment by ydcjeff** [comment]
Okay, Got it

**Comment by williamFalcon** [comment]
i like the example.  i wouldn’t object but no strong feelings on this

**Pull request merged**
