### PR TITLE
Remove unnecessary warning in `DDPSpawnPlugin`

### PR DESCRIPTION
**Pull request by rusty1s**
## What does this PR do?

This PR removes the `cleaning up ddp environment...` warning when using `ddp_spawn` training type, as PyTorch Lightning shouldn't print out a warning that one cannot resolve :)

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Comment by awaelchli** [comment]
Hi @rusty1s
Thanks for that. This is currently being addressed and discussed in #10864 (no consensus yet). Feel free to participate in the discussion there too.

**Comment by rusty1s** [comment]
Thanks for letting me know. I missed this :)

**Comment by rusty1s** [comment]
I'm fine with converting that to a `rank_zero_info` or a `rank_zero_debug` call, but it shouldn't be a warning nonetheless :)

**Comment by awaelchli** [comment]
Sounds good, thx for your input! Everyone agrees so far that it should definitely not be a warning. Should be resolved soon.

**Pull request closed without merging**
